### ISSUE TITLE
Unable to start Serial Monitor (again)

### ISSUE THREAD

**Issue by Awbmilne** [microsoft/vscode-arduino#1002]
Having an issue with opening the serial port on VScode Arduino extension. 

**Also**: Manually setting the serial port works through the settings.json file, but cannot open serial port selection menu with status bar button or command palette.

It seems others have had this issue in the past 2 weeks on #851. People have been rolling back their VScode versions to get it to work again. 

Getting error:
```
Failed to open serial port COM3 due to error: + TypeError: Cannot read property 'close' of null
```

**This is different from the existing issues  #774 and #851 from July 2019.** _Different software version_

VSCode Version: 1.43.1
Arduino Extension Version: 0.2.29
Arduino IDE Version: 1.8.12

**Comment by dilin-MS** [comment]
Duplicate as #980
