### ISSUE TITLE
Visual Code can´t find the Arduino IDE

### ISSUE THREAD

**Issue by El-Programador4** [microsoft/vscode-arduino#1011]
I don't know how to solve it, visual code  can´t find the Arduino IDE.
![Sin título](https://user-images.githubusercontent.com/63022844/78191940-61dc9e00-7477-11ea-9c1b-8f01fbdfc8ae.png)

**Comment by hellyzh** [comment]
Please set `arduino.commandPath` to `arduino_debug.exe` and `arduino.path` to `G:\Arduino`, and restart your vscode.
![image](https://user-images.githubusercontent.com/49181894/78200811-56629480-74c2-11ea-9525-f725859d460d.png)
![image](https://user-images.githubusercontent.com/49181894/78200834-6f6b4580-74c2-11ea-9e5e-e1b9ed95646a.png)

**Comment by hellyzh** [comment]
#979 Visual Code can´t find the Arduino IDE

**Comment by El-Programador4** [comment]
That doesn't work for me
![Anotación 2020-04-02 131621](https://user-images.githubusercontent.com/63022844/78243530-380d9080-74e4-11ea-9c9b-c38100049007.png)

**Comment by hellyzh** [comment]
change it to `"arduino.path": "G\\Arduino\\arduino-1.8.12"`

**Comment by Iyaka25747** [comment]
I have the same issue but work with Unbuntu. Could you help me to figure out what arduino.path shall I use to bypass this issue ?

**Comment by hellyzh** [comment]
@Iyaka25747 , thank you for confirm working. If no more issue, will close this issue.

**Comment by rohit-singh-gautam** [comment]
I installed Arduino using Windows Store, now unable to find the path of Arduino, how to resolve this?

**Comment by hellyzh** [comment]
Arduino using windows store is not supported, you need to install Arduino IDE.
