### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by k1215tian** [microsoft/vscode-arduino#1013]
- Issue Type: `Performance`
- Extension Name: `vscode-arduino`
- Extension Version: `0.3.0`
- OS Version: `Windows_NT x64 10.0.10586`
- VSCode version: `1.43.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\mis-dev\vsciot-vscode.vscode-arduino-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by rrakso** [comment]
Here the same
[vsciot-vscode.vscode-arduino-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-arduino/files/4651168/vsciot-vscode.vscode-arduino-unresponsive.cpuprofile.txt)

**Comment by hellyzh** [comment]
Arduino extension v0.3.1 is released.
