### ISSUE TITLE
WiFiClientSecure has no member "verify"

### ISSUE THREAD

**Issue by hasanemretonguc** [microsoft/vscode-arduino#1019]
am i doing something wrong ?

![err](https://user-images.githubusercontent.com/13487220/79087654-a6eeb300-7d48-11ea-8233-42b1b5f93c53.PNG)

**Comment by hellyzh** [comment]
It looks like the board package issue. Have you selected the right board?
![image](https://user-images.githubusercontent.com/49181894/79094198-5186c600-7d89-11ea-911c-d8290e9beaf3.png)

**Comment by hasanemretonguc** [comment]
im using nodemcu v3 board. i change to generic esp8266. issue still persist
![err](https://user-images.githubusercontent.com/13487220/79109971-22208b00-7d82-11ea-9635-89f0292b1c96.PNG)

**Comment by hellyzh** [comment]
You can go to definition of WiFiClientSecure to check if there is member "verify". It should be other member like "connected", "available".

**Comment by hasanemretonguc** [comment]
looks like it is
![err](https://user-images.githubusercontent.com/13487220/79216313-a263f080-7e55-11ea-89df-93a56dfe913a.PNG)

**Comment by hellyzh** [comment]
Is `"Arduino: Verify"` or `"Arduino: Upload"` working or not? If yes, it may be intellisense issue.

**Comment by hasanemretonguc** [comment]
verify and upload works

**Comment by hellyzh** [comment]
It should be issue for the intellisense, please check the setting of file .vscode/c_cpp_properties.json according to [link](https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference).

**Comment by hasanemretonguc** [comment]
i couldnt find the problem can you help with that 
![err](https://user-images.githubusercontent.com/13487220/79616384-97d38080-810d-11ea-936e-e12d67f0057b.PNG)

**Comment by hellyzh** [comment]
Please also try to specify `"compilerPath"`

**Comment by adiazulay** [comment]
IntelliSense auto-generation has been added in v0.4.0. If you're having any problems with IntelliSense please open a new issue.
