### ISSUE TITLE
Serial monitor failed when restart the Arduino board

### ISSUE THREAD

**Issue by mynameisbill2** [microsoft/vscode-arduino#1028]
Serial monitor failed when I restart the Arduino board(ESP8266), like this ...

![image](https://user-images.githubusercontent.com/32593114/80661759-26f37780-8ac2-11ea-9801-e7f31f497caf.png)

But the same action in Arduino IDE is OK!

![image](https://user-images.githubusercontent.com/32593114/80661885-85205a80-8ac2-11ea-8b0d-72dec7579a0a.png)

- Arduino IDE Version: 1.8.12
- VS Code Version: 1.43.2
- VS Code Arduino Extension Version: 0.3.0
- OS: Win8.1 Pro

**Comment by hellyzh** [comment]
It looks like the same issue as #[1015](https://github.com/microsoft/vscode-arduino/issues/1015)(Serial Monitor keeps ESP devices in flash mode), Will serial monitor work if unplug and re-plug the ESP8266?

**Comment by mynameisbill2** [comment]
Yes, It's the same problem.
