### ISSUE TITLE
Detach Serial Monitor

### ISSUE THREAD

**Issue by MikeAUT** [microsoft/vscode-arduino#1030]
Hi all,
Is it possible to make the Serial Monitor detachable from the main window? Working on a 21:9 doesn't leave much space for the monitor, especially when many data comes in :)

**Comment by hellyzh** [comment]
You can maximize the window.
![image](https://user-images.githubusercontent.com/49181894/82532256-8bf73600-9b73-11ea-868e-4cd24b527cae.png)

**Comment by MikeAUT** [comment]
I allready knew that ;)
But it would be great to completely detach it and drag it to another monitor for example. But i don't think this is possible with VSC
