### ISSUE TITLE
Error - cannot open source file "avr/pgmspace.h"

### ISSUE THREAD

**Issue by cvmanjoo** [microsoft/vscode-arduino#1031]
Hi Someone can help?
I'm getting this error. Code complies fine but intellisense does not.

```
#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (C:\Users\Manjunath CV\Documents\Arduino\sketch_may08b\sketch_may08b.ino).C/C++(1696)
cannot open source file "avr/pgmspace.h" (dependency of "C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\Arduino.h")C/C++(1696)
```

Thanks

**Comment by hellyzh** [comment]
Please check your IntelliSense setting according to https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference.

**Comment by ar-std** [comment]
I do have the same problem and already posted a more explanatory question on [stack**overflow**](https://stackoverflow.com/questions/61954481/intellisense-throws-include-errors-when-working-with-arduino-in-vs-code). Maybe this helps.

**Comment by adiazulay** [comment]
IntelliSense auto-generation has been added in v0.4.0. If you're having any problems with IntelliSense please open a new issue.
