### ISSUE TITLE
Hi, I have a dumb but anoying problem with the setting.json, help pls!

### ISSUE THREAD

**Issue by JunkDogg** [microsoft/vscode-arduino#1032]
I mess the paths and now I dont know how to reset or what to write, I´m completly lost.

![Captura de pantalla (240)](https://user-images.githubusercontent.com/42895520/81859373-71b2cc00-9565-11ea-8eb7-7f9f03ddb43d.png)

**Comment by hellyzh** [comment]
Please refer to #1011 Visual Code can´t find the Arduino IDE

**Comment by JunkDogg** [comment]
okey, done.
