### ISSUE TITLE
How to enable Colorized Serial Monitor?

### ISSUE THREAD

**Issue by Nathan-ma** [microsoft/vscode-arduino#1037]
Is there an easy way to enable colorized Serial Monitor?

pySerial example (not a very good one)
![image](https://user-images.githubusercontent.com/11060905/83033328-5d62da80-a00d-11ea-9a64-3e1bdfb44dec.png)

Screen example
![image](https://user-images.githubusercontent.com/11060905/83033435-7c616c80-a00d-11ea-92d7-76a489a4809d.png)

**Comment by gcampbell-msft** [comment]
@Nathan-ma We have recently updated the Arduino extension to depend on a new standalone Serial Monitor extension, please upgrade your arduino extension and try out this new feature!
