### ISSUE TITLE
Support VS Code on Windows on ARM

### ISSUE THREAD

**Issue by dilin-MS** [microsoft/vscode-arduino#1041]
Related to [98818](https://github.com/microsoft/vscode/issues/98818)

To support VS Code on Windows on ARM, native node in `node-usb-native`, `serialport`, `usb-detection` will need to be rebuilt.

**Comment by robotdad** [comment]
VS Code is available on ARM now. I need to take a look at what would be required for the underlying dependencies here to see if we can enable this or not.

**Comment by maddogjt** [comment]
@robotdad happy to help take a look at this if you'd like, can test on raspberry pi, which I assume is a likely target device for this feature.

**Comment by robotdad** [comment]
Thanks! I'll let you know if (when) we decide to take this on.

**Comment by robotdad** [comment]
Adding the serial tag here as the native components that need to be compiled for arm are for serial port access

**Comment by gcampbell-msft** [comment]
@dilin-MS We have recently updated the Arduino extension to depend on a new standalone Serial Monitor extension, please upgrade your arduino extension and try out this new feature!

Let us know if it solves your issue or if the issue still persists!
