### ISSUE TITLE
Update 0.31 ruins Arduino serial port reset

### ISSUE THREAD

**Issue by iqapps** [microsoft/vscode-arduino#1053]
After doing code upload, subsequent disconnect/connect serial port operations by cliking VSCode serialport icon, does not properly reset Arduino (in my case Arduino Mega Embed USB CH340) since extension update 0.31.

Reverting to version 0.30 restores expected reset function.

**Comment by iqapps** [comment]
Any news on this. Will it be fixed.

I cannot upgrade beyond v 0.30 since my normal development method is invalidated as the Arduino does not reset after second upload.

What does the "external" label mean ?

**Comment by robotdad** [comment]
We're starting to go through the backlog now. I'll report back after we have done some initial prioritization. I don't know how the external label was being used, I've removed it. This is more meaningfully grouped with other serial port issues.

**Comment by iqapps** [comment]
This is probably back, after the lastest releases, but now seen with a FTDI chip Arduino Nano.

see [vscode/issues/125911](https://github.com/microsoft/vscode/issues/125911)

**Comment by gcampbell-msft** [comment]
@iqapps We have recently updated the Arduino extension to depend on a new standalone Serial Monitor extension, please upgrade your arduino extension and try out this new feature!

Let us know if it solves your issue or if the issue still persists!
