### ISSUE TITLE
Arduino Leonardo Serial Terminal broken in 0.3.1

### ISSUE THREAD

**Issue by dougy83** [microsoft/vscode-arduino#1063]
Issue Type: <b>Bug</b>

Hi. The latest update 0.3.1 seems to have shagged the serial monitor for Arduino Leonardo -- presumably the DTR isn't set appropriately :( 

`while(Serial) ;` will run forever waiting for an appropriate DTR state

I've just rolled back to 0.3.0, which works well.

Extension version: 0.3.1
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

**Comment by hellyzh** [comment]
#1053

**Comment by sajayantony** [comment]
Confirmed that this is a regression. The serial monitor can't connect in the current version.

**Comment by adiazulay** [comment]
This is fixed in v0.3.4
