### ISSUE TITLE
IntelliSense shows multiple errors but program compiles and runs fine on Arduino Uno

### ISSUE THREAD

**Issue by Gostas** [microsoft/vscode-arduino#1072]
I am making a program for my Arduino Uno using the Arduino extension in vs code. Although my program compiles, uploads and runs just fine, I get multiple errors and I can't find why. From my understanding, there seem to be a few bugs with IntelliSense and this should be one of them.

c_cpp_properties.json:
![image](https://user-images.githubusercontent.com/16310050/87666695-aa586700-c79b-11ea-8fe8-c0d3a7a29987.png)

arduino.json:
![image](https://user-images.githubusercontent.com/16310050/87666743-be03cd80-c79b-11ea-96b4-5efda77082b5.png)

Example of errors:
![image](https://user-images.githubusercontent.com/16310050/87666843-f3102000-c79b-11ea-87e8-9f391219385b.png)
![image](https://user-images.githubusercontent.com/16310050/87666912-0e7b2b00-c79c-11ea-8ff8-ed09d8f9e60f.png)

Any help appreciated!

**Comment by hellyzh** [comment]
You can try to change the default "compilerPath". It is in the compile log which should be `"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++"`.

**Comment by Gostas** [comment]
That helped, thank you!
However, I now get "IntelliSense mode msvc-x64 is incompatible with compiler path."
What should the IntelliSense mode be?

**Comment by HEMISixty** [comment]
I followed the suggestion and this is what eliminates both problems:

            "intelliSenseMode": "gcc-x64",
            "compilerPath": "C:/Program Files (x86)/Arduino/hardware/tools/avr/bin/avr-g++.exe",

**Comment by Gostas** [comment]
Yup that works, cheers!
