### ISSUE TITLE
Serial port opened and can transmit but receive nothing

### ISSUE THREAD

**Issue by petesg** [microsoft/vscode-arduino#1073]
I can successfully open a serial port to my Adafruit Grand Central M4 from within VS Code and send serial messages with "Send Text to Serial Port" which I have verified the board receives and interprets properly, however no messages from the M4 can be seen in the serial monitor from within VS Code.

**Comment by hellyzh** [comment]
#1054 Unable to start serial monitor

**Comment by adiazulay** [comment]
closing duplicate issue (#1054). Feel free to reopen if I misunderstood.
