### ISSUE TITLE
include library zip

### ISSUE THREAD

**Issue by jolugama** [microsoft/vscode-arduino#1075]
Hi, 

I have several examples  I have private libraries. I dont know how include this zip files.

**Comment by hellyzh** [comment]
Please try to extract the zip file to C:\Users\[user]\Documents\Arduino\libraries, and run `"Arduino: Library Manager"` to include the library to the example sketch. Also you can check the guide for [writing a library for Arduino](https://www.arduino.cc/en/Hacking/libraryTutorial).

**Comment by jolugama** [comment]
It`s working!! in c_cpp_properties.json, includePath, i add this : "/home/MYUSER**/snap/arduino/current/Arduino",

This directions is the same like in arduino: file, preferencies, proyect location. 

Then,  right button on mouse in library in visual code, add library.     

Thanks!!!!

**Comment by olawalejuwonm** [comment]
> It`s working!! in c_cpp_properties.json, includePath, i add this : "/home/MYUSER**/snap/arduino/current/Arduino",
> 
> This directions is the same like in arduino: file, preferencies, proyect location.
> 
> Then, right button on mouse in library in visual code, add library.
> 
> Thanks!!!!

Please I do not understand this.

How can I make this work for me?
