### ISSUE TITLE
Include file not found in browse.path. [1,1]

### ISSUE THREAD

**Issue by soham2002** [microsoft/vscode-arduino#1086]
I had just started learning C programming for my first semester. But VS Code is showing some problems...
Is there a way to fix this? I had installed the **C/C++** and the **Code Runner** extensions, but still, it's not compiling  :(

![prob](https://user-images.githubusercontent.com/59365699/90752379-efb90880-e2f4-11ea-8ada-71363cd6a531.jpg)

**Comment by hellyzh** [comment]
Please follow the [guide](https://code.visualstudio.com/docs/cpp/customize-default-settings-cpp) to set up the config file c_cpp_properties.json, and open issue in the repo of [c/c++ intellisense](https://github.com/Microsoft/vscode-cpptools).

**Comment by adiazulay** [comment]
This appears to be a c/c++ issue, you can file in the c/c++ extension repo: https://github.com/microsoft/vscode-cpptools/issues
