### ISSUE TITLE
Print time in serial monitor

### ISSUE THREAD

**Issue by astroanax** [microsoft/vscode-arduino#1088]
How can I print the time in serial monitor?
![esp](https://user-images.githubusercontent.com/57185902/90953216-1f981580-e487-11ea-9dd0-3f827302797b.JPG)
I couldn't tell apart how long the gap was when the above lines of output were being printed
In the Arduino IDE, there is a option for time, like so:

![Capturearduino](https://user-images.githubusercontent.com/57185902/90953318-db594500-e487-11ea-8769-c7ab1cba4f2b.JPG)

**Comment by Phantom-Rehan** [comment]
I hope this is being taken for consideration, it would be a really nice feature to include

**Comment by nikodiyana** [comment]
This is a feature that I really need in VS Code. A lot of debugging is done by comparing the Serial output's timestamps. (ie: interrupts taking place at the same time, etc).
Also the refresh rate of the Serial monitor is currently quite slow.

**Comment by NbrTDB** [comment]
+1 I could really do with this as well, and I agree, I noticed the refresh rate was slow. I'm guessing this would also be an issue for timestamp purposes.

**Comment by alka79** [comment]
+1000
a timestamp is a must for Serial output. Please make it optional to please everyone.

**Comment by blabber666** [comment]
+1 on the timestamp in the serial monitor.

**Comment by AutonomousPi** [comment]
+1 a timestamp is really necessary.

**Comment by donwinchell** [comment]
+1 for timestamp

**Comment by benmcmorran** [comment]
This issue has been fixed in the latest release of this extension, which is available in the VS Code extension marketplace.
