### ISSUE TITLE
Syntax highlighting and #ifdef

### ISSUE THREAD

**Issue by didiergm** [microsoft/vscode-arduino#1094]
VSCode 1.48.2 / Arduino extension 0.3.2

When using #define to use different chunks of code with #ifdef .. #endif the portions of code /excluded/ used to be greyed out by the syntax highlighter.

it does not seem to be the case anymore not sure whether if it comes from a VSCode update or the extension update.

Hope this is clear as English is not my main language

**Comment by hellyzh** [comment]
The language intelliSense function is provided by the extension dependency of C/C++. I checked that the excluded portions of code are greyed out if installed the latest version 0.29.0 of C/C++ extension.
![image](https://user-images.githubusercontent.com/49181894/92063291-70840400-edcd-11ea-8942-ec2efb739328.png)

**Comment by didiergm** [comment]
Just checked I am on 0.30.0-insider4, tried to downgrade to 0-29-0 but
VSCode reloaded 0.30.0-insider4 immediately, not sure what to do ...

**Comment by hellyzh** [comment]
Please try to "Disable Auto Updating Extensions" according to https://code.visualstudio.com/docs/editor/extension-gallery.

**Comment by didiergm** [comment]
It did work & indeed v 0.29.0 of the extension displays the desired
behaviour

**Comment by adiazulay** [comment]
this appears to be resolved in c/c++ extension. Please reopen if this is still an issue.
