### ISSUE TITLE
cannot open source file "BLEPeripheral.h"C/C++(1696)

### ISSUE THREAD

**Issue by stormbytes** [microsoft/vscode-arduino#1106]
Having a lot of issues with this plugin.

Everything compiles just fine and uploads but intellisense is showing squiglies and I'm getting errors in the "problems" tab. 

I'm on Mac OS 10.15.6.  

Getting a squigly / error when trying to #include <BLEPeripheral.h> which is in ../libraries/BLEPeripheral.

Sketch is in Users/storm/Documents/Arduino/led_callback/

// c_cpp_properties.json

{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "/Users/storm/Library/Arduino15/packages/arduino/tools/**",
                "/Users/storm/Library/Arduino15/packages/arduino/hardware/samd/1.8.8/**",
                "Users/storm/Documents/Arduino/libraries/**"
            ],
            "forcedInclude": [
                "/Users/storm/Library/Arduino15/packages/arduino/hardware/samd/1.8.8/cores/arduino/Arduino.h"
            ],
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ],
            "intelliSenseMode": "clang-x64",
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
}

// arduino.json

{
    "port": "/dev/cu.usbmodem401301",
    "board": "arduino:samd:arduino_zero_native",
    "programmer": "AVRISP mkII",
    "sketch": "led_callback.ino"
}

**Comment by adiazulay** [comment]
IntelliSense auto-generation has been added in v0.4.0. If you're having any problems with IntelliSense please open a new issue.
