### ISSUE TITLE
Is this extension made by interns?

### ISSUE THREAD

**Issue by clankill3r** [microsoft/vscode-arduino#1108]
The first time I used this extension was about 3 years ago when it was really bad.
Today I gave it another try, and not much has improved since then. Someone told me that this extension is made by interns at microsoft, is this true?

**Comment by robotdad** [comment]
This is not constructive feedback. If you have specific issues please either log them or upvote existing issues that impact you. Also, our interns build some amazing features/products which is why we hire so many of them.
