### ISSUE TITLE
Library search, Serious lack of performance and visual feedback! 

### ISSUE THREAD

**Issue by starkapandan** [microsoft/vscode-arduino#1109]
I absolutely love vscode with Arduino for everything 10 stars for that! 

But the issue is with the library search... Im very sorry to say this but Holy Cow i have never seen a worst implemented search box, which made me want to go here and post this after being frustrated with it for so long. And maybe this post can help someone else frustrated that thinks that their is something wrong with their libraries/setup.

--Simple Visual that are truly needed without anyone having to say this --
1. There is NO visual indication if it is searching!
2. There is NO visual indication if finished searching! (How long do we wait? XD)
3. There is NO visual indication of a button to press(which makes me believe that it auto searches, which makes the above two points more frustrating!)

--Bugs--
Other than those actual visual flaws, there are bugs but of course they are relativly more unexpected to fix. Atleast i can say what they are for future reference.

* Searching for a library, sometimes they don't show up(may be because of the visual flaws stated above, and maybe we have to wait for example 10min before they show up, well we don't know that since it's impossible to say if it still searching XD).

- Temporary Solution 1: Refresh Library Index multiple times and search again or Close and reopen visual studio multiple times combining pressing refresh library index and clearing search box and retyping... Repeat all of those step multiple times until it finds your wanted search result.
- Temporary Solution 2: If you have imported on previous projects and want to avoid the pain of going through the library manager searching, copy and paste from .vscode folder the libs you need.

**Comment by nya3jp** [comment]
I found that the library search UI throws an unhandled exception when the number of search results becomes a few. I've sent #1500 to fix it.
