### ISSUE TITLE
[Board/Library manager] The web view is reloadd when switching between tabs

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode-arduino#112]
See the below gif, the page is totally refreshed and my Type filter is lost
![bug-switch](https://cloud.githubusercontent.com/assets/1050213/23883187/5e05d54e-08a0-11e7-86bb-d95620b308b3.gif)

**Comment by czgtest** [comment]
this issue is also repro on now.

**Comment by czgtest** [comment]
This is the vscode behavior. see vscode bug Microsoft/vscode#15437
