### ISSUE TITLE
Serial port open - does not reset Arduino boards

### ISSUE THREAD

**Issue by iqapps** [microsoft/vscode-arduino#1134]
Applies to Arduino Extension v0.3.3

Serial port does not reset Arduino board after connecting. Seems like DTR signalling is broken on Open serial port.

We need to be able to automatically reset the Arduino after uploading finishes.

It is one of the key features in the Arduino hardware design, that DTR is toggled to reset the Arduino after uploading code to it.

**Comment by adiazulay** [comment]
this is resolved in v0.3.4

**Comment by alka79** [comment]
If this feature has to stay, could you make it optional ?

In many situations, you just want to open a com port to read messages WITHOUT reset. Current 0.3.4 systematically resets when you open the com port :-(

In my experience, arduino automatically resets when you physically plug to the serial port and after upload, not when a remote Serial communication software opens a com port.

**Comment by adiazulay** [comment]
That shouldn't be too hard to do. Can you open a new issue so we can track the feature request?

**Comment by alka79** [comment]
done. https://github.com/microsoft/vscode-arduino/issues/1154
