### ISSUE TITLE
changing the default c_cpp_properties created

### ISSUE THREAD

**Issue by KnifeOfDunwall** [microsoft/vscode-arduino#1139]
when i start working with it a default c_cpp_properties is created. this includes:
```
"includePath": [
                "C:\\Program Files (x86)\\Arduino\\tools\\**",
                "C:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\**"
            ],
```
however for intellisense to work correctly i also need to add `"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr\\avr\\**"`
is there a way to also add this line to the "default creation" of the file or do i need to add it manually everytime i start a new project without adding it to c_cpp.default which would include it in every c/c++ project?

**Comment by adiazulay** [comment]
tracking this with #438
