### ISSUE TITLE
Code OSS: command 'arduino.selectSerialPort' not found

### ISSUE THREAD

**Issue by aynurin** [microsoft/vscode-arduino#1145]
Hi there,

My configuration:

- Linux x64 5.9.8-2-MANJARO
- Code OSS 1.51.1
- vscode-arduino-0.3.3
- Arduino IDE 1.8.13

What's happening:

- Trying to select port by going Ctrl+Shift+P -> Arduino: Select Serial Port.
- Expecting to get a list of ports to choose from.
- Instead of that getting an error: `command 'arduino.selectSerialPort' not found`

`ls -la /dev/ttyU*` is showing my port, as well as Arduino IDE. Arduino IDE works fine (launches, opens port, opens serial monitor, receives data from serial port). I just updated my system this morning, updating Code OSS and Arduino IDE at once. Before the update I had ~two months old versions and it worked well.

Tried to re-install the extension but after the update, Code OSS stopped showing the `vscode-arduino` extension in the extensions list I had to set `extensionsGallery` to [point to VS Code extensions gallery](https://github.com/Microsoft/vscode/issues/23831) and uninstall/reinstall the extension. That didn't change the above behavior.

Looking forward to any advise!

Thanks,
Shavkat

**Comment by gcampbell-msft** [comment]
@aynurin We have recently updated the Arduino extension to depend on a new standalone Serial Monitor extension, please upgrade your arduino extension and try out this new feature!

Let us know if it solves your issue!
