### ISSUE TITLE
Upload and Serial Monitor management : auto close/reopen

### ISSUE THREAD

**Issue by alka79** [microsoft/vscode-arduino#1147]
Hi,
In Arduino IDE, if you upload while Serial port is open, the IDE closes temporarilly the com port and re-opens it automatically at the end of the upload. The board is reset _once_ at the end of the upload.

Interestingly, when I upload while the Serial Monitor is open, VSCode closes the com port and re-opens it immediately. This _resets_ the board. Thus, the upload will fail because com port is busy. 
I see the intention to manage properly the Serial Monitor during uploads but it seems to fail. 

I must quickly close manually the serial , wait for the upload to finish (which _resets_ the board) and re-open the Serial which _resets_  the board once more. That is a total 3 resets.

v0.34 seems to have created a mess.

Do I miss something ?

I run VSCode 1511,  arduino extension 0.34 with  NodeMCU ESP8266 boards.

**Comment by alka79** [comment]
Am I the only one with this issue ? something must be wrong in my setup if no one else complains. It is quite painful in everyday use.

As of now, when I click upload and Serial is open ( a common situation in dev/debug) : 
- Serial is closed
- Serial is immediately reopened (which in 0.34 leads to a reset of the board)
- compile
- if compile success, upload fails because Serial is busy :(
- Serial remains closed. When I reopen it with the button in 0.34, the board is reset once again :(


.
Expected behavior when user clicks Upload : 
- compile
- if compile fails -> exit without touching the Serial port.
- after compile success, if Serial port is open, temporarily close it _(with Arduino IDE, this is when the Serial window remains open but is greyed out)_
- upload
- after upload (successful or failed), if Serial was temporarily closed, reopen it.
- if upload was successful, reset the board only once

**Comment by nbaztec** [comment]
I would appreciate the feature as well

**Comment by gcampbell-msft** [comment]
@alka79 We have recently updated the Arduino extension to depend on a new standalone Serial Monitor extension, please upgrade your arduino extension and try out this new feature!

Let us know if it solves your issue or if the issue still persists!
