### ISSUE TITLE
Open Serial Port resets Arduino board : please make it optional

### ISSUE THREAD

**Issue by alka79** [microsoft/vscode-arduino#1154]
since v0.3.4, open the Serial com port resets the board. https://github.com/microsoft/vscode-arduino/issues/1134#issue-734290431

In many situations, you just want to open a com port to read messages WITHOUT reset. 

In my experience, arduino automatically resets when you physically plug to the serial port and after upload, not when a remote Serial communication software opens a com port.

Is it possible to make this change optional ? ie let user decide if opening the com port resets or not the board.

The reset after upload is not concerned by this and should always remain.

Thanks for considering,

**Comment by gcampbell-msft** [comment]
@alka79 We have recently updated the Arduino extension to depend on a new standalone Serial Monitor extension, please upgrade your arduino extension and try out this new feature!

Let us know if it solves your issue or if the issue still persists!
