### ISSUE TITLE
Serial monitor cursor moves to new line when carriage return is recieved

### ISSUE THREAD

**Issue by cabobalot** [microsoft/vscode-arduino#1161]
Hello,
Today I spent a good deal of time searching through my code for a `Serial.println()` call when there was none. I would like to use carriage return characters `'\r'` to overwrite lines in the serial monitor but the built in serial monitor inserts a newline whenever it encounters the carriage return, so it prints a new line below instead of overwriting the previous line. Using PuTTY with the same code results in the overwriting behavior I am looking for.

Either I missed a setting somewhere or the serial monitor adds some unwanted fluff to the stream. 
Is this problem fixable? I was really beginning to like this extension but this is a deal breaker for me as switching to a PuTTY window all the time can get tedious. 

I am using Windows 10

EDIT:
Side note, the Arduino desktop app serial monitor behaves even worse and ignores the carriage return altogether.

**Comment by gcampbell-msft** [comment]
@cabobalot We have recently updated the Arduino extension to depend on a new standalone Serial Monitor extension, please upgrade your arduino extension and try out this new feature!

Let us know if it solves your issue or if the issue still persists!
