### ISSUE TITLE
Cannot open source file "vireg/port/megaAVR-0/PORT_t.h" (dependency of "Arduino.h")

### ISSUE THREAD

**Issue by Gostas** [microsoft/vscode-arduino#1162]
I am writing code for the Arduino Uno WiFi rev. 2 which is a MegaAvr board. I get this error for every .cpp or .ino file I have and it always says the error is in the first include statement from the top. So first it says that PORT_t.h is a dependency of SPI.h and if I delete the #include <SPI.h>,  it will move on to the next include which is  #include <WiFiNINA.h> and say that it is a dependency of WiFiNINA.h.
Now when I go to each and every one of the files which intellisense says are dependent on PORT_t.h, I get "#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit".
**The code compiles and runs just fine though.**

**Comment by adiazulay** [comment]
This should be fixed in #1141
