### ISSUE TITLE
Cannot select board type

### ISSUE THREAD

**Issue by raghavdoescode** [microsoft/vscode-arduino#1163]
![image](https://user-images.githubusercontent.com/33642056/102729657-3ba5a980-42f7-11eb-9ad2-b4ff797a20bb.png)
 Nothing is showing when i try to select the board type but i am able to select the serial port. I am able to use Arduino IDE to upload sketches though.

OS: Arch Linux

**Comment by Starkiller4011** [comment]
Same issue as nerdthatnoonelikes though when I tried to set the Board Type through the command pallet I got "No supported board is available.\n\nSource: Arduino (Extension)". OS: Manjaro

**Comment by nerdthatnoonelikes** [comment]
So i tested the extension on my machine with Xubuntu 20.04 and the extension worked fine. Is there a reason It worked on Xubuntu and not Arch Linux?

**Comment by nerdthatnoonelikes** [comment]
So today I reinstalled Arch Linux and installed the Arduino extension for vscode and I can select the board. But I cannot click on the <Select Serial Port> Button. Its completely unresponsive.

**Comment by ben-kuhn** [comment]
Same problem on Ubuntu 20.10

**Comment by Aumandaris** [comment]
Same problem on Manjaro KDE Plasma 21.0.2

**Comment by JorgeMarinC** [comment]
Same problem here on Ubuntu 20.04

**Comment by JuanDavidBallesteros** [comment]
I solved this problem, you need to download the Arduino official version (later version of 1.6). The version has a install.sh file, you can install those files  running in console from the folder the command `sh file_name.sh`

Then, the paths must look something like this, so update the paths:

`"arduino.path": "/home/redes/Descargas/arduino-1.8.15",
  "arduino.commandPath": "arduino"`

Finally, you must to restart vs code

**Comment by orlade** [comment]
I also get this behaviour when trying to use `arduino-cli`. It works when not using the CLI.

**Comment by yuxiaoyuan0406** [comment]
> I solved this problem (Linux), you need to download the Arduino official version (later version of 1.6). The version has a install.sh file, you can install those files running in console from the folder the command `sh file_name.sh`
> 
> Then, the paths must look something like this, so update the paths:
> 
> `"arduino.path": "/home/redes/Descargas/arduino-1.8.15", "arduino.commandPath": "arduino"`
> 
> Finally, you must to restart vs code

Run `whereis arduino` gives `/usr/local/bin/arduino`.   
So I set my settings like this:

```
    "arduino.path": "/usr/local/bin",
    "arduino.commandPath": "arduino"
```

Still not working.

**Comment by andrewsno1** [comment]
I had the same issue: I could not select the board even though I had set `path` and `commandPath`.

As soon as I created a .vscode folder in the workspace of my project and created a file called `arduino.json` it sudenly worked. I could select the boards and the selected board would also appear in the `arduino.json` file.

I hope this helps.

**Comment by DayLightDancer** [comment]
I had the same issue but I am on windows and I solve it in that way:
VSCode uses the arduino app the get the board info so:
1. Open the Arduino app and setup the board
2. Close the Arduino app - it saves changes on close
3. Open VSCode set the propper path in the fields
4. Click outside of the edited field( sometimes VSCde lost field data if the tab is closed while the edited field is in focus )
5. Restart the VSCode

**Comment by plejsq** [comment]
F1 and after that Arduino:initialize have solved problem. Thank you @rrakso

**Comment by Shaladdin** [comment]
**I found a Solution** (in windows 10, [but maybe work for you too?])
I download the Arduino(official) version 1.8.13
and change the Arduino extension in vsCode to version v0.3.4

and it works!
now I can select board!

**Comment by YvanLin** [comment]
> Downgrading to v0.4.5 fixed this for me (on MacOS 10.15.7 Intel)

It does help! I guess there are some bugs in v0.4.6.

**Comment by magouero** [comment]
same here.
reverted arduino extension from 0.4.6 to 0.4.5 and Arduino board configuration comes back to life.
___________________
vscode about:
Version : 1.61.0 (system setup)
Commit : ee8c7def80afc00dd6e593ef12f37756d8f504ea
Date : 2021-10-07T18:13:09.652Z
Electron : 13.5.1
Chrome : 91.0.4472.164
Node.js : 14.16.0
V8 : 9.1.269.39-electron.0
OS : Windows_NT x64 10.0.19043

**Comment by gustafwigren** [comment]
Thanx, Reverting extension from 0.4.6 to 0.4.5 also fixed this for me on windows10

**Comment by AlexIII** [comment]
Can confirm reverting from 0.4.6 to 0.4.5 fixes the problem (win10)

**Comment by han-fastolfe** [comment]
How do you get v0.4.5? I can only see v0.4.6 to install

**Comment by MysteryMS** [comment]
> How do you get v0.4.5? I can only see v0.4.6 to install

You should be able to select a specific version by clicking on "Install Another Version" from the Uninstall dropdown.
![image](https://user-images.githubusercontent.com/38635037/139598516-e49efbf3-363b-43d8-8bdf-7a8d305dab54.png)

**Comment by Edwardhk** [comment]
Reverting to version 0.4.5 solved the problem too. (Ubuntu 20.04)

**Comment by benmcmorran** [comment]
Fixed in v0.4.7.

**Comment by GShashikanth** [comment]
I spent hours on setting Vs code for arduino, but no bingo, can anyone post step by step working process.

**Comment by RanzQ** [comment]
If you installed arduino using snap:
```sh
$ which arduino
/snap/bin/arduino
```
I figured out that the paths are a bit weird. But these seem to work:
```json
"arduino.path": "/snap/arduino/current",
"arduino.commandPath": "../../bin/arduino"
```
Without that relative command path, the snap's `/snap/arduino/current/bin/java` isn't found.

**Comment by YvanLin** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by laestrada** [comment]
Was able to get this working on MacOS Monterey 12.1 with `arduino-cli` and vscode extension 0.4.8. Some initialization was needed using the arduino cli:
1. `$ arduino-cli config init` ( this step may not be necessary )
2. `$ arduino-cli board list` to get the core version
3. `$ arduino-cli core install <insert-core-version-here>`
4. Restart vscode

**Comment by zakkhoyt** [comment]
`arduino-cli board list` failed for me on macOS 12.1, but I was able to get running with `arduino-cli core install adruino:avr`

**Comment by YvanLin** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by notblank00** [comment]
reverting did not fix anything on ubuntu 21.10

**Comment by YvanLin** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Mek101** [comment]
Re open, this issue is still present

**Comment by YvanLin** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by crashbit666** [comment]
Yes, this  issue is still present. I've install arduino-ide form snap. I've configure arduino paths and it working well. But when I try to select arduino board, empty list is showed. I'm using latest version of plugin and latest version of ide on ubuntu 22.04

**Comment by a1usha** [comment]
@laestrada Thanks, was missing arduino:avr core. After `arduino-cli core install <insert-core-version-here>` everything initialised properly. Plugin version 0.4.12

**Comment by YvanLin** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
