### ISSUE TITLE
Cannot find the sketch file

### ISSUE THREAD

**Issue by OpenSourceDevelop** [microsoft/vscode-arduino#1166]
"Cannot find the sketch file" error when verifying/uploading code #427

hello, i have the same problem with Windows also Debian... would like getting it to work..

**Comment by adiazulay** [comment]
Is the sketch in a folder with the same name?

**Comment by OpenSourceDevelop** [comment]
I tried it anyway, but I'm not sure whether the file or the path are correct. can you specify the path and the content of the file?

**Comment by AtCra** [comment]
> I tried it anyway, but I'm not sure whether the file or the path are correct. can you specify the path and the content of the file?

I meet the same problem , and it had been solved.
I found the possible reason is you open multiply directions and the ".vscode/arduino.json" **not exist in your project root direction**
This is my test project directory structure:
![image](https://user-images.githubusercontent.com/40266932/104541182-ffe2d300-565b-11eb-839d-c96993e24771.png)

**Comment by OpenSourceDevelop** [comment]
Path: /home/XXX/Downloads/arduino-1.8.13/


/home/XXX/.vscode/arduino.json

{
"sketch":"GetStarted.ino",
"port":"COM6",
"board":"GetStarted:LALA",
"configuration":"upload_method=OpenOCDMethod"
}


/home/XXX/.vscode/GetStarted.ino

void setup() {
  // put your setup code here, to run once:
}

void loop() {
  // put your main code here, to run repeatedly:
}


**any Idea?**

**Comment by AtCra** [comment]
> Path: /home/XXX/Downloads/arduino-1.8.13/
> 
> /home/XXX/.vscode/arduino.json
> 
> {
> "sketch":"GetStarted.ino",
> "port":"COM6",
> "board":"GetStarted:LALA",
> "configuration":"upload_method=OpenOCDMethod"
> }
> 
> /home/XXX/.vscode/GetStarted.ino
> 
> void setup() {
> // put your setup code here, to run once:
> }
> 
> void loop() {
> // put your main code here, to run repeatedly:
> }
> 
> **any Idea?** error "cannot find sketch file"

move
/home/XXX/.vscode/GetStarted.ino
to
/home/XXX/GetStarted.ino?
My ino file not in the  .vscode dir

**Comment by OpenSourceDevelop** [comment]
Thank you. But the same Problem "cannot find sketch file"

also in /home/XXX/.vscode/GetStarted.ino
also in /home/XXX/.vscode/GetStarted/GetStarted.ino
also in /home/XXX/Downloads/arduino-1.8.13/GetStarted/GetStarted.ino
also in /home/XXX/Downloads/arduino-1.8.13/GetStarted.ino

:(

is the installation path right? is the same like the Arduino IDE which is working.

**Comment by adiazulay** [comment]
do you have Arduino installed in the Downloads folder? If it's not installed in the default location you'll have to point the extension to where Arduino is installed
![image](https://user-images.githubusercontent.com/14335253/105746645-91700180-5ef4-11eb-8bf9-bdc46a379e61.png)

then to open the folder containing the sketch go to **File>Open Folder** and select the Get Started directory
