### ISSUE TITLE
Need load board pinout through force include to avoid intellisense "not included" errors

### ISSUE THREAD

**Issue by edolis** [microsoft/vscode-arduino#1178]
Hi guys,
finally understood how get around the issue of Intellisense apparently not reading the pins_arduino.h pinout header file (intellisense errors like LED_PINOUT undefined and the like - I had to include specifically the pinout header file in the forced includes.
You may look into this - I expeceted that, once you select the board, its pinout (in the specific case 
` "C:\\Users\\Eddo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\2.7.4\\variants\\d1\\pins_Arduino.h"` ) was read and applied - but maybe I got this wrong, please clarify.

It looks like even including the specific path in the includes does not work
' "C:\\Users\\Eddo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\2.7.4\\variants\\d1\\**"
![image](https://user-images.githubusercontent.com/2226075/104095504-77e57d80-5297-11eb-94d7-27b6639cbafd.png)

while
![image](https://user-images.githubusercontent.com/2226075/104095535-a6635880-5297-11eb-97e3-74d3e05679ac.png)

**Comment by adiazulay** [comment]
This issue is being tracked with #438 and is fixed in #1183. There will be a release candidate with the fixes in the next week or so.
