### ISSUE TITLE
Cannot Select Serial Port

### ISSUE THREAD

**Issue by Alvin-Chips** [microsoft/vscode-arduino#1202]
Issue Type: <b>Bug</b>

Install the arduino library, then select your serial port, and nothing should happen. 

Extension version: 0.3.4
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19041

**Comment by boskoe** [comment]
You need 0.3.5

**Comment by Alvin-Chips** [comment]
> You need 0.3.5

And how do I install this version?

**Comment by boskoe** [comment]
Open the extensions module "Ctrl+Shft+X". Click the three horizontal dots at the top "..." and click "Check for Extension Updates"

**Comment by Alvin-Chips** [comment]
It says "All extensions are up to date."

**Comment by boskoe** [comment]
Try this then.

https://github.com/microsoft/vscode-arduino/issues/1198#issuecomment-774746151

**Comment by Alvin-Chips** [comment]
Ok I have read through a lot of it, and I'm wondering how to manually add a serial port by code.

**Comment by boskoe** [comment]
[Let me Google that for you...](https://letmegooglethat.com/?q=vscode+arduino+manually+add+com+port)

**Comment by Alvin-Chips** [comment]
Ok Thank you!

**Comment by AronRubin** [comment]
I have success now with vscode-arduino 0.3.5 . I did have to download that from the releases and "Install from VSIX"

**Comment by adiazulay** [comment]
please see #1198
