### ISSUE TITLE
Broken on Apple Silicon version of VSCode

### ISSUE THREAD

**Issue by VladislavSmolyanoy** [microsoft/vscode-arduino#1209]
Failed to open serial port /dev/tty.usbserial-10 due to error: + Error: dlopen(/Users/VladislavS/.vscode/extensions/vsciot-vscode.vscode-arduino-0.3.5/out/node_modules/usb-detection/build/Release/detection.node, 
1): no suitable image found. Did find: /Users/VladislavS/.vscode/extensions/vsciot-vscode.vscode-arduino-0.3.5/out/node_modules/usb-detection/build/Release/detection.node: mach-o, but wrong architecture

Just updated to the Apple Silcion optimised version of VSCode, and it broke the extension. Rosetta version works fine.

**Comment by egandro** [comment]
Related to this https://github.com/microsoft/vscode-arduino/issues/1207

**Comment by gcampbell-msft** [comment]
@VladislavSmolyanoy We have recently updated the Arduino extension to depend on a new standalone Serial Monitor extension, please upgrade your arduino extension and try out this new feature!

Let us know if it solves your issue or if the issue still persists!
