### ISSUE TITLE
Can't find debugging configuration

### ISSUE THREAD

**Issue by ajs256** [microsoft/vscode-arduino#1213]
I don't see the debugging configuration from the Arduino extension when I click the "Run & Debug" button in the debug menu. I only see "C++ (GDB/LLDB)" and "C++ (Windows)".

VS Code Version: 1.54.3
Arduino Extension Version: 0.4.0
C/C++ Extension Version: 1.2.2

**Comment by ajs256** [comment]
Do I have to add something to `launch.json` or `arduino.json` to get it to show up?

**Comment by ajschwieterman** [comment]
@ajs256 Were you able to solve this problem?  What steps did you take?

**Comment by ajs256** [comment]
I used the cortex-debug extension
