### ISSUE TITLE
Add context menus in editor for frequently-used commands

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode-arduino#123]
Add context menus for frequently-used `Veirfy` and `Upload` will be very useful for those ‘lazy’ developers.
The feedback of context menus in [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner) and [Terminal](https://marketplace.visualstudio.com/items?itemName=formulahendry.terminal) extensions are very good.
Right-click to Veirfy and Upload will be straightforward.
![image](https://cloud.githubusercontent.com/assets/1050213/23883978/0320aaf0-08a5-11e7-9a84-9b6f8b79bcab.png)

**Comment by liydu** [comment]
Recommend to use Command palette as that is the standard VS Code way.
