### ISSUE TITLE
Raspberry Pi | cannot select port

### ISSUE THREAD

**Issue by CAProjects** [microsoft/vscode-arduino#1243]
I can get the extenssion working on a windows PC, however on a Raspberry Pi 32bit I am unable to select a port. This makes it impossible to upload code to the Arduino board.

I am able to select the board with out issue, its just the port i cannot.

I have looked at logs and cannot find anything there at all

**Comment by davidcooper1** [comment]
@CAProjects have you checked to see if your Raspberry Pi is able to detect any devices? I've seen a few sites list `dmesg | grep tty` as a way to see any messages relating to serial activity. Working fine on my Raspberry Pi 64bit Lite OS. I think the packages should come pre-installed. If not, the arduino package through `apt-get` should have them.

**Comment by davidcooper1** [comment]
Could be related to #1207 and #1181

**Comment by gcampbell-msft** [comment]
@CAProjects We have recently updated the Arduino extension to depend on a new standalone Serial Monitor extension, please upgrade your arduino extension and try out this new feature!

Let us know if it solves your issue or if the issue still persists!
