### ISSUE TITLE
Shouldn't need to set commandPath if useArduinoCli is true

### ISSUE THREAD

**Issue by calebho** [microsoft/vscode-arduino#1245]
Seems like #1227 fixes some of the path issues on Mac, but [the getter `commandPath` still joins the Arduino app path](https://github.com/microsoft/vscode-arduino/blob/v0.4.2/src/arduino/arduinoSettings.ts#L136) [which defaults to `"/Contents/MacOS/Arduino"` if it is empty](https://github.com/microsoft/vscode-arduino/blob/v0.4.2/src/arduino/arduinoSettings.ts#L95-L97). This causes IntelliSense to fail which I commented on #1235.
```
[Starting] Analyzing sketch '03-love-o-meter/03-love-o-meter.ino'
[Warning] Output path is not specified. Unable to reuse previously compiled files. Build will be slower. See README.
[Warning] Failed to generate IntelliSense configuration.
[Error] Analyzing sketch '03-love-o-meter/03-love-o-meter.ino': {"error":{"errno":"ENOENT","code":"ENOENT","syscall":"spawn /usr/local/bin/Contents/MacOS/Arduino","path":"/usr/local/bin/Contents/MacOS/Arduino","spawnargs":["compile","-b","arduino:avr:uno","--verbose","/Users/calebho/work/arduino/starter-kit/03-love-o-meter/03-love-o-meter.ino"]}}
```
The issue is `"syscall":"spawn /usr/local/bin/Contents/MacOS/Arduino"` which causes `ENOENT`.

Was able to workaround by setting `commandPath = arduino-cli` for now.

Extension version:
```
Name: Arduino
Id: vsciot-vscode.vscode-arduino
Description: Arduino for Visual Studio Code
Version: 0.4.2
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-arduino
```

Working relevant configuration:
```
    "arduino.path": "/usr/local/bin",
    "arduino.useArduinoCli": true,
    "arduino.commandPath": "arduino-cli
```

**Comment by benmcmorran** [comment]
Thanks for the feedback. The recent `v0.5.0` release of the extension includes a bundled copy of Arduino CLI that should make it much easier to use the Arduino CLI without setting `arduino.commandPath`.
