### ISSUE TITLE
[BUG] The extension passes `--prefs` to the build command even when explicitly using the CLI.

### ISSUE THREAD

**Issue by Falven** [microsoft/vscode-arduino#1268]
[The Arduino CLI equivalent to `--pref` is `--build-property`](https://arduino.github.io/arduino-cli/latest/commands/arduino-cli_compile/#options).
The extension should not be trying to use `--pref` when using the CLI as it is an invalid command.
I have created a PR to address this issue.

**Comment by benmcmorran** [comment]
This issue should be fixed by PR #1269, which has merged and will be included in the next release of the extension.
