### ISSUE TITLE
Can't find Arduino IDE

### ISSUE THREAD

**Issue by stonez56** [microsoft/vscode-arduino#1281]
OS: Windows 10 Pro, v20H2
Vscode version: 1.5.62
Arduino extension: 0.43
arduino-snippets: 1.0.2
C/C++ 1.4.0

It seems I couldn't get this to work. VScode showed the Error message!
For Arduino: Path: I have tried the following and non-of them worked:

- C:\Program Files (x86)\Arduino
- 'C:\Program Files (x86)\Arduino'
- C:\\\Program Files (x86)\\]Arduino
- C:/Program Files (x86)/Arduino
- "C:\Program Files (x86)\Arduino"  

Error message:
![image](https://user-images.githubusercontent.com/5953052/120954538-fcbebf80-c781-11eb-8349-7c5f68258306.png)

Arduino path settings:
![image](https://user-images.githubusercontent.com/5953052/120954566-08aa8180-c782-11eb-9828-8a65178a25c0.png)

Settings.json:
![image](https://user-images.githubusercontent.com/5953052/120954592-15c77080-c782-11eb-82e9-921cb4d433ca.png)

Arduino IDE Installed location:
![image](https://user-images.githubusercontent.com/5953052/120954673-44dde200-c782-11eb-9c39-6b842047887e.png)

**Comment by stonez56** [comment]
Never mind... I found what happened.... I need to change both "User & Workspace" for Vscode to find Arduino IDE.

In User:
![image](https://user-images.githubusercontent.com/5953052/120967113-b2493d00-c799-11eb-95c5-7d9dde714faf.png)

In Workspace:
![image](https://user-images.githubusercontent.com/5953052/120967192-c7be6700-c799-11eb-9b97-a1d75135a907.png)

[Suggestion] Recommend to put a browse button to location the Arduino installed location...or even better to search Arduino installed location!

Thanks

**Comment by benmcmorran** [comment]
I'm glad you got this working! Regarding your suggestion, [the extension should already be searching for a system-wide Arduino IDE installation](https://github.com/microsoft/vscode-arduino/blob/cdf1d94a5ccdb8362bb5e5f7caf4cf35a0f358cb/src/common/sys/win32.ts#L9-L29), but it looks like that logic didn't work for you. Can you tell me what you get when you run these commands from an *administrator* command prompt?

1. `reg query HKLM\SOFTWARE\WOW6432Node\Arduino`
2. `where arduino`
