### ISSUE TITLE
Arduino upload with compile error switch to serial port view when its open

### ISSUE THREAD

**Issue by iqapps** [microsoft/vscode-arduino#1284]
Conditions:
  The serial port open
  The code cannot compile. (ex. missing terminating semicolon)
  Output view is on Serial port
  You press "upload"

The output view changes to Arduino during compile
After the compile finishes the output view changes to serial port anyway.

The expected behavior is to stay in Arduino view and show the errors.

**Comment by gcampbell-msft** [comment]
@iqapps We have recently updated the Arduino extension to depend on a new standalone Serial Monitor extension, please upgrade your arduino extension and try out this new feature!

Let us know if it solves your issue or if the issue still persists!

**Comment by iqapps** [comment]
Thanks, I'll try it out at next convenience.
