### ISSUE TITLE
Serial port diconnect + connect does not reset Arduino Nano

### ISSUE THREAD

**Issue by iqapps** [microsoft/vscode-arduino#1285]
When doing 'disconnect' then 'connect' on the Serial port, the attached Arduino Nano (FTDI) does not reset.

This was reported also on version 0.31.

When doing the same with the serial port from a C# program it is possible to reset the same Arduino by controlling the DTR line.

Seems like the VS-Code serial port controls does not control DTR line correctly.

Maybe it should be an option to be able to select if DTR and/or RTS should be controlled when disconnecting/connecting the Serial port.

Preferrebly a setting to enable DTR/RTS control should be the Arduino type dependent settting with possible user setting override.

VS Code version: Code 1.56.2 (054a929, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

**Comment by iqapps** [comment]
Anyone else see this.

I also get this error on Arduino Mega.

**Comment by gcampbell-msft** [comment]
@iqapps We have recently updated the Arduino extension to depend on a new standalone Serial Monitor extension, please upgrade your arduino extension and try out this new feature!

Let us know if it solves your issue or if the issue still persists!
