### ISSUE TITLE
Serial Monitor auto reconnects after build failure.

### ISSUE THREAD

**Issue by Llaves** [microsoft/vscode-arduino#1289]
If the serial monitor was active when the build/upload command is invoked, the monitor is restored when the operation is complete, even if it failed. This occurs at arduino.ts line 722 (I think). The problem is that this immediately hides the build output window and the user may not notice that the build failed, no upload occurred, and they are still running the result of the previous successful upload and left wondering why the new code had no effect. 

This conflicts to some degree with issues [1060 ](https://github.com/microsoft/vscode-arduino/issues/1060 )and [1061](https://github.com/microsoft/vscode-arduino/issues/1061).  1060 points out that if you don't restore the monitor in this case, then the next successful compile will not open the monitor as the recorded state at the start of the compile. This would require some sort of persistent state var rather than just testing to see if the monitor is open at the invocation of the compile.  1061 seems to want the serial monitor to remain open and connected to the device in the event of a failed compile, though I don't understand what the use case for that would be.

**Comment by StefanKellerAC** [comment]
Yes, that would be fine!
An acoustic signal would be fine for me:
https://github.com/microsoft/vscode-arduino/issues/1518#issuecomment-1316629270

**Comment by gcampbell-msft** [comment]
@Llaves We have recently updated the Arduino extension to depend on a new standalone Serial Monitor extension, please upgrade your arduino extension and try out this new feature!

Let us know if it solves your issue or if the issue still persists!
