### ISSUE TITLE
Missing Board type

### ISSUE THREAD

**Issue by telefonosuci** [microsoft/vscode-arduino#1294]
Vscode arduino version: 0.4.3

Do not see Arduino MKR1000 on board type selection list

**Comment by zhong-wx** [comment]
I solve this problem by using version 0.3.4. Maybe this is a bug.

**Comment by benmcmorran** [comment]
Potentially related to #414

**Comment by benmcmorran** [comment]
#1425 fixes this issue and will be included in the next release of the extension.
