### ISSUE TITLE
Starting larger project issues warning "Invalid Board config..." at VS-Code startup

### ISSUE THREAD

**Issue by iqapps** [microsoft/vscode-arduino#1296]
I get a warning "Invalid board configuration detected in configuration file: Invalid configuration key. Falling back to defaults." when starting a larger Arduino project using the "Arduino Mega 2560". This is an old project, previously never gave me any warnings, and the warning is new and appear every time I start VS-Code on this project.

As the warning is quite fluffy in the message of what is really wrong, I cannot fix it. After the project has started, i can verify and upload without any problems and the configuration seems ok as far as I can see. But then again, the warning said it has fixed something.

The warning should say something more informative, so the user have a chance of fixing it, and falling back to defaults leaves me with no clue at all. What is my best step to get rid of this annoying warning.

Any ideas ?

**Comment by benmcmorran** [comment]
This looks like an instance of #1272, and I think the warning is coming from the `.vscode/arduino.json` file. Can you provide the content of this file to help diagnose the issue? I'll also see how we can improve the warning text.
