### ISSUE TITLE
Unable to select programmer

### ISSUE THREAD

**Issue by Juppi88** [microsoft/vscode-arduino#1298]
I have a freshly installed Visual Studio Code (1.57.1) with the vscode-arduino extension with a freshly installed Arduino IDE (1.8.15) linked to it. I am trying to upload a pretty basic sketch to one of my SparkFun Pro Micro boards.

I am able to select the board I am going to use, as well as the COM port used for programming, However, I am not able to select any Programmer, because for some reason the Visual Studio Code extension isn't able to detect any programmers supported by Arduino:

![image](https://user-images.githubusercontent.com/5600425/124365210-27038000-dc4f-11eb-9672-f731766218bb.png)
![image](https://user-images.githubusercontent.com/5600425/124365249-629e4a00-dc4f-11eb-8da6-3f218c101356.png)

If there are any logs or other information I can provide, please let me know.

**Comment by ChristianDavis** [comment]
I had this same issue, but the docs define that as "external" programmers. If I just use the "upload" command it connects to the board via the CLI

**Comment by afreisinger** [comment]
I had this same issue.

**Comment by afreisinger** [comment]
Solved !
https://randomnerdtutorials.com/solved-arduino-ide-esp32-esp8266-installation/

**Comment by magnets99** [comment]
@afreisinger i'm not sure it's the same issue. OP was not having problems with esp. I have the same issue, on linux, so i'm also unable to follow these solution instructions

**Comment by magnets99** [comment]
I'm also having the same issue as @mumblety along with selecting the board. it gives me the box, but it is unpopoulated and the the dropdown is disabled (becuase it is empty).

I have tried using the arduino-cli but for some reason code says that my path to the cli is wrong (it is not, i can literally paste the path from the json file into bash and it runs).

**Comment by magnets99** [comment]
the issue has been fixed for me now with version 0.4.7
i did have to choose the board first, then the programmer was populated, which i guess makes sense.

**Comment by benmcmorran** [comment]
I'm glad this is working for you now! If anyone else in this thread is still having issues, please let me know.
