### ISSUE TITLE
Add "output":"build" to arduino.json on arduino:initialize

### ISSUE THREAD

**Issue by jerryc05** [microsoft/vscode-arduino#1302]
Add `"output":"build"` to `arduino.json` on `arduino:initialize` command (or others) automatically so that we don't need to set this by hand.

It is a pretty useful configuration but hard to find unless we read through the `readme` or check the extension output for info.

**Comment by blackpancake** [comment]
Agree.

**Comment by Llaves** [comment]
agree, though I would prefer to see it as a subdirectory of the project directory

**Comment by benmcmorran** [comment]
#1425 fixes this issue and will be included in the next release of the extension.
