### ISSUE TITLE
Arduino Extension Serial Monitor Error

### ISSUE THREAD

**Issue by tondar20** [microsoft/vscode-arduino#1309]
After update to ver 1.59.0, serial port does not work:

Failed to open serial port COM3 due to error: + Error: The module '\\?\c:\Users\xxxxx\.vscode\extensions\vsciot-vscode.vscode-arduino-0.4.3\out\node_modules\usb-detection\build\Release\detection.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 87. This version of Node.js requires
NODE_MODULE_VERSION 89. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

**Comment by adiazulay** [comment]
tracking this with #1312
