### ISSUE TITLE
Failed to open serial port COM4 due to error

### ISSUE THREAD

**Issue by bdcliang** [microsoft/vscode-arduino#1314]
Failed to open serial port COM4 due to error: + Error: \\?\c:\Users\Administrator\.vscode\extensions\vsciot-vscode.vscode-arduino-0.4.3\out\node_modules\usb-detection\build\Release\detection.node is not a valid Win32 application.
\\?\c:\Users\Administrator\.vscode\extensions\vsciot-vscode.vscode-arduino-0.4.3\out\node_modules\usb-detection\build\Release\detection.node

**Comment by adiazulay** [comment]
tracking this with issue #1312
