### ISSUE TITLE
Serial port does not send data

### ISSUE THREAD

**Issue by iqapps** [microsoft/vscode-arduino#1339]
With Arduino Extension 0.44 and VS Code 1.60, the opened serial port does not send out data, when pressing SHIFT+ALT+S then typing some characters and pressing ENTER.

Downgrading to Arduino Extension 0.43 and VS Code to 1.58.2, the serial port works as expected.

**Comment by mustaqmasterstudent** [comment]
I have closed my issue #1340. Because it is somewhat similar to this issue #1339. But I tried downgrading as mentioned in this issue, but this did not helped me.

**Comment by masynthetic** [comment]
having the same issue here, rolling back does not work as old versions do not even allow me to select a serial port. Certain the issue is not related to EOL sequence. 

the fun never ends with this extension...

**Comment by iqapps** [comment]
I have not seen this for some time after upgrading to 0.4.6.
