### ISSUE TITLE
Serial Port dose not send data.

### ISSUE THREAD

**Issue by mustaqmasterstudent** [microsoft/vscode-arduino#1340]
I want to read the string input from the user in serial port.

When I use "Arduino: Sent Text to Serial Port". I was not able to send the text to serial port even after hitting the enter.

Is there any way for this. Any alternatives?

**Comment by hlovdal** [comment]
This seems to be a duplicate of #1339, can you verify and check if downgrading like mentioned in that issue makes any difference?

**Comment by mustaqmasterstudent** [comment]
Yes, I already tried that. 

I tried after downgrading, but it was not even compiling for me. So, I upgraded again. 

Which is also similar issue of #1339 and #1347.

**Comment by hlovdal** [comment]
So this issue can be closed as a duplicate then, and all effort be put into #1339 I assume?

**Comment by mustaqmasterstudent** [comment]
Okay! I close my issue, as this is just duplicate of #1339 issue.
