### ISSUE TITLE
Serial port console show only complete line

### ISSUE THREAD

**Issue by vlastahajek** [microsoft/vscode-arduino#1348]
Since the v0.4.4 (on Windows 10) serial port console seems to wait for LF to print new data.

When printing, for example, WiFi connection progress by char by char via `Serial.print()`, there is nothing shown until `Serial.println()`.
Also, when using ESP8266 with serial speed 74880  on SDK  3.0.2, when it reboots, it sends boot info with speed 115200, and at this time Serial console stops.

**Comment by vlastahajek** [comment]
Both problems still exist on 0.4.5

**Comment by apws** [comment]
thanks, its still issue, I used only print(".") initially and as nothing was happening, was hard to track for a while whats wrong where ... please, fix this :-)

**Comment by binarynoise** [comment]
Same issue here. Using `Serial.print(".");` to visualize progress and wondered why there's nothing on the serial monitor. And I don't think, it would be a good idea to just `println()` everything

**Comment by benmcmorran** [comment]
This should be fixed by #1450, which will be included in the next release of the extension.

**Comment by apws** [comment]
luckily, this feature led me to termite monitor/terminal where I am more than happy for my purpose ))

**Comment by benmcmorran** [comment]
This issue has been fixed in the latest release of this extension, which is available in the VS Code extension marketplace.

**Comment by vlastahajek** [comment]
I can confirm that. Thanks!
