### ISSUE TITLE
Serial Port Monitor Custom Baud Rate

### ISSUE THREAD

**Issue by rev1204** [microsoft/vscode-arduino#1350]
Please add option to set a custom baud rate. Current version does not provide custom baud rate, and I use 921600 baud rate which is not available.

**Comment by gcampbell-msft** [comment]
@rev1204 We have recently updated the Arduino extension to depend on a new standalone Serial Monitor extension, please upgrade your arduino extension and try out this new feature!

Let us know if it solves your issue or if the issue still persists!
