### ISSUE TITLE
Serial port receives data but does not send data

### ISSUE THREAD

**Issue by RiKuRail** [microsoft/vscode-arduino#1355]
With Arduino Extension **0.4.5** and VS Code **1.60.2**, the opened serial port does not send out data, when pressing SHIFT+ALT+S then typing some characters and pressing ENTER.

Receiving data works properly!

**Comment by benmcmorran** [comment]
Are you still seeing this issue on the latest version 0.4.8 of the extension? I can no longer reproduce this issue and #1356 should have fixed it.
