### ISSUE TITLE
[Board/Library manager] User should be able to see the count of each filter

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode-arduino#136]
Just like the VS Marketplace:
![image](https://cloud.githubusercontent.com/assets/1050213/23885355/678919fc-08ad-11e7-97a7-7dc1577a8c2d.png)

**Comment by czgtest** [comment]
new request : show the count of each filter

![image](https://user-images.githubusercontent.com/35018765/37076959-acd359a2-2213-11e8-94c2-057c64da4dca.png)
