### ISSUE TITLE
v0.4.6 board selection does not show any board

### ISSUE THREAD

**Issue by protttoy** [microsoft/vscode-arduino#1360]
tried both on vscode 1.58 and 1.60.2

reverting back to v0.4.3 works, bur serial selection is not working with vscode 1.60.2

vscode 1.60.2 with arduino-vscode v0.4.5 works fine

System : windows 10 build 19043

**Comment by hdpklm** [comment]
I have same problem

**Comment by mcedrdiego** [comment]
Same here, Select board list is empty.

**Comment by philipjoep** [comment]
I have the same issue: v0.4.6
and
![image](https://user-images.githubusercontent.com/73434428/136885685-b49611c7-98f8-4dcc-9418-25d3dc3c3aec.png)

**Comment by yaniot** [comment]
> 我有同样的问题：v0.4.6 和 ![图片](https://user-images.githubusercontent.com/73434428/136885685-b49611c7-98f8-4dcc-9418-25d3dc3c3aec.png)

I suggest you to roll back the arduino plugin to 0.4.5 vscode I choose 1.58

**Comment by benmcmorran** [comment]
This should be fixed in versions 0.4.7 and later by #1367
