### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by digitalbitlabs** [microsoft/vscode-arduino#1365]
- Issue Type: `Bug`
- Extension Name: `vscode-arduino`
- Extension Version: `0.4.6`
- OS Version: `Windows_NT x64 10.0.17134`
- VS Code version: `1.57.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by digitalbitlabs** [comment]
I think this post got generated automatically through vscode

**Comment by benmcmorran** [comment]
Closing this issue because there is no description or repro steps. @digitalbitlabs If you are still experiencing this issue, please reply with a description of the issue and steps to reproduce it.
