### ISSUE TITLE
After clicking "verify", the info "verifying" keeps showing w/o more hints

### ISSUE THREAD

**Issue by mybayern1974** [microsoft/vscode-arduino#137]
I was using the provided app.ino. As a beginner,I'm puzzled and don't know whether things are correct or failed when seeing the "Verifying" info keep showing w/o any more hints. Attached the screenshot.
![keep_verifying](https://cloud.githubusercontent.com/assets/16640242/23885274/f6e58ae6-08ac-11e7-9464-8b6f43dd0686.png)

**Comment by liydu** [comment]
We may wait to see what **arduino-cli** can provide improvements on this.

**Comment by czgtest** [comment]
@mybayern1974  have you got this issue solved?
