### ISSUE TITLE
AcronisCyberProtect: Malware.GenericML detected vsciot-vscode.vscode-arduino@0.4.6\out\serial-monitor-cli\win32\Main.exe 

### ISSUE THREAD

**Issue by c0ns0le** [microsoft/vscode-arduino#1370]
File Name: main.exe
Threat Name: Malware.GenericML
MDS      7ab158d4a11d186c005bf70640568949
SHAI      e24eb58e9e883eb52f66f4ad9cff7b80ffbf434e
SHA256 32bee79336a497b165366478bd7c8e1a4c6c77b458281e179ff5bd492fa3530f

![image](https://user-images.githubusercontent.com/677584/137585102-3e944f9d-6644-4e7b-a8ed-469a9d14bc78.png)

**Comment by benmcmorran** [comment]
The latest release v0.4.9 of this extension now signs the serial monitor executable on Windows with a Microsoft certificate. I'm no longer seeing any [detections from virus scanners](https://www.virustotal.com/gui/file/dc565fd07daf9db9e8bbcc0b2b2474ca128c5594a10bc9835c3c90b18a4c094f), including from Acronis.
