### ISSUE TITLE
Board manager isn't called properly in 0.4.6.

### ISSUE THREAD

**Issue by jtupulis** [microsoft/vscode-arduino#1372]
Hi,

Board list show no items when called. 0.4.5. works properly.

My config is the following:

Hardware

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro17,1
  Chip:	Apple M1
  Total Number of Cores:	8 (4 performance and 4 efficiency)
  Memory:	8 GB

OS MacOS BigSur 11.6 (20G165)

Arduino IDE 1.8.16

VS Code

1.61.1 (Universal)
Commit: c13f1abb110fc756f9b3a6f16670df9cd9d4cf63
Date: 2021-10-14T01:23:30.274Z (5 days ago)
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.6.0

with plugins:
GitHub Pull Requests and Issues v0.31.0
C/C++ v1.7.0
Arduino as per above

Veiksmi,
Jānis

**Comment by benmcmorran** [comment]
Fixed in v0.4.7.
