### ISSUE TITLE
Serial object is flagged as undefined

### ISSUE THREAD

**Issue by capnajax** [microsoft/vscode-arduino#1384]
Issue Type: <b>Bug</b>

1. Create a sketch
2. Use the Serial object (e.g. Serial.begin(9600);)
3. Note the Serial object has an error squiggly 'identifier "Serial" is undefined'
4. Note sketch compiles just fine because Serial is provided implicitely.

Extension version: 0.4.7
VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:24:41.297Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|32.00GB (0.89GB free)|
|Process Argv|--crash-reporter-id a3f2931a-6c32-478e-a029-f62099533b1d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by AlexIII** [comment]
Works fine for me. 
Did you select the board type? You have to select it and then wait a bit while intellisense does its magic.

![image](https://user-images.githubusercontent.com/10047074/140646018-36cbc642-c0df-48bf-9f37-3b294e79b754.png)
