### ISSUE TITLE
[Board Manager] useless duplicated 'Online help' and 'More info'

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode-arduino#139]
The link of 'Online help' and 'More info' are the same in each board, it is useless. 
The first time I use it, I try to visit two 'Online Help' but get the same page.
In this case, Arduino IDE is not a good reference. Just putting the links in header area or other place is enough.

![image](https://cloud.githubusercontent.com/assets/1050213/23886367/5471578c-08b5-11e7-9432-eccc53598586.png)

**Comment by liydu** [comment]
We will conform with what Arduino IDE UX to avoid confusions.
