### ISSUE TITLE
Extension Missing from Marketplace

### ISSUE THREAD

**Issue by quinn-n** [microsoft/vscode-arduino#1395]
- OS: `Arch Linux`
  - VSCode version: `1.62.0-1`
 
Searching `arduino` in the extensions tab doesn't bring up this extension.

I've tried re-installing vscode and deleting its data directories (`~/.vscode-oss` and `~/.config/Code - OSS/`), this didn't help.

**Comment by benmcmorran** [comment]
The extension appears in the Marketplace for me on VS Code 1.63.2. Are you still seeing this issue?

![image](https://user-images.githubusercontent.com/6981284/148290987-a4bcd20d-c7b4-49a4-bca6-222fd38c6805.png)

**Comment by SpazCode153** [comment]
Hi benmcmorran, I have the same issue.
OS: Arch Linux(Manjaro Distro)
VSCode version: 1.62.0

Attached is the 3 different searches I have done for the extension.

![Microsoft Search](https://user-images.githubusercontent.com/20951103/148929953-8a42d030-d1b1-441b-a471-42c70572853b.jpg)
![Search Arduino](https://user-images.githubusercontent.com/20951103/148929958-15eb443f-754f-4e28-b7a2-2e4371b5a129.jpg)
![Search vscode-arduino](https://user-images.githubusercontent.com/20951103/148929960-f4b14e04-cb02-4e4b-82ea-1036b91f8865.jpg)

Is there more information I can provide for this issue?

**Comment by SpazCode153** [comment]
Hi benmcmorran,
I found a solution, it seems the software installer for Manjaro installs an older version of visual studio code, if I download visual studio code from the website and use it like that then I can find the extension.

**Comment by benmcmorran** [comment]
Thanks for letting me know, and I'm glad you got this working!
