### ISSUE TITLE
[Board Manager] no way to cancel downloading

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode-arduino#140]
It seems there is no way to cancel downloading.
Sometimes if I have poor network, I usually want to stop the download and trigger a new download task.

![image](https://cloud.githubusercontent.com/assets/1050213/23886483/3ba1268c-08b6-11e7-9b96-3f54a38452d6.png)

**Comment by liydu** [comment]
Wait to see what **arduino-cli** provide.

**Comment by czgtest** [comment]
#298 has the same request
