### ISSUE TITLE
Serial monitor stops auto-scrolling when clicking in the window

### ISSUE THREAD

**Issue by theficus** [microsoft/vscode-arduino#1409]
This is immensely annoying. Whenever I click in the Serial window it stops auto-scrolling.

**Comment by benmcmorran** [comment]
This extension uses a VS Code output pane for displaying serial monitor output, so you should be able to use standard VS Code settings to force the serial monitor to always auto-scroll. First turn off [output.smartScroll.enabled](https://github.com/microsoft/vscode/issues/69480#issuecomment-593401640) in your VS Code settings, then make sure the scroll lock icon at the top of the output pane is unlocked.
