### ISSUE TITLE
SOLVED - Failed to open serial port (TypeError)

### ISSUE THREAD

**Issue by Triangle4** [microsoft/vscode-arduino#1427]
Issue Type: Bug

<details><summary>Board Info</summary>

Arduino:Mega 2560
</details>
<details><summary>System</summary>

Windows 10 64Bit (Latest, Official)
Ryzen 3900x
GSkill 64GB DDR4
1024GB Sabrent Rocket Q

<details><summary>USB Hub</summary>

Brand: Generic
Ports: 16
Cable Length: 30 Feet
Power Supply: 100W
Connected Devices: 8 (1 draws more than 5mA of power)
</details>
</details>

<details><summary>Sketch</summary>

```
void setup() 
{
  pinMode(LED_BUILTIN, OUTPUT);
}


void loop() 
{
  digitalWrite(LED_BUILTIN, HIGH);
  delay(1000);                    
  digitalWrite(LED_BUILTIN, LOW); 
  delay(1000);                    
}
```
</details>

<details><summary>Error</summary>

_**Failed to open serial port COM9 due to error: + TypeError: Cannot read property 'then' of undefined**_
</details>

<details><summary>Additional Info</summary>

Extension Installed:  12:03PM, January 19 2020
Previously Installed: Never
</details>

<details><summary>Arduino.log</summary>

```
{"correlationId":"3e5544b7d1134551ae080dfc316a4291","command":"arduino.selectProgrammer","message":"executeCommandError","errorLine":"src/extension.js:232:76","telemetry":true,"level":"error","timestamp":"2022-01-19T20:08:33.024Z"}
{"correlationId":"28c20dcb6cdf456f875bfb3debeb521b","handlerName":"load-configitems","message":"expressHandlerError","errorLine":"src/arduino/arduinoContentProvider.js:274:152)","telemetry":true,"level":"error","timestamp":"2022-01-19T20:08:49.816Z"}
{"notification":"Failed to open serial port COM9 due to error: + TypeError: Cannot read property 'then' of undefined","showUser":true,"telemetry":true,"message":"openSerialMonitorError","errorLine":"vs/workbench/services/extensions/node/extensionHostProcess.js:85:821)","level":"warn","timestamp":"2022-01-19T20:16:19.536Z"}
{"notification":"Failed to open serial port COM9 due to error: + TypeError: Cannot read property 'then' of undefined","showUser":true,"telemetry":true,"message":"openSerialMonitorError","errorLine":"vs/workbench/services/extensions/node/extensionHostProcess.js:85:821)","level":"warn","timestamp":"2022-01-19T20:20:55.263Z"}
{"notification":"Failed to open serial port COM9 due to error: + TypeError: Cannot read property 'then' of undefined","showUser":true,"telemetry":true,"message":"openSerialMonitorError","errorLine":"vs/workbench/services/extensions/node/extensionHostProcess.js:85:821)","level":"warn","timestamp":"2022-01-19T20:21:22.466Z"}
{"notification":"Failed to open serial port COM9 due to error: + TypeError: Cannot read property 'then' of undefined","showUser":true,"telemetry":true,"message":"openSerialMonitorError","errorLine":"vs/workbench/services/extensions/node/extensionHostProcess.js:85:821)","level":"warn","timestamp":"2022-01-19T20:23:29.255Z"}
{"notification":"Failed to open serial port COM9 due to error: + TypeError: Cannot read property 'then' of undefined","showUser":true,"telemetry":true,"message":"openSerialMonitorError","errorLine":"vs/workbench/services/extensions/node/extensionHostProcess.js:85:821)","level":"warn","timestamp":"2022-01-19T20:54:16.867Z"}
{"notification":"Failed to open serial port COM9 due to error: + TypeError: Cannot read property 'then' of undefined","showUser":true,"telemetry":true,"message":"openSerialMonitorError","errorLine":"vs/workbench/services/extensions/node/extensionHostProcess.js:85:821)","level":"warn","timestamp":"2022-01-19T20:55:30.857Z"}
{"notification":"Failed to open serial port COM9 due to error: + TypeError: Cannot read property 'then' of undefined","showUser":true,"telemetry":true,"message":"openSerialMonitorError","errorLine":"vs/workbench/services/extensions/node/extensionHostProcess.js:85:821)","level":"warn","timestamp":"2022-01-19T20:55:43.039Z"}
```
</details>

<details><summary>Resolution</summary>

Updated vscode to the latest version. (1.57.3 -> 1.63.2)
Issue is now resolved.
</details>

**Comment by benmcmorran** [comment]
Thanks for the report @Triangle4! To help diagnose this issue, can you post the content of `%USERPROFILE%\.vscode\extensions\vsciot-vscode.vscode-arduino-0.4.10\arduino.log`? That should let us identify which line is causing the crash. Please remove any sensitive information before posting the log.

**Comment by Triangle4** [comment]
Added it to the initial post. Its in the last dropdown

**Comment by benmcmorran** [comment]
Thanks. The error line that corresponds to the message you were seeing is `vs/workbench/services/extensions/node/extensionHostProcess.js:85:821)` which is surprising because that code is actually part of VS Code itself, not this extension. I'm guessing the extension is return some invalid object back to VS Code, which is then causing the exception.

If you'd like to try debugging this yourself, go for it! The extension is open source at this GitHub repo, and [the code that's logging the error message is here](https://github.com/microsoft/vscode-arduino/blob/faf77358cf8ccc436d56a57e4fc3891c133b0e49/src/serialmonitor/serialMonitor.ts#L166-L172). Something inside that `try` block is going wrong. The [development instructions in the README](https://github.com/microsoft/vscode-arduino#development) should still be up to date, but let me know if you have any issues or would like help fixing this.

**Comment by Triangle4** [comment]
I would definitely like help fixing it. I am not strong enough a developer to be working on vscode source. I will dig in though and see what I can figure out. 
I will let you know if I arrive at a conclusion.
Can I ask, does this happen to you, when you open the serial port? Otherwise I will try it on a few other computers and see if it is reproducible.

**Comment by benmcmorran** [comment]
No worries! We welcome external contributions, but there's definitely no obligation to fix the bug yourself.

I haven't seen this particular issue before. If I can't figure anything else out, I'll try adding some additional logging in the next release of the extension so that we can better narrow down the issue you're having.

**Comment by Triangle4** [comment]
So I tried it on one of my other machines and it works. There is no input. 
I noticed that the VSCODE versions do not match.
After installing the lastest of vscode, this error is gone.

**Comment by benmcmorran** [comment]
Glad you got this figured out! It's possible to send commands to the serial port by using commands. On Windows type `CTRL + SHIFT + P` and search for "serial port".

![image](https://user-images.githubusercontent.com/6981284/150229412-0fce38ee-7a55-4912-a11f-86c6d608f648.png)

**Comment by Triangle4** [comment]
Thanks Ben. 
I am curious, Lets say I wanted to place a button next to the serial monitor button
Where would I start?

And if I am successful, where would I share that code so you can implement it in future extensions.
I sent you an email, if you are open to it we can discuss this there. I know you are busy so I won't take more than a minute of your time.

Thanks again for your help.
