### ISSUE TITLE
Listen for baud rate changes in settings.json

### ISSUE THREAD

**Issue by tysonmatanich** [microsoft/vscode-arduino#1429]
There is currently the ability to set `arduino.defaultBaudRate` in `settings.json` however no way to override it per project without manually changing it.

Please add support for a project level setting in `arduino.json`. For example:
```json
{
    "sketch": "example.ino",
    "board": "arduino:avr:uno",
    "port": "COM4",
    "baudRate": 9600,
    "output": "./build"
}
```

**Comment by BelKed** [comment]
You can override it per each project using `settings.json` in `.vscode` folder (you have to create it in project directory). But you have to restart VSCode after each change of baud rate in that `.vscode/settings.json` file. This file should look like this:

```json
{
    "arduino.defaultBaudRate": 9600
}
```

---

But I think that, what you suggest is better, because after each change of baud rate using "Arduino: Change Baud Rate" it will be written in `arduino.json` and you don't have to restart VSCode after each change.

**Comment by robotdad** [comment]
@benmcmorran what do you think of the suggestion for baud rate in arduino.json? Would arduino.json or settings.json be better in context of other changes going on around serial support? If we keep it in settings would it be possible to remove the requirement to reload VS to detect that change?

**Comment by benmcmorran** [comment]
I'd prefer to keep settings in `settings.json` where possible. It plays better with the rest of the VS Code configuration ecosystem by automatically providing cascading overrides from the global to workspace folder level and has built-in graphical editor support. Regarding VS Code restarts after changing values in settings.json, we should be able to avoid that by subscribing to [`workspace.onDidChangeConfiguration`](https://code.visualstudio.com/api/references/vscode-api#workspace.onDidChangeConfiguration). I'll rename this issue to reflect that approach.

**Comment by BelKed** [comment]
Also, after using command for changing value it should be written to `settings.json`.
And change of values in that file should reflect in VSCode...
 
By the way, isn't this issue related to this one?

- https://github.com/microsoft/vscode-arduino/issues/709

**Comment by gcampbell-msft** [comment]
@tysonmatanich We have recently updated the Arduino extension to depend on a new standalone Serial Monitor extension, please upgrade your arduino extension and try out this new feature!

Let us know if it solves your issue or if the issue still persists!
