### ISSUE TITLE
Conflict with extension Output Colorizer

### ISSUE THREAD

**Issue by Alecton4** [microsoft/vscode-arduino#1447]
After installing this extension, [Output Colorizer](https://marketplace.visualstudio.com/items?itemName=IBM.output-colorizer) does not work anymore. Output panel becomes black and white again.
My environment:
```
- Windows 10 21H2
- VSCode 1.63.2
- extension: Output Colorizer 0.1.2
- extension: Arduino 0.4.10
```

**Comment by benmcmorran** [comment]
Thanks for the report. This is a [limitation of VS Code itself](https://github.com/microsoft/vscode/issues/11005) and [any other extension that provides a grammar for the output pane will likely hit the same issue](https://github.com/IBM-Cloud/vscode-log-output-colorizer/issues/21#issuecomment-392047772).
