### ISSUE TITLE
Set custom Arduino IDE preferences

### ISSUE THREAD

**Issue by DRSDavidSoft** [microsoft/vscode-arduino#1464]
Hi there, I'm looking into the documentation, but haven't quite figured this out yet.

Is there a way to pass some `preferences` to the ide?  The command line would be something like `--pref key=value`, but I was wondering if there is a way to set such configuration in `arduino.json`, and have it be passed using the `setPref()` method call:

https://github.com/microsoft/vscode-arduino/blob/2a47a35cdac33a96c3bc24d7b498dfd3d67fed58/src/arduino/arduino.ts#L135

So maybe I could write config like this:
```json
{
    "preferences": {
        "upload.tool": "avrdude_custom"
    }
}
```

**Comment by davidcooper1** [comment]
Hi! After a bit of research, I found that the `arduino.json` can have build preferences added in the following format:

```json
{
    "buildPreferences": [
        ["upload.tool", "avrdude_custom"]
    ]
}
```
Essentially just put any preference you want into the array as an array with the first element being the key and the second the value.

**Comment by DRSDavidSoft** [comment]
@davidcooper1 Great, going to test this right away!

Thank you for the tip!

**Comment by gruenfron** [comment]
> Essentially just put any preference you want into the array as an array with the first element being the key and the second the value.

Oh wow, thanks for pointing out.

```json
    "port": "192.168.xx.yy",
    "buildPreferences": [
        [
            "runtime.pwd.192.168.xx.yy",
            "mySecretPassword"
        ]
    ],
```
This easily solves my ESP32 simple OTA upload-with-password problem showing "Authorization required: No authorization data found" (#676).
