### ISSUE TITLE
Basic `wiring` identifiers are undefined?

### ISSUE THREAD

**Issue by zfields** [microsoft/vscode-arduino#1468]
![vscode-ext-arduino-issue](https://user-images.githubusercontent.com/2801887/157269312-c72226f5-f174-4a39-b795-352156743964.png)

As you can see in the screenshot, VSCode claims the most basic wiring APIs are not defined.

I have validated the paths in the `c_cpp_preferences.json`, and they are correct. I also noticed that the problem matcher claims it is checking against C/C++(20) in the **PROBLEMS** tab. However, the standard specified in `c_cpp_preferences.json` clearly states `c++14`.
_For the record: The `c_cpp_preferences.json` file was generated by the extension. I did NOT modify the file; I only verified its contents._

The code compiles without warnings, and if I press F12, then it will find the definition of either of the API.

**Comment by benmcmorran** [comment]
Hi @zfields! I'm was able to reproduce this issue, although eventually the identifiers did resolve. Given that F12 works, I suspect this is an issue with the C++ extension that powers our IntelliSense. I'm going to transfer this issue to the cpptools repo for further investigation.

**Comment by benmcmorran** [comment]
Sorry, looks like I don't have permission to transfer. Can you [open an issue with this template](https://github.com/microsoft/vscode-cpptools/issues/new?assignees=&labels=&template=language-service.md&title=)?
