### ISSUE TITLE
command 'arduino.showBoardConfig' not found

### ISSUE THREAD

**Issue by carreylife** [microsoft/vscode-arduino#1471]
macOS Mojave 
version 10.14.6

vscode 1.65
 settings.json
![image](https://user-images.githubusercontent.com/24565609/157823534-8c128473-1849-41b7-bfc5-89d3e5807c1c.png)

**Comment by aleun** [comment]
Thanks for your report. What version of the extension, and what version of the Arduino IDE do you have installed?

Also, can you try setting `arduino.commandPath` to `Contents/MacOS/Arduino`? `arduino_debug.exe` would be the default setting for Windows, not Mac.

**Comment by carreylife** [comment]
> Thanks for your report. What version of the extension, and what version of the Arduino IDE do you have installed?
> 
> Also, can you try setting `arduino.commandPath` to `Contents/MacOS/Arduino`? `arduino_debug.exe` would be the default setting for Windows, not Mac.

Thanks for your reply.
**vscode extension: 0.4.6 preview**
**Arduino IDE: 1.8.19**
i have setting arduino.commandPath to Contents/MacOS/Arduino but not work.

**Comment by benmcmorran** [comment]
Hi @carreylife. The current release of the extension is version 0.4.11, not 0.4.6. Can you try updating and let me know if you still see the issue?

Also to clarify, can you describe the steps you are taking, what you expect see, and what actually happens?

**Comment by MonveChen** [comment]
Me too, it took a long time and finally gave up

**Comment by nya3jp** [comment]
Hi,

I encountered the same error message for every Arduino extension commands. After a bit of debugging, I found that Arduino extension fails to activate if the setting `C_Cpp.intelliSenseEngine` is disabled. The extension started working once I enabled the setting.

Hope this helps.

**Comment by benmcmorran** [comment]
Thanks for that clue @nya3jp. Unfortunately, I'm still not able to reproduce this issue. I tried adding this line to a workspace settings.json file.

```
    "C_Cpp.intelliSenseEngine": "Disabled"
```

However, the Arduino extension still appeared to activate correctly and board management commands worked. Am I missing any steps?

**Comment by nya3jp** [comment]
Looks like the issue does not happen with latest C/C++ extension (v1.9.8). I can reproduce the issue on v1.9.7, but not on v1.9.8.

**Comment by Nebula83** [comment]
Settings that worked for me:
command path: `Contents/MacOS/Arduino`
Arduino path: `/Applications/Arduino.app`

but YMMV
