### ISSUE TITLE
Cannot select COM-Port that is invisible in the Device Manager

### ISSUE THREAD

**Issue by svollenweider** [microsoft/vscode-arduino#1472]
If you pass a COM port through via RDP it will not show up in the Device Manager under Windows. However, Powershells  `[System.IO.Ports.SerialPort]::getportnames()` will list all ports, including the "invisible" ones.

"Invisible" ports are not selectable in the VS Code extension. 
However, they are selectable in the standard Arduino IDE.

**Comment by gcampbell-msft** [comment]
@svollenweider We have recently updated the Arduino extension to depend on a new standalone Serial Monitor extension, please upgrade your arduino extension and try out this new feature!

Let us know if it solves your issue or if the issue still persists!
