### ISSUE TITLE
Upload and Verify buttons are missing from the Actionbar

### ISSUE THREAD

**Issue by iqapps** [microsoft/vscode-arduino#1476]
Not sure when this was implemented, but can we have them back or configurable.

**Comment by benmcmorran** [comment]
Hi @iqapps! Can you clarify what you mean by the "Actionbar"? Using the [terminology from this article](https://code.visualstudio.com/docs/getstarted/userinterface), there should already be upload and verify buttons in the "editor toolbar", but there are no upload and verify buttons in the "status bar". 

![image](https://user-images.githubusercontent.com/6981284/159783974-4669517d-ff67-4912-b564-eb422cf0a64b.png)

**Comment by iqapps** [comment]
Hi, It is a typo, sorry. I ment to write "editor toolbar" :-)

I can see you have the Arduino Upload and verify buttons, but I dont. I have GIT buttons instead.

![image](https://user-images.githubusercontent.com/12947531/159871641-aa557095-89b7-499d-a682-f0c9f9e20dae.png)

When I search in settings with various keywords, anything found, nothing relates to make the Arduino extension show these buttons.

**Comment by iqapps** [comment]
Ahhhh, really ! 

Its only showing the buttons when an actual INO file is selected.

**Comment by gcampbell-msft** [comment]
@iqapps Based on your most recent comment, it seems you found what is going on based on the behavior of those buttons only showing when an INO file is selected. Closing.
