### ISSUE TITLE
Cann't add newer arduino-esp32 to VSCode

### ISSUE THREAD

**Issue by joroMaser** [microsoft/vscode-arduino#1487]
When I looking at "Arduino Board Manager" in VSCode (Windows) version 1.66.0  and search esp32, I can select to install only version 1.0.0 - 1.0.5
But in https://github.com/espressif/arduino-esp32 there is already version 2.0.2 !

In arduino.additionalUrls I put 
`https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json` Like I saw [here](https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html)
And click  Refresh Packet Indexes , I still not see version 2.0.2

![esp32_1](https://user-images.githubusercontent.com/14313895/161445310-1804d343-e486-49a7-980c-271cd8a6a61b.png)
![esp32](https://user-images.githubusercontent.com/14313895/161445311-6d77cd7f-8870-4298-bfde-78027107cc6f.png)

**Comment by benmcmorran** [comment]
Hi @joroMaser. I just tried following these steps on version 0.4.11 but I do see 2.0.2 in the dropdown.

![image](https://user-images.githubusercontent.com/6981284/166072659-fc323ae1-3f4c-4bc1-8795-e407d436b45e.png)

A few questions that can help us narrow down the issue:

- What version of the vscode-arudino extension are you using?
- Are you using the Arduino IDE or the arduino-cli, and which version?
- What operating system are you using?
