### ISSUE TITLE
Intellisense not doing complete updating 

### ISSUE THREAD

**Issue by iqapps** [microsoft/vscode-arduino#1488]
I have intellisense report missing references in my workspace, for some keywords, while most other works fine.

Getting this error when pressing F12, While the called class clearly contains the method, and have had it for several iterations...

![image](https://user-images.githubusercontent.com/12947531/161526828-e25311bf-8743-4441-8a83-3e6eb51dc754.png)

Even pressing F12 on the method itself, says na...dont know what this is... :-)

![image](https://user-images.githubusercontent.com/12947531/161528876-2ef799bc-b5f3-4f95-83c0-0b94e8a8521a.png)

This is just one example, but I experience it throughout the workspace, but at somewhat rare occasions luckily. This problem has existed for several versions of the extension.

Rebuilding intellisense with CTRL+ALT+I says its doing something, but this do not solve the problem.
Restarting VSCode dont help.

I would love to give you some logs, but they are not where the verify output says it should be. Even when Verbose output is turned on.

`
Please see the build logs in output path: c:\Code\.....
`

**Comment by nimish** [comment]
Same here. Mac OS, arduino-cli. Include paths generated are missing the `/**` recursion.

**Comment by benmcmorran** [comment]
Thanks for the report @iqapps. IntelliSense in this extension works by generating a `c_cpp_properties.json` file in the `.vscode` directory. Can you share that file with us after removing any sensitive information? What we're looking for is that the path to the file you are editing is included in the configuration file somewhere, which should include it for IntelliSense processing.
