### ISSUE TITLE
Compilation is performed with every modification to "Board Config UI" (GUI for `arduino.json`).

### ISSUE THREAD

**Issue by zfields** [microsoft/vscode-arduino#1496]
Since firmware cannot be flashed without first compiling it, it is redundant and unproductive to verify every time a value in the Board Config UI changes.

This is less obnoxious when you have a standard issue Arduino board, like the Uno that doesn't really have any settings to speak of, but if you have a more sophisticated board, like an ST chip for example, there are multiple fields in the Board Config UI. Each modification results in a full recompile.

**The experience is PAINFUL.**

Please only compile when it is requested using **Verify**, or before **Upload** is performed. This is inline with the Arduino IDE and provides a WAY BETTER experience.

**Comment by benmcmorran** [comment]
Hi @zfields! An upcoming release (hopefully later today) will include #1480 which adds [the `arduino.analyzeOnOpen` and `arduino.analyzeOnSettingChange` options](https://github.com/microsoft/vscode-arduino#options). Setting `arduino.analyzeOnSettingChange` to `false` should fix your issue.
