### ISSUE TITLE
Portables versions

### ISSUE THREAD

**Issue by HugoCar77** [microsoft/vscode-arduino#1497]
Hi..!!

I use portables versions of vscode and arduino ide and for me both fine for now...but
I cant use 'Arduino Examples' directly from vscode if I change defaul sketchbook.path in for other in Arduino IDE

With defaul sketchbook.path run OK and open examples in a new window

![vscode](https://user-images.githubusercontent.com/60515894/165847986-b38a9243-e2a5-4b40-a883-62c1ecd2dee8.jpg)
![arduino config](https://user-images.githubusercontent.com/60515894/165848007-d0ddfb90-53b8-485e-b180-bf4d4c4074be.jpg)

Thanks!!

**Comment by benmcmorran** [comment]
Hi @HugoCar77. To clarify, when you change the sketchbook path in the Arduino IDE, what happens to the "Arduino Examples" view? Does it not load at all, or are there some examples missing that you would expect to see there?

**Comment by HugoCar77** [comment]
Hi...

Original path:
I can execute with double click
I can see everything

![vscode original path](https://user-images.githubusercontent.com/60515894/166084651-05e15f06-6960-4a8c-87e7-c909e0d9adc3.jpg)


Personal path:
I can't run... double click and nothing happens
I also can't see "Personal Library Examples"

![vscode personal path](https://user-images.githubusercontent.com/60515894/166084826-57874173-7f03-42d1-a186-527b67624c63.jpg)



I have try even with a new windows install and an arduino and vscode install too
