### ISSUE TITLE
v0.4.12-rc - command not found

### ISSUE THREAD

**Issue by Daedelos** [microsoft/vscode-arduino#1499]
v0.4.12-rc
Selecting any action via F1 results in command not found:

e.g.

Command 'Arduino: Board Config' resulted in an error (command 'arduino.showBoardConfig' not found)

**Comment by Daedelos** [comment]
![Screenshot 2022-05-01 121233](https://user-images.githubusercontent.com/25985496/166143517-ca167c4f-d224-496a-9a65-f245e23426eb.png)

**Comment by benmcmorran** [comment]
This issue should be fixed in the v0.4.12 release, which is available on the VS Code Marketplace.
