### ISSUE TITLE
arduino uno unable to generate bin file?

### ISSUE THREAD

**Issue by xiezhoubin** [microsoft/vscode-arduino#1503]
![image](https://user-images.githubusercontent.com/75734559/167810825-4642328f-2ca7-42ea-9422-e97d4fcd6812.png)
It can generate hex files and ELF files, but there is no bin file.

**Comment by aleun** [comment]
Can you provide some extra info to help us reproduce the issue?

1. Extension version
2. Arduino IDE or Arduino CLI version
3. If possible, a link to a sample project demonstrating the problem

**Comment by jegjessing** [comment]
I too see this problem.
I compile the code using Arduino IDE, both 1.8.x and 2.x and the result is just as shown in the picture.
I simply cannot generate a .bin file
