### ISSUE TITLE
c_cpp_properties.json does not include Arduino section

### ISSUE THREAD

**Issue by avtalion** [microsoft/vscode-arduino#1514]
extension did not modify c_cpp_properties.json to include Arduino configs, so intelliSense and Highlighting work for Win32 and marks most of the code as incorrect.
c++ config json (c_cpp_properties.json):
![image](https://user-images.githubusercontent.com/20072845/173024705-4bb1fe2e-027e-49a4-b310-662066aa96b7.png)
code marked with errors:
![image](https://user-images.githubusercontent.com/20072845/173024835-7f93fd50-f0f1-43a2-a69c-ce87b74cfcf3.png)

**Comment by gcampbell-msft** [comment]
Can you provide some extra info to help us reproduce the issue?

1. Operating system (from your screenshot, I see it's Windows)
2. What device are you using?
3. If possible, a link to a sample project demonstrating the problem, this could be a great help for us to immediately repro.
