### ISSUE TITLE
cannot find arduino IDE, i'm using WSL with arduino inside WSL

### ISSUE THREAD

**Issue by Mettikodeva** [microsoft/vscode-arduino#1523]
where should I specify the path of the arduino inside the WSL, in User or Remote[WSL:Ubuntu]?
![image](https://user-images.githubusercontent.com/70711951/178694677-66cfc867-4b4b-491e-b869-9b374efae6ea.png)
or I can only use arduino inside windows?
is there any way to compile with arduino inside wsl from this extension?

**Comment by fearthecowboy** [comment]
Do you have the linux version of arduino installed inside the WSL instance?

**Comment by Mettikodeva** [comment]
yes, i've installed the arduino and set the path inside the vscode
![image](https://user-images.githubusercontent.com/70711951/179845691-a232a6b6-cd51-4aac-9b93-7d8c6935dfac.png)

**Comment by Mettikodeva** [comment]
yes i've installed the arduino and i've set the path too
![image](https://user-images.githubusercontent.com/70711951/179845795-dbc3f644-eb62-41a3-9059-3559a1acb4c1.png)

**Comment by gcampbell-msft** [comment]
@Mettikodeva Could you show us what error you are seeing? It might help us diagnose where the issue is arising. Thanks!

**Comment by David00** [comment]
I'm getting this issue too. 

### Settings.json:

```
$ cat ~/.vscode-server/data/Machine/settings.json | grep "arduino"
    "arduino.path": "/home/david/.local/bin/arduino-cli"
```

### Testing the `arduino-cli` package at the path above:

```
$ /home/david/.local/bin/arduino-cli version
arduino-cli  Version: 0.27.1 Commit: a900cfb2 Date: 2022-09-06T16:44:27Z
```

When I choose Arduino: Initialize from the extension actions, I get the message:

> Cannot find Arduino IDE. Please specify the "arduino.path" in the User Settings. Requires a restart after change.

I have restarted VS Code.


VS Code Version: 1.71.0
Windows 11 x64
WSL Details:
```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```


Let me know if you need more information.

**Comment by borhanreo** [comment]
### **_My arduino Version_**
![ard 2](https://user-images.githubusercontent.com/11036088/190567213-573e1547-8c50-41ee-9eb9-1ca0cbe2b29f.png)

### **_Install location of arduino version 2.0.0_**
![install location](https://user-images.githubusercontent.com/11036088/190567393-999084b2-59dc-4f61-9227-501db83ff5b7.png)

### **_Still i did not resolve the issue_**
![VS show](https://user-images.githubusercontent.com/11036088/190567476-e5795814-eada-44ff-848a-f9e9158458bd.png)

Could you please give me help, what i have miss

**Comment by arminrosu** [comment]
@borhanreo Arduino IDE 2.0 is not supported (see https://github.com/microsoft/vscode-arduino/issues/1477). Use the [CLI](https://github.com/microsoft/vscode-arduino#arduino-cli) to get the extension working.
