### ISSUE TITLE
Not work with the IBM Output Colorizer plugin. 

### ISSUE THREAD

**Issue by nmpassthf** [microsoft/vscode-arduino#1530]
Does not work with the Output Colorizer plugin.
When I enable this plugin, Output Colorizer stops working and cannot colorize any text in the output.

The Output Colorizer plugin: [link](https://github.com/IBM-Cloud/vscode-log-output-colorizer)

**Comment by BelKed** [comment]
Duplicate of https://github.com/microsoft/vscode-arduino/issues/1447

**Comment by benmcmorran** [comment]
As mentioned in the linked issue, this is a [limitation of VS Code itself](https://github.com/microsoft/vscode/issues/11005) and [any other extension that provides a grammar for the output pane will likely hit the same issue](https://github.com/IBM-Cloud/vscode-log-output-colorizer/issues/21#issuecomment-392047772). Feel free to discuss on the VS Code issue tracker.
