### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by asmshamim** [microsoft/vscode-arduino#1534]
- Issue Type: `Bug`
- Extension Name: `vscode-arduino`
- Extension Version: `0.4.12`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.71.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by gcampbell-msft** [comment]
@asmshamim Could you provide some detail about the issue you're having? Thank you for posting the version numbers, etc, but I don't see details about what the actual issue is. 

Thanks!
