### ISSUE TITLE
Encoding issue in Output Channel

### ISSUE THREAD

**Issue by formulahendry** [microsoft/vscode-arduino#154]
The Node child_process does not take good care of encoding issue if your OS locale is not en-us.
Refer to https://github.com/nodejs/node-v0.x-archive/issues/2190
`chcp 65001` is one of the workaround.

However, in below screenshot, My OS is en-us. maybe it is another issue.
![image](https://cloud.githubusercontent.com/assets/1050213/23889666/41626dca-08c9-11e7-872a-100327fda125.png)

**Comment by liydu** [comment]
@Sneezry to add the reference issue id from VS Code for tracking purpose.

**Comment by liydu** [comment]
https://github.com/Microsoft/vscode/issues/3550

**Comment by czgtest** [comment]
#447 meet the same issue.
