### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by juliusRomanzeira** [microsoft/vscode-arduino#1540]
I just tried a lot of times use ide arduino with vscode. I'll attach the error here:
![Screenshot (2)](https://user-images.githubusercontent.com/91900152/195429117-b6a4a9f4-7538-4cdf-9c38-ba30bfb007d5.png)
![Screenshot (3)](https://user-images.githubusercontent.com/91900152/195429121-a5c9ba3c-2d0f-4bc2-9527-ce9d03e0fbf0.png)
![Screenshot (4)](https://user-images.githubusercontent.com/91900152/195429124-cca71e3d-b137-4fbe-bbca-4aabe35052e1.png)
![Screenshot (5)](https://user-images.githubusercontent.com/91900152/195429126-1b4ccab6-2ac6-4637-a44c-1e9183ba0f67.png)
![Screenshot (6)](https://user-images.githubusercontent.com/91900152/195429127-741901cc-5144-442e-bce3-b23cfc39c2c8.png)
![Screenshot (7)](https://user-images.githubusercontent.com/91900152/195429129-b595695a-0270-4d46-8cc3-2b7b26da2ae8.png)
![Screenshot (8)](https://user-images.githubusercontent.com/91900152/195429131-5a5cc940-1994-4673-ad24-5b837b9debc0.png)
![Screenshot (9)](https://user-images.githubusercontent.com/91900152/195429133-7a36afcf-b41e-4f25-94d2-8b52448dedb0.png)

**Comment by arminrosu** [comment]
Arduino IDE 2.0? See https://github.com/microsoft/vscode-arduino/issues/1477

**Comment by hlovdal** [comment]
Could you update the title of this issue to something more descriptive than just "Bug"?

Imagine what nightmare it would be for the maintainers if all the issues listed at https://github.com/microsoft/vscode-arduino/issues just had titles "Bug" or "Feature request".

**Comment by hlovdal** [comment]
#1548

**Comment by benmcmorran** [comment]
Thanks for the feedback. [Only the legacy IDE is currently officially supported](https://github.com/microsoft/vscode-arduino/blob/374c78f8ed06c1e88df480b687c24c06b728e13b/README.md?plain=1#L39). Additionally, **we plan to drop support for the legacy IDE entirely in the next release of this extension** and recommend that all users move to Arduino CLI as soon as possible. The recent `v0.5.0` release of the extension includes a bundled copy of Arduino CLI that should ease this migration.
