### ISSUE TITLE
Cannot find Arduino IDE. Please specify the "arduino.path" in the User Settings. Requires a restart after change.

### ISSUE THREAD

**Issue by koen1711** [microsoft/vscode-arduino#1545]
So I have set:
"arduino.path" to: C:\Program Files\Arduino IDE
And restarted VScode and it still doesn't work.

What could be the issue?

**Comment by rw377** [comment]
https://github.com/microsoft/vscode-arduino/issues/1548

**Comment by yk-solomon** [comment]
Same

**Comment by hlovdal** [comment]
This issue can most likely be closed as a duplicate of #1548.

**Comment by benmcmorran** [comment]
Thanks for the feedback. [Only the legacy IDE and Arduino CLI are currently officially supported](https://github.com/microsoft/vscode-arduino/blob/374c78f8ed06c1e88df480b687c24c06b728e13b/README.md?plain=1#L39). Additionally, **we plan to drop support for the legacy IDE entirely in the next release of this extension** and recommend that all users move to Arduino CLI as soon as possible. The recent `v0.5.0` release of the extension includes a bundled copy of Arduino CLI that should ease this migration.
