### ISSUE TITLE
Disable Auto Compiling when Board Configuration Changed

### ISSUE THREAD

**Issue by wachidsusilo** [microsoft/vscode-arduino#1549]
Hi, is there a way to disable auto compiling when changing the board configuration (and when opening the sketch)?
It's annoying to wait the compiling finished before i can upload the code. When i upload the code, it will be compiled again anyway. So what is the purpose of doing this such thing?

**Comment by StefanKellerAC** [comment]
Yes! in the settings of the extension :-)
disable: Analyze on open/settings changed

**Comment by hlovdal** [comment]
So this issue could be closed then I assume.
