### ISSUE TITLE
Unable to find Arduino executable without the name "arduino_debug"

### ISSUE THREAD

**Issue by DraftedDev** [microsoft/vscode-arduino#1580]
Hi, I recently stumbled upon the issue of the **`arduino.path` setting being invalid for some reason**.
I found out that the extension searches for the `arduino_debug.exe` file in the `arduino.path` setting, however in newer versions of the Arduino IDE the `arduino_debug.exe` file does not exist.

**There's a quick fix for everyone passing by**, trying to fix the "arduino.path is set, but doesn't work"-issue
Just copy-paste the `Arduino IDE.exe` (in the installation folder) file and rename it to `arduino_debug.exe`.

**Comment by benmcmorran** [comment]
Thanks for the feedback. Are you using Arduino IDE 2.x? [Only the legacy IDE is currently supported](https://github.com/microsoft/vscode-arduino/blob/374c78f8ed06c1e88df480b687c24c06b728e13b/README.md?plain=1#L39). Additionally, **we plan to drop support for the legacy IDE entirely in the next release of this extension** and recommend that all users move to Arduino CLI as soon as possible. The recent `v0.5.0` release of the extension includes a bundled copy of Arduino CLI that should ease this migration.
