### ISSUE TITLE
Verify / Upload keeps looking for an "arduino.ino" file

### ISSUE THREAD

**Issue by bennierex** [microsoft/vscode-arduino#1583]
I'm trying out the Arduino VScode extension, but keep getting the same error that "arduino.ino" main file is missing. I've actually tried automatically and manually setting the "sketch" to my own file ("blinker.ino"), but this only works as long as I have a "arduino.ino" file in my project directory. That file can actually be empty, but without it it doesn't verify/upload:

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/6532813/216994280-3ca6da9f-2905-4b93-aa7b-a5f6077eb7b3.png">

<img width="605" alt="image" src="https://user-images.githubusercontent.com/6532813/216994512-6ca4724b-5f55-4e25-9a6c-981e5481d300.png">

Now, adding an empty arduino.ino file to my project, it verifies and uploads without problems (not sure why it can't generate the IntelliSense config though):

<img width="860" alt="image" src="https://user-images.githubusercontent.com/6532813/216995224-1191255c-c61a-451f-abbc-7650837f9689.png">

### VS Code version info
Version: 1.75.0 (Universal)
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:24:42.903Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.2.0
Sandboxed: No

### Arduino extension info
Name: Arduino
Id: vsciot-vscode.vscode-arduino
Description: Arduino for Visual Studio Code
Version: 0.4.13
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-arduino

### Other info
Using `arduino-cli` on macOS Ventura 13.1 (Apple silicon), installed via homebrew.
arduino-cli  Version: 0.29.0 Commit: 76251df9 Date: 2022-11-16T14:49:42Z

**Comment by benmcmorran** [comment]
Hi @bennierex, [this is a limitation of Arduino itself](https://arduino.github.io/arduino-cli/0.20/sketch-specification/#primary-sketch-file).

> Every sketch must contain a .ino file with a file name matching the sketch root folder name.
