### ISSUE TITLE
Can't Verify/Upload Sketches

### ISSUE THREAD

**Issue by Arkapravo-Ghosh** [microsoft/vscode-arduino#1634]
Whenever I'm pressing Verify or Upload button, I'm getting the following error:
```
[Starting] Analyzing sketch 'test/test.ino'
[Warning] Output path is not specified. Unable to reuse previously compiled files. Build will be slower. See README.
Picked up JAVA_TOOL_OPTIONS: 
Error: unknown option: --no-color
[Warning] Failed to generate IntelliSense configuration.
[Error] Analyzing sketch 'test/test.ino': Exit with code=3
```
I have no idea why this error is happening.
OS: Arch Linux (x86_64)

**Comment by harry-po** [comment]
hello dude, i want to ask about ur solution, I have been try ur solve but it's still error. 

[Starting] Analyzing sketch 'test.ino'
[Warning] Output path is not specified. Unable to reuse previously compiled files. Build will be slower. See README.
Error opening sketch: main file missing from sketch: /home/o-soba/Arduino/generated_examples/encoder/encoder/encoder.ino
[Warning] Failed to generate IntelliSense configuration.
[Error] Analyzing sketch 'test.ino': Exit with code=1
like this. could u share any solution if u have? 
thanks u regards

**Comment by harry-po** [comment]
oh sorry dude i have been done with my problem thanks u

**Comment by Arkapravo-Ghosh** [comment]
> hello dude, i want to ask about ur solution, I have been try ur solve but it's still error. 
> 
> [Starting] Analyzing sketch 'test.ino'
> [Warning] Output path is not specified. Unable to reuse previously compiled files. Build will be slower. See README.
> Error opening sketch: main file missing from sketch: /home/o-soba/Arduino/generated_examples/encoder/encoder/encoder.ino
> [Warning] Failed to generate IntelliSense configuration.
> [Error] Analyzing sketch 'test.ino': Exit with code=1
> like this. could u share any solution if u have? 
> thanks u regards 

In most cases, putting the correct sketch path in `.vscode/arduino.json` works considering the sketch is in a directory having same name as sketch name, like `main/main.ino`.
