### ISSUE TITLE
Tutorial - Help/Offline tutorial integration

### ISSUE THREAD

**Issue by shizn** [Microsoft/vscode-arduino#21]

**Comment by liydu** [comment]
@shizn , what does it mean?

**Comment by czgtest** [comment]
@liydu  Can you sync with Shi Xin again ?

**Comment by liydu** [comment]
There is offline tutorial provided by VisionMicro for VS. But it's low priority. In Backlog for now.

**Comment by ArthurMa1978** [comment]
agree, too many unknown stuffs.
And since it's just a extension on vs code, don't think we need to support a offline book for Arduino, no worth to maintain it, so close.
