### ISSUE TITLE
No color in Output Channel if I installed Code Runner extension

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode-arduino#214]
If I install [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner) extension:
![image](https://cloud.githubusercontent.com/assets/1050213/24783982/31bf4b60-1b82-11e7-81db-7b53697dce01.png)
After I disable Code Runner extension:
![image](https://cloud.githubusercontent.com/assets/1050213/24783984/37d74246-1b82-11e7-8bc3-c93298895c15.png)

**Comment by liydu** [comment]
Not related with extension itself.
