### ISSUE TITLE
[Lib Manager] typo of search result count

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode-arduino#215]
Should be `Library` instead of `Libraries`
![image](https://cloud.githubusercontent.com/assets/1050213/24784051/a078db7a-1b82-11e7-9f29-b9bd2fd39c94.png)

**Comment by czgtest** [comment]
Now the text " 1 Libraries matched" is not display after search Library.  here is the snapshot.
![image](https://user-images.githubusercontent.com/35018765/37076088-dd166cb6-220f-11e8-91d3-d63b51fb8020.png)
