### ISSUE TITLE
generic *.pde support

### ISSUE THREAD

**Issue by shizn** [Microsoft/vscode-arduino#217]
*.pde is the obsolete Arduino sketch file. Probably we need activate our extension when *.pde file is opened in the future.

**Comment by liydu** [comment]
@shizn Is there anybody still using this format? Otherwise, suggest we just close it.

**Comment by czgtest** [comment]
@liydu  Can you review this request again?

**Comment by liydu** [comment]
Close it for now as we did not see anybody is using *.pde now.

**Comment by ddownn** [comment]
the .pde format is also used for Processing. I would like to see formatting for PDE files in VS Code. I've been using TobiahZ/[processing-vscode](url
https://github.com/TobiahZ/processing-vscode)

...sadly, it doesn't have formatting.
