### ISSUE TITLE
SelectSerialPort dropdown menu should display the right board name 

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode-arduino#233]
See the screenshot:
![image](https://cloud.githubusercontent.com/assets/14052197/24937645/b2e5f744-1f64-11e7-8455-5949503bb2cd.png)
In my PC, COM4 is connected to ESP8266 huzzah. But in the SelectSerialPort dropdown menu, it shows "Silicon Labs".  This is not user friendly. It should display the right board name for the corresponding serial port.

**Comment by liydu** [comment]
This is related with the USB driver that the board come with. We have no way to change by our own. Close it for now.
