### ISSUE TITLE
Manage Libraries - Add .zip library

### ISSUE THREAD

**Issue by shizn** [Microsoft/vscode-arduino#24]

**Comment by czgtest** [comment]
@liydu Can you help to review again?

**Comment by liydu** [comment]
Not many requests seen to ask for this. Let's keep it in Backlog now.

**Comment by czgtest** [comment]
now close it,   If the user has this request, we will consider doing it again.

**Comment by olawalejuwonm** [comment]
Please we need this. I do not know how to add this manually on a mac

**Comment by olawalejuwonm** [comment]
Please 🙏 how do i do this manually,  I need it for my project
