### ISSUE TITLE
Output message is unreadable code on windows10 when run "arduino verify" command

### ISSUE THREAD

**Issue by v-czg** [Microsoft/vscode-arduino#246]
Commands: Arduino - Verify
![image](https://cloud.githubusercontent.com/assets/24933705/25038388/3156a9f2-2131-11e7-9fa6-af75f40da523.png)

Install extenal libarary
![image](https://cloud.githubusercontent.com/assets/24933705/25038479/99cda8dc-2131-11e7-8733-2305a9eba7b1.png)

**Comment by czgtest** [comment]
this issue and #447 belong to the same type of problem
