### ISSUE TITLE
Arduino Libraries Manager has layout issue 

### ISSUE THREAD

**Issue by v-czg** [Microsoft/vscode-arduino#248]
![image](https://cloud.githubusercontent.com/assets/24933705/25038778/f62725d0-2132-11e7-8aa6-3a26067ea606.png)

**Comment by czgtest** [comment]
using the latest vscode version :1.20.1
the default layout site of Libraries Manager work well now.
if user want to adjust the smallest site, it will show like this.
the button all show up and work well
![image](https://user-images.githubusercontent.com/35018765/37072540-0b6e799a-21fd-11e8-92ab-760f17fc357d.png)

**Comment by czgtest** [comment]
this bug can close now.
