### ISSUE TITLE
Azure IoT Integration - Azure IoT certified device detection

### ISSUE THREAD

**Issue by shizn** [Microsoft/vscode-arduino#25]

**Comment by liydu** [comment]
Can provide a `packages.json` or similar configuration file with relevant PID&VID to maintain it.

**Comment by czgtest** [comment]
@liydu Can we close this bug?

**Comment by liydu** [comment]
Ref #27

**Comment by ArthurMa1978** [comment]
What's the integration efforts?
 more like this should move to IoT workbench

**Comment by czgtest** [comment]
If the user has this request, we will consider doing it again.
