### ISSUE TITLE
Add support for wireless serial port.

### ISSUE THREAD

**Issue by yaohaizh** [microsoft/vscode-arduino#264]
Following feature request from #212

**Comment by czgtest** [comment]
@Sneezry  Can you help to investigate how to fix it?

**Comment by czgtest** [comment]
#393 belong to serial port issue too.

**Comment by czgtest** [comment]
this issue will fix with #439

**Comment by gcampbell-msft** [comment]
@yaohaizh We have recently updated the Arduino extension to depend on a new standalone Serial Monitor extension, please upgrade your arduino extension and try out this new feature!

Let us know if it solves your issue or if the issue still persists!
