### ISSUE TITLE
The DevKit README and Arduino Examples will be shown in every instance of VS Code

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode-arduino#311]
Repro steps:
1. Open multiple VS Code instance
2. Connect to DevKit to USB

Actual:
The DevKit README and Arduino Examples will be shown in every instance of VS Code. It is a little annoying. Since I would work on other project with VS Code.

Expect:
Only show DevKit README and Arduino Examples in current active VS Code.

**Comment by liydu** [comment]
Later we will make DevKit extension to take care of it.
