### ISSUE TITLE
grammer highlighting is not work

### ISSUE THREAD

**Issue by yuwzho** [Microsoft/vscode-arduino#323]
After install the newest arduino extension and cpptools extension, the sample code has red underline for `pinMode` and `digitalWrite` for some arduino specific keyword

**Comment by yaohaizh** [comment]
Something related to C++ extension settings: 
https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/FAQ.md#why-do-i-have-red-underlines-everywhere-after-updating-to-the-latest-version
