### ISSUE TITLE
Missing install ST-Link Debug driver

### ISSUE THREAD

**Issue by yuwzho** [Microsoft/vscode-arduino#326]
First time to plug in a Devkit, clink `yes` in VSCode to install devkit package, it miss ST-Link Debug driver

**Comment by stuartaw** [comment]
So, these two issues get closed with zero feedback, refering to each other, as if the answer would be in the other issue? nice style andxu!
Perhaps I could suggest just a small hint as to why this happens?

**Comment by andxu** [comment]
This issue is related into package installation problem of Azure Devkit 3166(https://github.com/Microsoft/AzureIoTDeveloperKit), we have no ways of linking issue in that repository.

**Comment by terrillmoore** [comment]
Link to AzureIoTDevleloperKit is broken when tested on 2017-12-21.  And there is no issue 3166 in https://github.com/Microsoft/azure-iot-developer-kit; and none of the issues in that repo seem to match this description. More info would be appreciated, even if only as a cut/paste.
