### ISSUE TITLE
the output error message doesn't map

### ISSUE THREAD

**Issue by shizn** [Microsoft/vscode-arduino#336]
Issue from dglover@microsoft.com

"my one issue with it is that it doesn't map the errors to the source code as well as it could. and I end up having to use the arduino ide to find the issue then switch back to Code"

**Comment by liydu** [comment]
Put in backlog now for further investigation.

**Comment by czgtest** [comment]
@shizn ,  Can you help to provide more detail for it ?

**Comment by czgtest** [comment]
duplicate with #770
