### ISSUE TITLE
Feature Request: Better GUI

### ISSUE THREAD

**Issue by rei-vilo** [microsoft/vscode-arduino#356]
The GUI of Visual Studio Code is pretty limited. 

Is there a way to implement  

* a dedicated **Arduino** menu, or 
* a floating tool-bar with some buttons for **Build** / **Verify** and **Upload** / **Run**?

**Comment by testforstephen** [comment]
@rei-vilo yes, VSCode have strict limit on GUI layout. it seems we could add some buttons on editor action bar. something like this
![image](https://user-images.githubusercontent.com/14052197/27811785-568afae8-609c-11e7-9700-c8edec287026.png)

**Comment by czgtest** [comment]
Good request, we will investigate how to improve the GUI.

**Comment by rei-vilo** [comment]
A temporary solution is the **Shortcut Menu Bar** [jerrygoyal.shortcut-menu-bar](https://marketplace.visualstudio.com/items?itemName=jerrygoyal.shortcut-menu-bar).

**Comment by robotdad** [comment]
There was a verify and upload button added since this was filed. There are also newer options down in the bottom status bar. I'm closing based on age and that some of these UI suggestions have been taken. Please open a new issue with specific suggestions off the current release if you have additional feedback.

**Comment by rei-vilo** [comment]
See 

+ [Add some API to support GUI customization](https://github.com/Microsoft/vscode/issues/1833) and 
+ [Add an optional configurable toolbar below the menu](https://github.com/microsoft/vscode/issues/41309)

**Comment by robotdad** [comment]
Thank you for those specific pointers.

**Comment by MikeRosoft** [comment]
And... ? "Thank you for those specific pointers; as always, we're going to summarily ignore them, and summarily close any further requests pointing in the same direction"?
