### ISSUE TITLE
Compile Error 'Serial1 not declared in this scope' on ATMega2560 

### ISSUE THREAD

**Issue by PeterSek** [Microsoft/vscode-arduino#368]
Hi, getting error on Mega2560 with Serial1

**error: 'Serial1' was not declared in this scope**
   Serial1.begin(115200);            //WiFi
...
**error: 'Serial1' was not declared in this scope**
   if (Serial1.available() > 0) {
       ^
exit status 1

**My Board Config is:**
{
    "board": "arduino:avr:mega",
    "configuration": "cpu=atmega2560",
    "port": "COM4",
    "sketch": "SensorFarmIOWiFi.ino"
}

**Comment by PeterSek** [comment]
I must be doing something wrong, Just noted that build.options.json shows arduino:avr:uno but i expect it should be mega2560. what is the best/correct way to fix this?
![image](https://user-images.githubusercontent.com/3133073/28117777-15e018fe-6752-11e7-9b05-b34027c41fd9.png)

**Comment by yaohaizh** [comment]
@PeterSek, the vscode arduino extension doesn't use the build.options.json file. Not sure which platform/tools generated this configuration file.  

For this extention, you can set the type in .vscode\arduino.json file or invoke command: "Arduino: Change Board Type" or use the status bar to choose the board type.

**Comment by PeterSek** [comment]
thank you @yaohaizh, I tried both but no luck.
FYI yesterday I did my 1st VSC arduino test using 'uno' board 
I noticed that today setting.json shows 'uno' 
I have updated User Settings but these do not include fqbn (no changes in workspace settings)
Tomorrow I might try changing settings.json fqbn (or should this be updated when I choose board as you described?

![image](https://user-images.githubusercontent.com/3133073/28119287-a0961c50-6757-11e7-86c6-476cd62998a8.png)

**Comment by yaohaizh** [comment]
@PeterSek,  our setting are persisted on the arduino.json, the left one of setting.json. Could you show the content of that file?

**Comment by yaohaizh** [comment]
@PeterSek, you think you might use another extension.  Our extension is from this link: 
https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-arduino#review-details

**Comment by PeterSek** [comment]
@yaohaizh I am using same extension https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-arduino 

here is my arduino.json
![image](https://user-images.githubusercontent.com/3133073/28120411-52f4ff62-675b-11e7-8e12-a5bc7697e483.png)

**Comment by PeterSek** [comment]
@yaohaizh thank you, I think messed things up, getting different error (output bottom of screen)
Will get back to it tomorrow; P

**Comment by testforstephen** [comment]
@PeterSek Looks like you have multiple different arduino extensions installed in your vscode. Note that only these three settings "arduino.path", "arduino.additionalUrls", "arduino.logLevel" are from microsoft arduino extension. Other arduino.xxx settings are not used by our extension. i would suggest you to uninstall other arduino extension first and keep microsoft arduino extension to try again.

**Comment by PeterSek** [comment]
Thanks a lot. I will check it out tommorow, will re install vscode if
required
P

**Comment by PeterSek** [comment]
Hi @testforstephen yes, you are right, there was a non-Microsoft Arduino 022 also installed
Removing fixed the problem
thank you, closing
