### ISSUE TITLE
Configuring board type always fails on win10

### ISSUE THREAD

**Issue by seanchann** [Microsoft/vscode-arduino#379]
hi:
   ```
    vscode version: 1.14.1
    arduino verison: 1.8.3 (download from the  Official home page  of arduino, not  Store's )
    arduino extension version: 0.2.4
    os: win10
   ```
   when configuring board type always not work.

**Comment by yaohaizh** [comment]
@seanchann  Is the behavior similar to #370 ?

**Comment by khaled-hamam** [comment]
If it's the same as #370 the problem was excluding the .VSCODE folder in the settings by mistake, check if you have the same problem
