### ISSUE TITLE
Board/Serial Port settings lost between loads

### ISSUE THREAD

**Issue by rw950431** [Microsoft/vscode-arduino#384]
I'm liking this new Arduino extension but it seems I have to re-select the board and serial parameters each time I load a folder.  Is there a way for VSCode to remember the board  and comm port settings for each project?   
Issue occurs on Windows 10 + VSCode 1.14.2 + Arduino 1.6.5

**Comment by yaohaizh** [comment]
@rw950432, yes, it can. Please refer the readme to see how to persist your settings into the .vscode/arduino.json file.

**Comment by rw950431** [comment]
Thanks- that works except I dont see any way to remember the baud rate and other serial parameters- did I miss that too?

**Comment by czgtest** [comment]
@rw950431  you can set port and board value in the  .vscode/arduino.json file.

like this:
![image](https://user-images.githubusercontent.com/35018765/37016171-e8a218ca-2145-11e8-956c-70fef7579467.png)

**Comment by czgtest** [comment]
@rw950431  is it work ?

**Comment by Sneezry** [comment]
No more feedback more than one week, close.
