### ISSUE TITLE
After laptop wakes up from sleep, Arduino files added to all open VSCodes

### ISSUE THREAD

**Issue by JimWatV1** [Microsoft/vscode-arduino#389]
On Win10 w/Creators Update. (15063)

After restarting a sleeping or hibernating laptop with two instances of VSCode running, .vscode/arduino.json and .vscode/c_cpp_properties.json files have been added to all instances.  And the Arduino Examples file is open along with 
(curiously) C:\Users\<username>\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\README.md

The folders I have open are not Arduino projects to I have to remove the files each time.

**Comment by yaohaizh** [comment]
@JimWatV1  do you have any arduino board connected to the laptop when hibernating?

**Comment by JimWatV1** [comment]
Good point.  Sometimes, I do.  I have a Adafruit Feather HUZZAH with ESP8266 WiFi plugged into the docking station, just for power.  I just hibernated while in the doc, and it didn't add the files.  I'll try to keep track when the files get added.

**Comment by yaohaizh** [comment]
Fixed in PR#391
