### ISSUE TITLE
Automatically configure serial port when only 1 exists

### ISSUE THREAD

**Issue by Weetbix** [Microsoft/vscode-arduino#393]
Great work on this extension, works amazingly well!

Would be nice and slightly less tedious if the extension would automatically select the serial port if there is only one port available. Unless you can think of a reason this would be unwanted behaviour?

**Comment by czgtest** [comment]
@Weetbix  Thanks for your great suggestion, it's good idea to automatically select the serial port and board type.

**Comment by czgtest** [comment]
#439 has the same request.

**Comment by czgtest** [comment]
@ArthurMa1978  this issue is duplicate with #439 , #264

**Comment by czgtest** [comment]
@Weetbix  Now the Arduino extension already support auto detect new plugged in board , but this feather is only work on windows/mac, not support on Ubuntu.
