### ISSUE TITLE
Disable VSCode Board Manager automatic update

### ISSUE THREAD

**Issue by Medeirox** [Microsoft/vscode-arduino#394]
Sometimes the URL's that board manager uses are down, and when this happens the board manager "removes" the already installed boards from the arduino installation.
How can I do VSCode board manager stops from updating and working only with the installed boards?

**Comment by czgtest** [comment]
It's a good idea to support users to customize whether this feature is automatically updated.
we can do this in user settings,  allow user to edit the default settings,  if the value is false , don't upload the board manager,

**Comment by ihere1** [comment]
https://github.com/Microsoft/vscode-arduino/commit/244936ca8e2ac81164c3c3e4df595ab5dc38a774#diff-f1d3d81217c02af7cfec184b0e1d8b14  . For version after this commit, we only auto update board manager if "package_index.json" or a index.json file required in url is missing from Arduino folder. 

Please check following settings if you find it always update board manager on extension start: 1."boardsmanager.additional.urls" setting in preferences.txt folder in Arduino folder.
2. "arduino.additionalUrls" setting in vscode (Press `Ctrl + ,` in Visual Studio Code)
3. Arduino folder where index.json stored. (For example : {User folder}\AppData\Local\Arduino15 on windows)

**Comment by Medeirox** [comment]
I found out there's some problem when the arduino has the libraries
installed inside the "portable" folder instead of the default.
The VSCODE can't find the boards installed.

Em ter, 6 de mar de 2018 02:42, Chen Zhang <notifications@github.com>
escreveu:

**Comment by Sneezry** [comment]
@Medeirox thanks for the feedback. Portable support will be added in v0.2.12. See https://github.com/Microsoft/vscode-arduino/issues/498
