### ISSUE TITLE
Use .html as pop-up welcome page

### ISSUE THREAD

**Issue by liydu** [Microsoft/vscode-arduino#397]
Currently the extension supports `.md` as pop-up welcome page when a user attaches the board to VS Code. To further enrich the experience, we may want to support using `.html` as well.

And currently VS Code cpp is using `.html` for displaying release notes after upgrading.

**Comment by liydu** [comment]
@yaohaizh ,

Filename: `ReleaseNotes.html`

On local folder, the path will be `C:\Users\username\AppData\Local\Arduino15\packages\AZ3166\hardware\stm32f4\1.0.2\ReleaseNotes.html`. So it's in the same folder as `README.md`

**Comment by yaohaizh** [comment]
Fixed in #398
