### ISSUE TITLE
openocd error when trying to debug arduino:avr:pro

### ISSUE THREAD

**Issue by reflog** [Microsoft/vscode-arduino#401]
Hi.
I've created a new VSCode project, opened my INO file (it verifies and uploads correctly), can see serial output, configured the board:
{
    "board": "arduino:avr:pro",
    "configuration": "cpu=16MHzatmega328",
    "port": "COM3",
    "sketch": "emulate_tag_n_bt.ino"
}
But cannot debug:
`Cannot find the OpenOCD from the launch.json debugServerPath property.Please input the right path of OpenOCD`

Any suggestions?

Thanks!

**Comment by yaohaizh** [comment]
@reflog  aduino.avr:pro doesn't have debugger support.

You can check out readme for which boards have debugger capabilities.
