### ISSUE TITLE
[DevKit] The Arduino Example pannel not show up when connect the DevKit

### ISSUE THREAD

**Issue by ArthurMa1978** [Microsoft/vscode-arduino#403]
This is the issue in 0.2.5 which add the treeview for Arduino Example, broke the existing DevKit dev experience.

**Comment by yaohaizh** [comment]
Is the readme showed up? 

For treeview, normally, it is not expand automatically, just a bar on the explorer bottom.

**Comment by sffamily** [comment]
fixed in v0.2.6

**Comment by liydu** [comment]
Should be considered in DevKit extension.
