### ISSUE TITLE
Upload Using Programmer 

### ISSUE THREAD

**Issue by jmsaavedra** [Microsoft/vscode-arduino#407]
Apologies if there is an extension setting that I overlooked, but I'm wondering if there is a way to **Upload Using Programmer**. This available in the Arduino app with either `cmd+shift+U` or by holding shift and clicking the Upload button.

There is also a menu selection for which Programmer I am using (_AVRISP MkII_ currently).

Thanks for any info -

**Comment by icamaster** [comment]
I am also interested in this. Came here to ask for this and found your post.

**Comment by icamaster** [comment]
I think this can be easily fixed by adding here "const args = ["--upload", "--board", boardDescriptor, "--port", dc.port, appPath];" the option "--useprogrammer" as stated here https://github.com/arduino/Arduino/blob/master/build/shared/manpage.adoc .

**Comment by RyanBlace** [comment]
I'd like to see this added too. There will also need to be a way to pick the programmer:

![2017-10-26 09_30_35-](https://user-images.githubusercontent.com/33130663/32065090-8e82553e-ba30-11e7-806c-47a1c5fba985.jpg)

**Comment by juankgp** [comment]
Hi, maybe someone was lucky

**Comment by guilhermezat** [comment]
I really need this. ;-)

**Comment by czgtest** [comment]
I think this is a nice feature, Arduino extension should be support to select "Programmer" in vscode,  just like selecting Board Type or Port

![image](https://user-images.githubusercontent.com/35018765/37015558-f042d34c-2142-11e8-8682-b69ecc63b690.png)

**Comment by czgtest** [comment]
@icamaster  can you send pull request for your change to support programmer ?

**Comment by czgtest** [comment]
vscode-arduino-0.2.15-rc is support to upload using programmer, can you have a try ？
steps:
1.download from here
https://github.com/Microsoft/vscode-arduino/releases/download/v0.2.15-rc/vscode-arduino-0.2.15-rc.vsix
2.open vscode and install vscode-arduino-0.2.15-rc from VSIX
3.Press F1 and select arduino: upload using programmer

**Comment by czgtest** [comment]
the latest vscode arduino is support it now, you can upgrade the version 0.2.15 or later.
