### ISSUE TITLE
How do you guys figure out the sketchbook path?

### ISSUE THREAD

**Issue by nealhnguyen** [Microsoft/vscode-arduino#408]
Hello I'm looking through the code and I don't seem to have a preferences.txt file, so how do you guys figure out the sketchbook path? Do you use the sketch path for the .ino file?

**Comment by liydu** [comment]
@ArthurMa1978 could you answer it?

**Comment by VashJuan** [comment]
I suspect it just looks for the workspace/.vscode/arduino.json file's line
"sketch": "myIncredibleSketch.ino"
to determine the sketch to use. Does that help?

**Comment by VashJuan** [comment]
I can try to figure this out later this week!
