### ISSUE TITLE
Allow end of line to be send using Send Text to Serial Port

### ISSUE THREAD

**Issue by mlewand** [Microsoft/vscode-arduino#409]
Currently there's  no way to insert `\n` char to the Serial port, even if copied and pasted from external source VSCode builtin input will strip it.

Sometimes it's a handy to terminate strings using eol.

**Comment by RyanBlace** [comment]
Ideally 5 options:
1) Send nothing
2) Send \n (LF)
3) Send \r (CR)
4) Send \r\n (CR & LF)
5) Something even cooler but we can't think of it right now.

![image](https://user-images.githubusercontent.com/33130663/32065416-9653710c-ba31-11e7-8b74-0f5eb9dee64e.png)

**Comment by mlewand** [comment]
Ideally I'd like be able simply to input `\n` or `\r` char(s) into the input that is used to collect about-to-be-sent data.

Your suggestion AFAICS is related to being able to set character that serial input should be followed with, which is slightly different. It will allow you to put new lines, but will require you to put each single line separately.

Whereas having the input element that works with new lines, you can put multiline content before you actually send it.

**Comment by liydu** [comment]
Duplicated with #463 as a feature request.
