### ISSUE TITLE
Typical install leads to "Cannot find the OpenOCD from the launch.json debugServerPath property" upon running debug

### ISSUE THREAD

**Issue by joseortiz3** [Microsoft/vscode-arduino#410]
This is your most typical installation pattern. Windows 10, Default Arduino Desktop IDE installed, default VS Code with no other extensions installed (except those installed as dependencies during vscode-arduino's install).

I'm trying to set up VS Code with this extension. I first installed the default arduino IDE as described in "[Get Started with Arduino](https://www.arduino.cc/en/Guide/Windows)".

I then installed default VS Code, and then installed the vscode-arduino extension default from the extension manager built-in to VS Code.

I'm using an Arduino Uno. It works fine with the Arudino Desktop IDE. When I try to use VSCode "debug", the following occurs with configuration "Arduino": "Cannot find the OpenOCD from the launch.json debugServerPath property"

![image](https://user-images.githubusercontent.com/18585219/30297076-56db0cd2-96fb-11e7-877e-2bb2239062eb.png)

No error messages or logs are printed when this occurs.

If OpenOCD were a requirement, it would be listed under [prerequisites](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-arduino). Since it's not, and I followed the installation directions as listed, I'm assuming this is a bug.

The configuration "Arduino" has, as default, the following configuration.
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Arduino",
            "type": "arduino",
            "request": "launch",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "MIMode": "gdb",
            "targetArchitecture": "arm",
            "miDebuggerPath": "",
            "debugServerPath": "",
            "debugServerArgs": "",
            "customLaunchSetupCommands": [
                {
                    "text": "target remote localhost:3333"
                },
                {
                    "text": "file ${file}"
                },
                {
                    "text": "load"
                },
                {
                    "text": "monitor reset halt"
                },
                {
                    "text": "monitor reset init"
                }
            ],
            "stopAtEntry": true,
            "serverStarted": "Info\\ :\\ [\\w\\d\\.]*:\\ hardware",
            "launchCompleteCommand": "exec-continue",
            "filterStderr": true,
            "args": []
        }
    ]
}

```
Side note: npm is not listed as a requirement, but it should be, because it is. The solution to all this might just be the Readme.md is not complete. Also, I do not have Node.js installed, but this was not listed as a prerequisite.

**Comment by yaohaizh** [comment]
The Arduino UNO is not supported for debugging int VSCode Arduino extension. Please see the readme for  which kind of board suports debugging. Let me know if you have any further questions.

**Comment by czgtest** [comment]
please see #446

**Comment by SunboX** [comment]
Same for me with Waveshare Driver Board 😢 (Node MCU 1.0 compatible) Works fine with Arduino IDE

**Comment by afzalmushtaque** [comment]
If anyone else reading this is trying to "Verify"/"Upload" using VSCode instead of Arduino IDE, please open the command palette by pressing the F1 key and select "Arduino: Verify"/"Arduino: Upload".

**Comment by leonbrag** [comment]
I have the same problem with Arduino Uno WiFi rev 2

**Comment by ChuangRoy** [comment]
I have same problem with arduino uno .
but I write the debugger path in launch.json ,but  it  isn't work .

This is my launch.json :
`{
    // 使用 IntelliSense 以得知可用的屬性。
    // 暫留以檢視現有屬性的描述。
    // 如需詳細資訊，請瀏覽: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Arduino",
            "type": "arduino",
            "request": "launch",
            "program": "${file}",
            "cwd": "${workspaceFolder}",
            "MIMode": "gdb",
            "targetArchitecture": "arm",
            "miDebuggerPath": "",
            "debugServerPath": "{workspaceFolder}\\OpenOCD\\bin",
            "debugServerArgs": "",
            "customLaunchSetupCommands": [
                {
                    "text": "target remote localhost:3333"
                },
                {
                    "text": "file \"${file}\""
                },
                {
                    "text": "load"
                },
                {
                    "text": "monitor reset halt"
                },
                {
                    "text": "monitor reset init"
                }
            ],
            "stopAtEntry": true,
            "serverStarted": "Info\\ :\\ [\\w\\d\\.]*:\\ hardware",
            "launchCompleteCommand": "exec-continue",
            "filterStderr": true,
            "args": []
        }
    ]
}`

**Comment by John-WL** [comment]
can anyone explain to me why this issue was closed? Is this issue solved?
