### ISSUE TITLE
Nothing is displayed for 'Arduino Board Configuration'

### ISSUE THREAD

**Issue by brndmg** [Microsoft/vscode-arduino#419]
When I run the 'Arduino Board Configuration' from the ctrl-shift-p or by clicking the board name in the footer, the tab opens with the title but there isn't any content.

The following error is shown in the Developer console.
```
[Embedded Page] Uncaught Invariant Violation: Element type is invalid: expected a string 
(for built-in components) or a class/function (for composite components) but got: object. 
Check the render method of `BoardConfigItemView`. [webview.ts:151]
```
I should mention that I am running Ubuntu 16.04.
Arduino IDE 1.8.4

**Comment by brndmg** [comment]
I have a working fix for this, I will be submitting a PR shortly.

**Comment by sid9102** [comment]
Seeing the same issue on MacOS, please update when this is fixed!

**Comment by Joseph14078** [comment]
Can confirm on Win10 with exact same error.

**Comment by pedzed** [comment]
Can confirm as well for Debian 9.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux testing (buster)
Release:        testing
Codename:       buster
```

**Comment by godrix** [comment]
same error occurs in ubuntu 17.04 =(

**Comment by juankgp** [comment]
I have the same problem I use Ubuntu 16.04, arduino 1.8.4, code Insigner, I testwith the last version code 1.17, a lot of time ago it works but one day nothing, so please help me
