### ISSUE TITLE
Press F5 to build .ino file and deploy to device

### ISSUE THREAD

**Issue by akaroml** [Microsoft/vscode-arduino#42]
Currently pressing F5 while an INO file is opened triggers nothing. The expected behavior is:
1. User press F5
2. Start the build process and show the output window for user to see the build result
3. After build succeeded, upload the binaries to current device

**Comment by czgtest** [comment]
@ArthurMa1978  Can you help to review it again ?

**Comment by ArthurMa1978** [comment]
vs code has different behavior, close it.
