### ISSUE TITLE
Text in serial monitor is encoded.

### ISSUE THREAD

**Issue by AndreyKrupskii** [Microsoft/vscode-arduino#420]
![image](https://user-images.githubusercontent.com/14182602/31046505-3eb47bd2-a602-11e7-980d-20c742df2cae.png)

**Comment by TheKayneGame** [comment]
Is the baud rate in your program and serial monitor the same?

**Comment by andxu** [comment]
Be aware to the baud rate setting at the status bar.

**Comment by AndreyKrupskii** [comment]
It works for me! Thank you, @andxu.

**Comment by yaohaizh** [comment]
Nice, add this issue to the FAQ of the wiki page.

**Comment by ped59430** [comment]
Baud rate made it for me:
Ctrl + Shift + P
Arduino: Change baud rate
I choose 9600, I guess it is the default

**Comment by Xorbit17** [comment]
The baud rate trick did it. Thanks for commenting.
