### ISSUE TITLE
Unable to start debugging for file path contain space

### ISSUE THREAD

**Issue by lirenhe** [Microsoft/vscode-arduino#428]
"Unable to start debugging. Unexpected GDB output from command "-interpreter-exec console "file c:/Users/kdixit/Documents/Visual Studio Code/MXChipApp1/.build/MXCHIP_AZ3166/MXChipApp1.ino.elf"". c:/Users/kdixit/Documents/Visual: No such file or directory."

**Comment by czgtest** [comment]
@lirenhe   have you got this issue solved?  if not, Can you provider more detail about it?

**Comment by Sneezry** [comment]
Maybe related issue: https://github.com/Microsoft/vscode/issues/3667

**Comment by czgtest** [comment]
the version 0.2.12 able to start debugging for file path contain space
