### ISSUE TITLE
Verification always gives an [Error] Exit with code=undefined

### ISSUE THREAD

**Issue by my-poi** [Microsoft/vscode-arduino#429]
Hello!

Verification gives an error:
```
[Starting] Verify sketch - projects/001.ino
[Error] Exit with code=undefined
```
The code is a blink template.

arduino.json
```
{
    "port": "COM6",
    "board": "arduino:samd:mzero_pro_bl_dbg",
    "sketch": "projects\\001.ino",
    "output": "build"
}
```
c_cpp_properties.json
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "C:\\Users\\maciej.tokarz\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\samd\\1.6.16\\cores\\arduino"
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": false,
                "path": [
                    "C:\\Users\\maciej.tokarz\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\samd\\1.6.16\\cores\\arduino",
                    "${workspaceRoot}"
                ]
            },
            "intelliSenseMode": "msvc-x64"
        }
    ],
    "version": 3
```
Settings
```
"arduino.path": "C:/Program Files (x86)/Arduino",
"arduino.logLevel": "verbose"
```
The most interesting thing is that despite the Verify error, Upload works.

Regards,
Maciej

**Comment by my-poi** [comment]
The solution was to reset Windows to factory settings.
M.

**Comment by yoppy-tjhin** [comment]
Hi,

I encounter the same problem, and could not resolve it.
I am using Win 8. How did you actually reset Windows to factory settings?
Thank you for sharing.

**Comment by RJPalombo** [comment]
First time trying this out and I received the same error (on Mac). For me the reason was I copied the settings from the instructions. I commented out all but  _"arduino.enableUSBDetection": true_ and everything is working now. I now see that you are only supposed to use these settings if you want to override the defaults - which for me the defaults work fine.

**Comment by FriedCircuits** [comment]
I get this error on Win10 for both verify and upload.

**Comment by arkadiusz-wieczorek** [comment]
@RJPalombo Exactly the same in the case of Ubuntu 16.04, I've added in User Settings: 
`"arduino.enableUSBDetection": false`

**Comment by alkhimey** [comment]
Just installed Arduino extension and can confirm that I have the same problem.

**Comment by jraviotta** [comment]
On OSX, I get the same error.

**Comment by driedell** [comment]
I was trying on Windows 10 and was getting the same error when using the Arduino IDE downloaded from the Windows 10 app store. But when I downloaded the Arduino IDE directly from https://www.arduino.cc/ and uninstalled the Win10 app store version, it worked.

**Comment by mtzfactory** [comment]
Hi,

I had the same problem in my **Mac**, but now it's working properly. I changed a bit the _settings.json_ file:

```json
{
    "arduino.path": "/Applications",
    "arduino.commandPath": "Contents/MacOS/Arduino",
    "arduino.additionalUrls": "",
    "arduino.logLevel": "info"
}
```

**Comment by jraviotta** [comment]
Seems to be a documentation issue on the ardiuno path. Also, documentation should reflect that the path can be set in settings.jaon and the project vscode.
