### ISSUE TITLE
Identifier is undefined

### ISSUE THREAD

**Issue by dafzor** [Microsoft/vscode-arduino#437]
All Arduino functions in Visual Studio code show underlined in red with the following error:
```file: 'file:///c%3A/Users/daf/Documents/Arduino/ex2_ledseq/ex2_ledseq.ino'
severity: 'Error'
message: 'identifier "pinMode" is undefined'
at: '10,5'
source: ''
```

Adding `#include <Arduino.h>` fixes those error but shows a new ones like:

```file: 'file:///c%3A/Users/daf/Documents/Arduino/ex2_ledseq/ex2_ledseq.ino'
severity: 'Info'
message: 'cannot open source file "stdlib.h" (dependency of "Arduino.h")'
at: '1,1'
source: ''
```
This error shows on two computers I tested, around one to two weeks ago it did not occur. Verification and Upload still work without regardless of the error above.

**Comment by redwarff** [comment]
I am having the exact same problem

**Comment by Kulbhushan-Chand** [comment]
Same problem here.
Is there a way not to write the basic include files in the beginning, just like we do in arduino official IDE?

**Comment by JebinMatthew25** [comment]
Yep exactly, but the code can be uploaded without problems, still it's annoying

**Comment by yaohaizh** [comment]
Duplicate with https://github.com/Microsoft/vscode-arduino/issues/438

Please see the related issue.
