### ISSUE TITLE
Can't access mapped serial port in Azure VM

### ISSUE THREAD

**Issue by ArthurMa1978** [microsoft/vscode-arduino#441]
Repo:
Create a Azure VM
Install the DevKit SDK
Remove to the Azure VM and map the local serial port to the vm

Issue:
The Arduino extension can't upload the fw, but Arduino IDE can.

**Comment by gcampbell-msft** [comment]
@ArthurMa1978 We have recently updated the Arduino extension to depend on a new standalone Serial Monitor extension, please upgrade your arduino extension and try out this new feature!

Let us know if it solves your issue or if the issue still persists!
