### ISSUE TITLE
German umlauts "ä, ü, ö" not showing correct in the output window

### ISSUE THREAD

**Issue by xhizorsz** [Microsoft/vscode-arduino#447]
It looks like this:

`Konfiguration wird geladen...
Pakete werden initialisiert...
Boards werden vorbereitet...
�berpr�fungsvorgang...
Build-Optionen wurden ver�ndert, alles wird neu kompiliert`

**Comment by czgtest** [comment]
it's related to some global language problem.

**Comment by yaohaizh** [comment]
@czgtest  https://github.com/Microsoft/vscode-arduino/commit/00d3fefcead1a95ec1b1ffbb32abc0f1b0a47a82 PR for your reference.

**Comment by czgtest** [comment]
this issue is not repro on now,  00d3fef PR is fix it
