### ISSUE TITLE
Sending text to serial doesn't seem to be working

### ISSUE THREAD

**Issue by Erutan409** [Microsoft/vscode-arduino#448]
When I send text to the serial, nothing happens when in Visual Code using this extension.

However, when I'm in the Arduino IDE, it works; but, only if `newline` is selected from the drop-down.

**Comment by liydu** [comment]
Duplicated with #463 as a feature request.

**Comment by Erutan409** [comment]
Eh, I'm using Visual Micro in Visual Studio now, anyway.

Glad to see it's being address now, though.
