### ISSUE TITLE
[OSX] Running verify switches from vscode space to arduino space

### ISSUE THREAD

**Issue by jpmckearin** [Microsoft/vscode-arduino#453]
It seems that when running verify, Arduino IDE opens which forces OSX to switch from the fullscreen VSCode space to the Desktop space which shows the splash-screen for Arduino IDE. 

https://imgur.com/a/AQ9SX

**Comment by yaohaizh** [comment]
Yes, this is an issue of Arduino IDE on macOS platform. Unfortunately, the official Arduino IDE doesn't provide command without this splash-screen popping up.

**Comment by jpmckearin** [comment]
@yaohaizh this is what I was looking for... I'm not sure how I missed it when searching. https://github.com/Microsoft/vscode-arduino/pull/451
