### ISSUE TITLE
Add support to multi-root workspaces

### ISSUE THREAD

**Issue by nuno407** [Microsoft/vscode-arduino#455]
Please add support to multi-root workspaces as explained [here](https://code.visualstudio.com/docs/editor/multi-root-workspaces). 
If i enter some root project the arduino.json should be loaded with board and port information for instance.
Thank you, nuno407

**Comment by czgtest** [comment]
this issue belong to new feature request

**Comment by czgtest** [comment]
#476 has the same request.
