### ISSUE TITLE
Serial Monitor Question Marks

### ISSUE THREAD

**Issue by amatzen** [Microsoft/vscode-arduino#458]
I have Technology at my school, we are learning developing with Arduino Uno, but the serial monitor in VSCode just prints question marks.

<img width="1680" alt="skaermbillede 2018-01-15 kl 11 59 51" src="https://user-images.githubusercontent.com/10503999/34939366-cc8cf244-f9eb-11e7-9711-360d97b80741.png">

**Comment by yaohaizh** [comment]
@amatzen Please change the serial baud rate to 9600 to match your settings.
