### ISSUE TITLE
add "output" to global user preferences 

### ISSUE THREAD

**Issue by aster94** [Microsoft/vscode-arduino#461]
i think it would be nice to have something like
`"arduino.output": "your_path"`
in the global settings accesible with `Ctrl + ,`

P:S: i don't like to open too much issues, may i be wrong or there is not a way to do the "auto format"?

**Comment by caniggia1** [comment]
You can add for example:
"output": ".build"
to ".vscode/arduino.json" file.

More on this page:
https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-arduino

**Comment by liydu** [comment]
Resolved.

**Comment by aster94** [comment]
@caniggia1  you misunderstand the question, or i didn't understand it
i know i can add the output in the LOCAL ".vscode/arduino.json" file, but i am suggestion this is not the best way to do it

I am suggesting that it would be better to have the possibility to choose once the built path in the GLOBAL  user preferences accessible with Ctrl + , 
if i didn't misunderstand please reopen the issue
