### ISSUE TITLE
auto format

### ISSUE THREAD

**Issue by ErmesT** [Microsoft/vscode-arduino#466]
It would be nice to auto-format Arduino code with conventional alt+shift+F

At the moment the following error is reported:
Sorry, but there is no formatter for 'cpp'-files installed.

**Comment by czgtest** [comment]
Please reference https://github.com/Microsoft/vscode-cpptools/issues/1232

**Comment by Sneezry** [comment]
@ErmesT format still doesn't work on your side till now? It works fine on my side.

**Comment by Sneezry** [comment]
No more feedback more than one week, close.
