### ISSUE TITLE
Can't upload, no serial line set, Adafruit Trinket Pro

### ISSUE THREAD

**Issue by MrTheSaw** [Microsoft/vscode-arduino#468]
I'm trying to upload to an Adafruit Trinket Pro 5v via the USB port. This works with the Arduino IDE.
In vscode, I can't select a useful serial port. The one the other IDE uses is /dev/cu.usbserial-A6008bj4, but all I see in vscode is the two bluetooth devices.

System: macOS 10.13.3
vscode: 1.20.1
Arduino: 1.8.5
Adafruit AVR Boards: 1.4.12

**Comment by czgtest** [comment]
Yes, you can add port in  arduino.json file, like this.

{
    "sketch": "GetStarted.ino",
    "port": "/dev/cu.usbserial-A6008bj4",
    "board": "AZ3166:stm32f4:MXCHIP_AZ3166",
    "configuration": "upload_method=OpenOCDMethod"
}

**Comment by czgtest** [comment]
@MrTheSaw  have you resolved this issue ?

**Comment by MrTheSaw** [comment]
Well, adding a line to json worked, but is less than awesome.
