### ISSUE TITLE
Encoding problem ?

### ISSUE THREAD

**Issue by vaine4** [Microsoft/vscode-arduino#469]
![image](https://user-images.githubusercontent.com/26749794/36395922-ea66b548-15bb-11e8-9297-3850ad326e79.png)
![image](https://user-images.githubusercontent.com/26749794/36395933-fbecce2e-15bb-11e8-94df-a1a3c9f8b399.png)

Everything in the screenshot. I don't know if it's my configuration or the extension. I'm just sending 0 in the serial input

**Comment by czgtest** [comment]
the same issue in vscode. 
https://github.com/Microsoft/vscode/issues/3550

**Comment by czgtest** [comment]
#447
