### ISSUE TITLE
Unable select board configuration when the folder in Onedrive

### ISSUE THREAD

**Issue by vphuoc** [Microsoft/vscode-arduino#471]
There is no issue if the arduino file outside Onedrive folder. But when I sync it to Onedrive by copping it to Onedrive folder. Then I cannot select the board configuration and can not compile it.

Note that I enabled the File on demand setting in Onedrive app. There is also no issue if the arduino path contains space.

**Comment by czgtest** [comment]
@vphuoc Thanks, this issue will be fix next.

**Comment by czgtest** [comment]
this is repro step:
1.copy a project to OneDrive
2.use vscode to open the project
3.select the board type on the bottom of toolbar
verify cannot select the board configuration

**Comment by Sneezry** [comment]
@vphuoc OneDrive had removed Arduino config file for you to save space. You can require OneDrive always to keep your Arduino file on your machine. See https://github.com/Microsoft/vscode/issues/35433#issuecomment-337382621

**Comment by czgtest** [comment]
resolved the problem by turning off Files On-Demand OneDrive feature.  http://www.intowindows.com/what-is-onedrive-files-on-demand-feature/
