### ISSUE TITLE
Enrich device develop experience

### ISSUE THREAD

**Issue by chyuanmsft** [microsoft/vscode-arduino#474]
There might be some improvements on following aspects:
Provide better IntelliSense and Library management experience
Provide well-structured documents and sample code
Provide more project templates for different purpose
Improve experience for developing big/complex project

**Comment by czgtest** [comment]
we will consider improving the extension.Thank you for your valuable suggestions.

**Comment by czgtest** [comment]
should sync with Chaoyi Yuan about more detail for improvements

**Comment by elektronikworkshop** [comment]
Hi, I'm currently implementing the auto IntelliSense feature, see my comment on #438 and others.

**Comment by robotdad** [comment]
This looks like a list of things from the previous project team. I think many of these are tracked by other issues, including the one @elektronikworkshop mentions. Please reactivate if I have misunderstood.
