### ISSUE TITLE
Set the include path automatically when create the new project.

### ISSUE THREAD

**Issue by ArthurMa1978** [Microsoft/vscode-arduino#484]
_From @ArthurMa1978 on March 7, 2018 4:5_

_From @ArthurMa1978 on January 29, 2018 9:10_

https://stackoverflow.com/questions/47401731/issues-setting-up-mxchip-vscode-arduino-mx3166-environment-on-mac/47448652#47448652

_Copied from original issue: Microsoft/devkit-sdk#736_

_Copied from original issue: Microsoft/vscode#45172_

**Comment by ArthurMa1978** [comment]
This will be fixed in the Arduino Extension

**Comment by czgtest** [comment]
this issue already fix,  after select board config,  the include path automatically add in cpp json


![image](https://user-images.githubusercontent.com/35018765/45018723-399f7a00-b05d-11e8-9d66-5518866e0ce7.png)
