### ISSUE TITLE
If open 2 instances and only one set the "output", both of them are failed when compile

### ISSUE THREAD

**Issue by v-fional** [Microsoft/vscode-arduino#494]
**Steps:**
1. Launch 2 instances from Arduino Examples, such as GetStarted and ShakeShake
2. Set the output parameter for one instance;  for another, do not set
3. Then try to verify this 2 instances

**Expected:**
1. Not sure the Arduino extension support this scenario or not.

**Actual:**
1. Both of them failed, please refer to the following screenshot
![image](https://user-images.githubusercontent.com/15977880/37195485-dcf2b212-2327-11e8-9739-1fa15034aec7.png)

**Comment by czgtest** [comment]
this issue is not repro on , try to run "Arduino:verify" on the same time for 2 instances, it can verify pass.

![image](https://user-images.githubusercontent.com/35018765/37263101-796f6bce-25e1-11e8-8ceb-39283901970a.png)
