### ISSUE TITLE
Unable to add '\r\n' when sending text to serial monitor

### ISSUE THREAD

**Issue by lirenhe** [Microsoft/vscode-arduino#497]

**Comment by czgtest** [comment]
we can select "Both NL & CR" or "No Line ending" now

![image](https://user-images.githubusercontent.com/35018765/38123389-57a5995c-340d-11e8-9b10-f4b52e8dbf0e.png)

**Comment by vishnumaiea** [comment]
![image](https://user-images.githubusercontent.com/10383395/121816071-1aff5080-cc97-11eb-9a3d-159cd8de37a7.png)

The line ending character option appear to be missing from my VS Code status bar when then serial monitor is active. Am I missing something? Couldn't find anything related to this at the configurations.

**Comment by MarcoRBosco** [comment]
> ![image](https://user-images.githubusercontent.com/10383395/121816071-1aff5080-cc97-11eb-9a3d-159cd8de37a7.png)
> 
> The line ending character option appears to be missing from my VS Code status bar when the serial monitor is active. Am I missing something? Couldn't find anything related to this at the configurations.

Same issue:

![image](https://user-images.githubusercontent.com/62314876/124926040-5fafaa80-dffd-11eb-87b4-f56c2a32b4cc.png)

System: Ubuntu 20.04.2 LTS
VS Code: 1.57.1
Arduino plugin: 0.4.3
