### ISSUE TITLE
Arduino integration - Export binary

### ISSUE THREAD

**Issue by shizn** [Microsoft/vscode-arduino#5]

**Comment by caniggia1** [comment]
HI
I didn't find this option, so i tought i'll go to AppData Temp folder and copy from there .bin, .elf, .cpp or whatever file i need.
But Temp folder is deleted immediately after compile.

Then i've managed to get debuger working for STM32103.
I realized that the .build folder is copied to source folder and i can get all the files from there (.bin, .elf, .cpp,...).
I can live with that, but i need working debuger and device to be connected.

It would be nice if there would be some setting to put .build folder into source folder when you choose Verify or Upload.
Something like this:
// copy .build folder to souce folder after compile (Verify or Upload)
"arduino.buildFolder": "enabled",

BR
caniggia

**Comment by yaohaizh** [comment]
@caniggia1  You can set the output folder in the arduino.json.  You can see the PR here: https://github.com/Microsoft/vscode-arduino/pull/378/files

**Comment by caniggia1** [comment]
Perfect!
That's what i was looking for.

Thanks
caniggia
