### ISSUE TITLE
Board manager can not list board version

### ISSUE THREAD

**Issue by ihere1** [Microsoft/vscode-arduino#520]
![image](https://user-images.githubusercontent.com/20485730/38608284-80b7ca6e-3dad-11e8-8037-e1260a44e508.png)

**Comment by czgtest** [comment]
Board Manager can list the board version now, please install vscode-arduino 1.2.13
![image](https://user-images.githubusercontent.com/35018765/39031787-d67947ac-449c-11e8-8cfc-a33697faccdc.png)
