### ISSUE TITLE
#include errors detected - Tag Parser.

### ISSUE THREAD

**Issue by Craix** [Microsoft/vscode-arduino#525]
VS Code info:
Version 1.22.2
Shell 1.7.12
Architecture x64 
Os Windows 8.1 

Try to use VS Code with Aruino IDE and wemos d1 mini (ESP8266) and i got a problem. 

`#include errors detected. Please update your includePath. IntelliSense features for this translation unit (C:\\...) will be provided by the Tag Parser.`

**Comment by czgtest** [comment]
@Craix  Can you find the answer in the following article?
https://github.com/Microsoft/vscode-cpptools/issues/1041

**Comment by Sneezry** [comment]
Duplicate with https://github.com/Microsoft/vscode-arduino/issues/438
