### ISSUE TITLE
TestingOpen output on the serial monitor

### ISSUE THREAD

**Issue by f6fvy** [Microsoft/vscode-arduino#530]
What's the point of sending "TestingOpen" in the Serial monitor window after opening it ?

It look me a while to understand it was coming from this plugin (after digging the sources), and not from my Arduino code !

**Comment by Sneezry** [comment]
TestingOpen is for test if serial port open successfully.

**Comment by f6fvy** [comment]
I understand, but maybe it would be suitable to make this text sending optional (and/or allow its modification by the user).

**Comment by Sneezry** [comment]
That makes sense. I will add a new setting to allow user to disable it.

**Comment by czgtest** [comment]
this fix work on version 0.2.15

**Comment by Sneezry** [comment]
We have added a new config (`arduino.disableTestingOpen`) to disable auto testing open in v0.2.15, see https://github.com/Microsoft/vscode-arduino#options
