### ISSUE TITLE
VSCode insider has been upgraded to node.js >8.0 

### ISSUE THREAD

**Issue by yaohaizh** [Microsoft/vscode-arduino#534]
This will have breaking changes on the native module on vscode arduino. 

Either update the built depending binary or using new addon mechanism from node.js 8.0 to resolve this issue. https://nodejs.org/api/n-api.html

**Comment by yaohaizh** [comment]
@ArthurMa1978 @lirenhe

**Comment by Sneezry** [comment]
VS Code reverted node from 8.0 to 7.9

https://github.com/Sneezry/vscode-version-watcher#readme
