### ISSUE TITLE
Any command can't be found

### ISSUE THREAD

**Issue by r3d9u11** [Microsoft/vscode-arduino#540]
Hi. I have VSCode 1.22.2 and installed extension "vscode-arduino" via extension manager. But any command "Arduino: *" will be crashed. For example: "Arduino: Initialize" will rise exception "command 'arduino.initialize' not found". What I'm doing wrong?

**Comment by czgtest** [comment]
Arduino IDE is required. Please install it from here.
https://www.arduino.cc/en/main/software#download

**Comment by r3d9u11** [comment]
@czgtest yes, it's installed (unpacked from tar.xz, I'm on Linux Mint), latest version. also setting.json and arduino.json configured, too. (but latest version of arduino ide haven't subdirectory bin and scriptbrun-arduini.sh)

**Comment by r3d9u11** [comment]
[development](https://github.com/Microsoft/vscode-arduino#development) version works fine
