### ISSUE TITLE
serial monitor can't decode data

### ISSUE THREAD

**Issue by r3d9u11** [Microsoft/vscode-arduino#546]
Hi. Why serial monitor can't decode input data?
vscode serial monitor:
![1](https://user-images.githubusercontent.com/15020827/39619728-82b4d76c-4f91-11e8-8f49-9c9c7d7d40f3.png)

Arduino IDE serial monitor:
![123](https://user-images.githubusercontent.com/15020827/39619747-8cc7799e-4f91-11e8-9801-266c88d5a768.png)

I've changed baud rate via Ctrl+P->Arduino: Change Baud Rate

Thanks.

**Comment by r3d9u11** [comment]
Ok, I changed Baud Rate again with started Serial Monitor and it's solved my problem.

Can this value be defined somewhere at configuration (for example in arduino.json or settings.json) and be overwrited at when project is opened?

**Comment by czgtest** [comment]
Now it is not support to define it at configuration
