### ISSUE TITLE
Debug Can't Find .elf File

### ISSUE THREAD

**Issue by atrantan** [Microsoft/vscode-arduino#560]
Got the same issue as mentioned here https://github.com/Microsoft/vscode-arduino/issues/357. It happens when multiple .cpp files are colocated with my single .ino file.

**Comment by czgtest** [comment]
@atrantan  ，do you try the solution of #357 ?

**Comment by atrantan** [comment]
@czgtest Specifying the `sketch` value in the `arduino.json` file does not fix the problem. To overcome the problem, I have to create subfolders to put my `.cpp` files and let the `.ino` file in the root folder.
