### ISSUE TITLE
Arduino IDE appears when uploading or verifying Arduino .ino file 

### ISSUE THREAD

**Issue by NilsMinor** [Microsoft/vscode-arduino#561]
When trying to verify or upload a sketch on mac the Arduino IDE starts for a second and closes when verified or uploaded. But the focus is still on the Arduino IDE not in Visual Code anymore, so I have to switch my screen back to VS.

**Comment by czgtest** [comment]
this is by design on Mac, this issue is not repro on Windows/Ubuntu.
