### ISSUE TITLE
Support of intellisence for library Wire(sam)

### ISSUE THREAD

**Issue by R3D9477** [microsoft/vscode-arduino#563]
Hi. I'm tried to add Wire library for Arduino Due, and for this board available Wire(sam) library.
![1](https://user-images.githubusercontent.com/15020827/40164418-25856242-59c2-11e8-8efc-287e7b770fd7.png)
It will automatically add to c_cpp_properties.json only one path to directory of file Wire.h, but all other dependencies (twi.h, variant.h, sam.h, etc.) of this library must be defined manually (to support inellisence). Can it be fixed (if this behavior depends on vscode-arduino)?

Thanks.

**Comment by adiazulay** [comment]
IntelliSense auto-generation has been added in v0.4.0. If you're having any problems with IntelliSense please open a new issue.
