### ISSUE TITLE
Board definition on Atmega 2560 memory reporting issue

### ISSUE THREAD

**Issue by MrBambix** [Microsoft/vscode-arduino#564]
Hi,

Seems the board definition for an 2560 AVR board is not right, cannot upload a 72k sketch allthough 256k is possible...

regards,
Leo

**Comment by MrBambix** [comment]
Sketch uses 74776 bytes (231%) of program storage space. Maximum is 32256 bytes.
Global variables use 2880 bytes (140%) of dynamic memory, leaving -832 bytes for local variables. Maximum is 2048 bytes.
===error ||| Sketch too big; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing it. ||| []

**Comment by MrBambix** [comment]
Board is correctly set to 2560 btw

**Comment by czgtest** [comment]
@MrBambix  Can you try to upload your sketch on Arduino IDE ?  is it work ?

**Comment by MrBambix** [comment]
Hi,


Yes it is not a code problem it is definitely the board definitions reporting the available memory on an atmega 2560 board as too low. Sketch works fine on the Arduino IDE, compiles, uploads and Arduino IDE is reporting available memory on the 2560 just fine.

 

Thanks for looking into this.

 

Regards

Leo

 

Van: Chen Zhang <notifications@github.com> 
Verzonden: donderdag 31 mei 2018 12:04
Aan: Microsoft/vscode-arduino <vscode-arduino@noreply.github.com>
CC: MrBambix <l.deblaauw@chello.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [Microsoft/vscode-arduino] Board definition on Atmega 2560 memory reporting issue (#564)

 

@MrBambix <https://github.com/MrBambix>  Can you try to upload your sketch on Arduino IDE ? is it work ?

**Comment by czgtest** [comment]
@MrBambix ,  the board definition for an 2560 AVR board is in board.txt file of package folder. 
For Windows, the default path is C:\Users\{UserName}\AppData\Local\Arduino15\packages\emoro\hardware\avr\3.2.2\boards.txt.


Both Arduino IDE and VSCode Arduino Extension will use the same board defination when upload.

So please check if you have select the right board in Arduino Extension and use the same board definition with Arduino IDE.

![image](https://user-images.githubusercontent.com/35018765/41021540-555c8cf2-6999-11e8-90bc-a150d1cdc15b.png)

**Comment by czgtest** [comment]
@MrBambix  any update from you ?
