### ISSUE TITLE
Where I found the .hex file?

### ISSUE THREAD

**Issue by juloko** [Microsoft/vscode-arduino#572]
I'm not coding for hardware, at this project I just doing the simulation. So I need the .hex file to insert them at simulator. But was not encountered in terminal logs.

**Comment by juloko** [comment]
I already found at #367. This shoud works at first:


In the arduino.json file put:
`"output": ".\\bin"`

But I have to remove all that I made, removing the folder ".vscode". Settings and run the command:
`"Arduino: Initialize"`

**Comment by AnielShri** [comment]
@juloko : Thanks! Was also looking for the output .hex files; your second comment was quite useful

**Comment by Zoldyck99** [comment]
> I already found at #367. This should works at first:
> 
> In the arduino.json file put:
> `"output": ".\\bin"`
> 
> But first, I had to remove all that I made, removing the folder ".vscode". Settings and run the command:
> `"Arduino: Initialize"`

This worked for me too, much thanks.
