### ISSUE TITLE
i verify and revived this error :Exit with code=undefined

### ISSUE THREAD

**Issue by Alisparrow2000** [Microsoft/vscode-arduino#577]
![screenshot 25](https://user-images.githubusercontent.com/39906491/40913237-349b6a92-6809-11e8-9eeb-898b7ddcb309.png)
help help
don't know what to do ????

**Comment by Sneezry** [comment]
Did you install Arduino IDE? If yes, did you install it from Windows App Store?

**Comment by Alisparrow2000** [comment]
yes i installed arduino IDE .no i installed from arduino;s web site

**Comment by Sneezry** [comment]
This error usually appears when the extension cannot find Arduino IDE. The extension looks for Arduino IDE in two places:

1. `arduino.path` in user settings of VSCode
2. default path of Arduino IDE. For Windows, the default path is `C:\Program Files (x86)\Arduino`.

So please check if you have set an incorrect Arduino path in VSCode user settings (open VSCode, **File** - **Preferences** - **Settings**). If you didn't set `arduino.path` in VSCode user settings, check if Arduino IDE is installed in `C:\Program Files (x86)\Arduino`.

**Comment by Alisparrow2000** [comment]
i checked every thing you said but the issue didnot solve

**Comment by eknowlton** [comment]
I get this issue as well, but on mac. I may be configuring it wrong.

I've managed to get it working on Mac with:

```
{
    "arduino.path": "/Applications/Arduino.app",
    "arduino.commandPath": "Contents/MacOS/Arduino",
}
```

**Comment by motycakjan** [comment]
Hi, this setting works for me, where the _C_Cpp.intelliSenseEngine_ was the main reason of my issue. 

`{
    "arduino.path": "/Applications",
    "arduino.commandPath": "Contents/MacOS/Arduino",
    "arduino.additionalUrls": "",
    "arduino.logLevel": "info",
    "C_Cpp.intelliSenseEngine": "Tag Parser"
}`

**Comment by fengpakho** [comment]
I don't understand.


On 2018-06-25 04:51 , motycakjan<mailto:notifications@github.com> Wrote:


Hi, this setting works for me, where the C_Cpp.intelliSenseEngine was the main reason of my issue.

{ "arduino.path": "/Applications", "arduino.commandPath": "Contents/MacOS/Arduino", "arduino.additionalUrls": "", "arduino.logLevel": "info", "C_Cpp.intelliSenseEngine": "Tag Parser" }

**Comment by fengpakho** [comment]
Don't send this mail to me





On 2018-06-25 04:51 , motycakjan<mailto:notifications@github.com> Wrote:


Hi, this setting works for me, where the C_Cpp.intelliSenseEngine was the main reason of my issue.

{ "arduino.path": "/Applications", "arduino.commandPath": "Contents/MacOS/Arduino", "arduino.additionalUrls": "", "arduino.logLevel": "info", "C_Cpp.intelliSenseEngine": "Tag Parser" }

**Comment by motycakjan** [comment]
I did not send you this email, this is notification email from this channel.

**Comment by eknowlton** [comment]
Lmao

**Comment by czgtest** [comment]
@Alisparrow2000 , the error was caused by command path,   please remove "arduino.commandPath": "run-arduino.bat" in your vscode settings.  restart vscode after change.

arduino.commandPath" is  only option setting, the default value is "C:/Program Files (x86)/Arduino/arduino_debug.exe" on windows ,  so we can not set it .
if you set  "arduino.commandPath": "run-arduino.bat", you should put "run-arduino.bat" file in path "/Program Files (x86)/Arduino" , then run arduino command,  the error will resolve.

**Comment by Desertgeek** [comment]
I ran into the same problem in my Arduino UNO project that I am developing on my MacBook Pro. I can confirm that the suggestion offered by eknowlton above works and allows the package index to update successfully. I also incorporated the suggestion by motycakjan re: the intellisense engine.

**Comment by human2010** [comment]
@Alisparrow2000 Is your problem solved? I also encountered the same problem, please help!

**Comment by Josh-BI-UK** [comment]
> ![screenshot 25](https://user-images.githubusercontent.com/39906491/40913237-349b6a92-6809-11e8-9eeb-898b7ddcb309.png)
> help help
> don't know what to do ????
==========================================
I had the same issue using windows 10 and resolved it as follows:


1) In Visual Studio Code, click **File > Preference > Settings**.

2) Type “Arduino” in the search textbox; the Arduino settings page should display.

3) In the field entitled [**Arduino: Command Path**] simply type in "**_arduino_debug.exe_**", nothing more.

I found that if I typed in the full path, VSCode would prefix the base file path again, automatically, ending up with an incorrect path like this;

C:\Program Files (x86)\Arduino\C:\Program Files (x86)\Arduino\arduino_debug.exe

Simply using "**_arduino_debug.exe_**", resolved the problem for me.

![arduino_bat_error](https://user-images.githubusercontent.com/59780902/78552437-67334300-77ff-11ea-8ed4-4f3d51e988b3.PNG)

**Comment by Akshay1595** [comment]
> > ![screenshot 25](https://user-images.githubusercontent.com/39906491/40913237-349b6a92-6809-11e8-9eeb-898b7ddcb309.png)
> > help help
> > don't know what to do ????
> > ==========================================
> 
> I had the same issue using windows 10 and resolved it as follows:
> 
> 1. In Visual Studio Code, click **File > Preference > Settings**.
> 2. Type “Arduino” in the search textbox; the Arduino settings page should display.
> 3. In the field entitled [**Arduino: Command Path**] simply type in "**_arduino_debug.exe_**", nothing more.
> 
> I found that if I typed in the full path, VSCode would prefix the base file path again, automatically, ending up with an incorrect path like this;
> 
> C:\Program Files (x86)\Arduino\C:\Program Files (x86)\Arduino\arduino_debug.exe
> 
> Simply using "**_arduino_debug.exe_**", resolved the problem for me.
> 
> ![arduino_bat_error](https://user-images.githubusercontent.com/59780902/78552437-67334300-77ff-11ea-8ed4-4f3d51e988b3.PNG)

This worked for me as well! THanks
