### ISSUE TITLE
Upload Using a Status Bar Button

### ISSUE THREAD

**Issue by momiccioli** [Microsoft/vscode-arduino#582]
How do I get a button on the Status Bar for "Arduino Upload"?  I use this all the time as I would expect most do.  This should be there by default.

**Comment by czgtest** [comment]
@momiccioli now you can upload using command "Arduino:upload" in the Command Palette (F1 or Ctrl + Shift + P) ,  we not add button in status bar for uploading.

**Comment by momiccioli** [comment]
I realize I can do that but still want to add to the status bar.  I use the upload command more than any other when developing.  Its too bad to have to go through multiple actions for something that should be able to do in a single click.

**Comment by sstaub** [comment]
I think there should be two buttons, one for upload and one for verify.

**Comment by czgtest** [comment]
you can see verify and upload button in action bar when select a .ino file



![image](https://user-images.githubusercontent.com/35018765/51448259-3b45b200-1d60-11e9-88ea-053bf779ab11.png)
