### ISSUE TITLE
Select serial port option is not opening neither the serial monitor.

### ISSUE THREAD

**Issue by heyAyushh** [Microsoft/vscode-arduino#590]

**Comment by czgtest** [comment]
@heyAyushh   do you use vscode-insiders ?   now vscode work well for it.

**Comment by heyAyushh** [comment]
yes vscode insiders

**Comment by czgtest** [comment]
VSCode insider has been upgraded to node.js >8.0 , This will have breaking changes on the native module on vscode arduino.  we will fix this issue next.  
@heyAyushh  vscode stable work well now, you can use vscode arduino on stable version to continue your work.

**Comment by czgtest** [comment]
#596  is duplicate with this issue

**Comment by czgtest** [comment]
This issue is resolved in the latest VSCode insider now.
