### ISSUE TITLE
"Verifying" is misspelled in the status message in the status bar

### ISSUE THREAD

**Issue by xxaxdxcxx** [Microsoft/vscode-arduino#591]
![Picture showing status message "verifing"](https://user-images.githubusercontent.com/18105223/41545382-0b835e36-72e9-11e8-8b7e-5209a647833c.png)

As shown here, the status message is misspelled.

**Comment by czgtest** [comment]
@xxaxdxcxx  Thanks a lot for your feedback, will correct it in the next release

**Comment by czgtest** [comment]
fix work on v0.2.18
