### ISSUE TITLE
ST-Link upload - "Please specify the upload serial port"

### ISSUE THREAD

**Issue by ChriD** [Microsoft/vscode-arduino#595]
ST-Link upload does not work.
It always wants to have a com port even if upload Method is set to ST-Link 

```
{
    "board": "STM32:stm32:Nucleo_32",
    "configuration": "pnum=NUCLEO_L432KC,upload_method=STLink,xserial=generic,usb=none,opt=osstd",
    "sketch": "test.ino"
}
```

ST-Link upload works well in the Arduino IDE

**Comment by czgtest** [comment]
@ChriD ,  I don't have enough knowledge about st-link upload,  do you mean if upload method is set to ST-Link,  it is not specify the port, right?

**Comment by ChriD** [comment]
Correct! Is upload Method "ST-Link" is chossen there is no need for a com port

**Comment by czgtest** [comment]
Now vscode arduino is not support for ST-Link upload,  but it is a good feature request, Thanks for your feedback!

**Comment by svelmurugan92** [comment]
Hi, Any update on this?

**Comment by monte-monte** [comment]
@czgtest please add ability to upload using ST-Link. Without it we can't use vscode-arduino with arm based boards like STM32, on NRF5.

**Comment by svelmurugan92** [comment]
@monte-monte  You can just specify a dummy serial port and upload via ST-link

**Comment by monte-monte** [comment]
@svelmurugan92 could you please explain how to do it, or maybe provide a link to a tutorial?
