### ISSUE TITLE
COM port issue

### ISSUE THREAD

**Issue by lamqhoang** [Microsoft/vscode-arduino#596]
I have issues with the COM port recently. 
The COM port list does not show up when I click on the "Select Serial Port". I can set the COM port in the setting json and upload to Arduino board without issue. But if I try to open the port, the error message below show up.

> Failed to open serial port COM4 due to error: + TypeError: Cannot read property 'close' of null

![image](https://user-images.githubusercontent.com/12744859/41659261-fc16b6d8-74c2-11e8-8f3a-2b232299ec54.png)
VScode and arduino extension are updated to latest version. The COM port is not in used

**Comment by czgtest** [comment]
@lamqhoang  VSCode insider will repro on this issue, Can you use VSCode stable ? 

VSCode insider has been upgraded to node.js >8.0 , This will have breaking changes on the native module on vscode arduino. we will fix this issue next.

**Comment by czgtest** [comment]
The Nodejs of VSCode insider is reverted to 7.9, so it work well now.

**Comment by kjcolley7** [comment]
I believe this issue is present again in recent VSCode Insiders versions. Happens to me on 1.31.0-insider for Mac.

Snippet from Developer Tools:

```
TypeError: Cannot read property 'close' of null
	at Object.<anonymous> (bindings.js:27)
	at Object.<anonymous> (bindings.js:46)
	at Module.t._initNodeRequire.r._compile (loader.js:721)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:722)
...
```

This exception is generated from the node-usb-native library.

**Comment by Sneezry** [comment]
@kjcolley7 this issue has been fixed with https://github.com/Microsoft/vscode-arduino/pull/731, and you can use Arduino extension in insiders with next release.

**Comment by bluefate** [comment]
Getting the error in latest insiders version.
Failed to open serial port COM3 due to error: + TypeError: Cannot read property 'close' of null

**Comment by doddydigitaldesign** [comment]
I'm having the same error as @bluefate .
VSCode-Insiders version: 1.36.0

**Comment by q10359443** [comment]
![image](https://user-images.githubusercontent.com/52553001/60692944-d85d6700-9f0a-11e9-9e3e-3fa51ecdb58f.png)

**Comment by q10359443** [comment]
I found the same mistake
VSCode-Insiders version: 1.36.0-insider
![image](https://user-images.githubusercontent.com/52553001/60693075-65082500-9f0b-11e9-9980-7edb903204c8.png)

VSCode  version: 1.36.0
![image](https://user-images.githubusercontent.com/52553001/60693084-6d606000-9f0b-11e9-8325-2676e5805a60.png)

**Comment by q10359443** [comment]
@lamqhoang @czgtest

**Comment by j3rrey** [comment]
Newest VSCode and Arduino plugin.
I'm not able to choose the correct port.
In the Arduino Ide everything works as expected
![Screen Shot 2019-07-05 at 12 59 56](https://user-images.githubusercontent.com/5716777/60718430-e8824000-9f24-11e9-9e6d-f25ac6da0ce9.png)

**Comment by rido-min** [comment]
same here

**Comment by viniciusczanini** [comment]
Have anyone found the solution for this issue?

**Comment by rido-min** [comment]
rollback VSCode to 1.35

**Comment by viniciusczanini** [comment]
Thank you very much, rollback to 1.35 did the trick!

Here's the link if anyone need:
https://code.visualstudio.com/updates/v1_35

**Comment by danieldiasm** [comment]
Yeah, 1.35 User worked out for me too. Thanks!!

**Comment by DanwithArduino** [comment]
1.36 generates no response when trying to change serial port, but 1.35 and 1.34 crashes the arduino extension when trying to change the port.

**Comment by huba71** [comment]
Unfortunately 1.40 breaks the com port again. 1.39.2 seems to work. (on Mac OSX at least)

**Comment by gcurtis79** [comment]
Still getting this with VSCode Windows and Linux:

VSCode: 1.43.1
Arduino: 0.2.29

It worked fine a couple weeks ago...

**Comment by Mechanikerlegion511** [comment]
ВОТ зачем делать обновления после которых не чего не работает?????????????????
