### ISSUE TITLE
Serial Monitor as a standalone extension

### ISSUE THREAD

**Issue by stigbjorlykke** [microsoft/vscode-arduino#598]
It should be possible to install/use the Serial Monitor as a standalone extension and make vscode-arduino depend on this. The Serial Monitor is useful for more than Arduino development and the ```<Select Programmer>``` and ```<Select Board Type>``` in the Status Bar is not applicable in this environments.

**Comment by fengpakho** [comment]
？




On 2018-06-25 03:10 , Stig Bjørlykke<mailto:notifications@github.com> Wrote:


It should be possible to install/use the Serial Monitor as a standalone extension and make vscode-arduino depend on this. The Serial Monitor is useful for more than Arduino development and the and in the Status Bar is not applicable in this environments.

**Comment by czgtest** [comment]
It's a great piece of advice,  Thank you for your feedback.

**Comment by peter73421** [comment]
any progress on this

**Comment by danpeig** [comment]
Agree!

**Comment by lewisxhe** [comment]
Agree! +1

**Comment by robotdad** [comment]
Interesting suggestion, I agree it is useful in other scenarios.

**Comment by gcampbell-msft** [comment]
@stigbjorlykke We have taken your advice and the serial monitor is now in it's own extension and Arduino depends on it! Please check out the most recent version of the Arduino extension to try it out.
