### ISSUE TITLE
Config setting descriptions are unlcear

### ISSUE THREAD

**Issue by Pharap** [Microsoft/vscode-arduino#605]
The first setting `arduino.path` is pretty clear.
The other three settings however, are not well documented by their corresponding comments.

The second setting, `arduino.additionalUrls`, is unclear.

> Additional URLs for 3rd party packages. You can have multiple URLs in one string with comma(,) as separator, or have a string array. The default value is empty.

It doesn't specify what 'packages'.
(I have inferred from the name of a past issue that it means 'board packages', but I can see that others might not make the connection.)

And the final two settings have no comment at all.
It is unclear what values `arduino.logLevel` supports other than `info`.
Admittedly clicking the edit icon reveals `verbose` to be the other option, but it would still be nice to have the comment filled in properly.
While one would hope that `arduino.enableUSBDetection` is obvious (detecting serial devices connected via USB), it should still be documented for the sake of clarity.

**Comment by czgtest** [comment]
improve some descriptions  on v0.2.18
