### ISSUE TITLE
Select port dropdown not working in Insider's Edition

### ISSUE THREAD

**Issue by TreTuna** [Microsoft/vscode-arduino#607]
With Visual Studio Code Insider's Edition Version 1.25.0-insider (1.25.0-insider) build c51cf862a9604dffe2e3e8792a4b0a45213869a3 I am not getting a dropdown to choose ports. One I opened in Visual Studio Code Version 1.23.1 (1.23.1) I was able to select and save a port to the configuration and can now build in Insider's Edition, however, the select port dropdown still does not appear to select a different port.

**Comment by czgtest** [comment]
VSCode insider has been upgraded to node.js >8.0 , This will have breaking changes on the native module on vscode arduino. 
@TreTuna  Can you upgrade to 1.26.0.-insider ?   serial port work well on it.
