### ISSUE TITLE
" [Error] Exit with code=undefined " -> too little information

### ISSUE THREAD

**Issue by gajop** [Microsoft/vscode-arduino#611]
I'm getting the error as mentioned (`[Error] Exit with code=undefined`), which is lacking information.
My `arduino.path`, `arduino.commandPath` or something else is probably wrong, but it's too hard to tell where the issue is.
Can you please increase the verbosity of the commands like Verify, so we have a chance to figure out what went wrong?
Thanks!

PS: In my case the issue was that I didn't restart VS Code after correcting the path, but this doesn't invalidate the issue (if I knew it was trying to use the wrong path, I could've figured out the reason why sooner)

**Comment by czgtest** [comment]
@gajop  Thank you for your feedback. 

before use this extension,  we should install Arduino IDE. 
you can not set  “arduino.path”  , when you use this extension ,  it will  automatically detected from your Arduino IDE installation path. 

arduino.commandPath is not required too , it is only option.


for this error, we will improve the description,  Can you tell us the detail of how to repro on it ?

**Comment by gajop** [comment]
I don't have Arduino IDE installed in the default path, which is why I specified a custom `arduino.path` pointing to the right location.

I think you can easily reproduce this by specifying any bogus `arduino.path`. This is not a bug, just lacks verbosity to help the user figure out what settings are wrong.

**Comment by czgtest** [comment]
if not install Arduino IDE or set incorrect path for  `arduino.path` ,  then you run arduino command , will get an message as bellow.

![image](https://user-images.githubusercontent.com/35018765/44136413-4fbcdf76-a09f-11e8-9adf-655bf13df6e1.png)

if `arduino.commandPath` is not right,  we will get the error " [Error] Exit with code=undefined "  when run arduino command.  Thank you a lot for your feedback,  we will improve the error information then

**Comment by czgtest** [comment]
![image](https://user-images.githubusercontent.com/35018765/44244130-f80d7300-a204-11e8-8fe5-ade0069871c1.png)

**Comment by gajop** [comment]
I'd add some space after the ".", but otherwise it's a good error message (especially as it also includes the attempted path)

**Comment by human2010** [comment]
@czgtest  " [Error] Exit with code=undefined " ，I also encountered such a problem, how to solve it? Please give pointers!

**Comment by PeterWone** [comment]
I don't _have_ a commandPath specified but I'm getting code=undefined, what else can it mean?
