### ISSUE TITLE
highlights errors

### ISSUE THREAD

**Issue by aster94** [microsoft/vscode-arduino#614]
in the arduino ide there is a very useful soft red highlight of the first error encountered during compile time:

![12](https://user-images.githubusercontent.com/21184718/43038147-8a82f288-8d14-11e8-9245-9726dbe72736.png)

you should add this and overtake it highlighting all the errors.
the second error in this example is not highlighted as you can see

![13](https://user-images.githubusercontent.com/21184718/43038157-ba8e36ea-8d14-11e8-9591-78b6634eeef9.png)

**Comment by czgtest** [comment]
It is a great feature request. Thank you for your feedback

**Comment by aster94** [comment]
Thanks

I was also thinking that maybe highlighting only the first error would be faster since the compiler stops there instead of checking all the code. Maybe you could add an option to leave the user choose if he wants all the code checked or having it stopping at the first one

**Comment by aster94** [comment]
you may find this useful:
https://github.com/Microsoft/vscode-extension-samples/tree/master/decorator-sample

**Comment by smarthomeagentur** [comment]
Is there any way to highlight errors on compile? I tested it with a fresh project and the only way to find the compilation error seems to be the output in terminal
