### ISSUE TITLE
Add ESP32 to the Board Manager

### ISSUE THREAD

**Issue by Hans007a** [Microsoft/vscode-arduino#621]
Hello,

how to add ESP32 to the Board Manager?
Any description?

Regards

Hans

**Comment by czgtest** [comment]
@Hans007a  here is the step:

1. open VSCode --File--Preferences--Settings
2. set arduino.additionalUrls in global user preferences and save

you can add ESP32 board manger url here,
    "arduino.additionalUrls": [
        "<Your ESP32 additional boards manager Url>",
        "http://arduino.esp8266.com/stable/package_esp8266com_index.json",
        "https://raw.githubusercontent.com/jantje/arduino-esp32/master/package/package_Espressif_esp32_index.json"
    ],

3. Press F1 and select command "Arduino: Board Manager"

you can see install button and click it.

![image](https://user-images.githubusercontent.com/35018765/43375170-f8c24334-93e5-11e8-8c9c-835567d7f792.png)

**Comment by Sneezry** [comment]
Espressif officially released esp32 package yesterday https://dl.espressif.com/dl/package_esp32_index.json

**Comment by nights321** [comment]
Has it been deleted? Its not there anymore.. (refreshed package indexes just to be sure)

**Comment by ivan7707** [comment]
Hi, I had to add the arduino extension for vscode before I could use/find board manager- even after using the official url. 

https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-arduino

**Comment by armando-fandango** [comment]
is there a way to install it from command line ? after configuring the URL
