### ISSUE TITLE
Can I avoid running debugServer so I can do remote debug?

### ISSUE THREAD

**Issue by DeqingSun** [Microsoft/vscode-arduino#625]
Hi,

I tried to connect to another computer running OpenOCD. So I don't need VS code to start openocd.

However, VScode Arduino seems require a valid debugServer before it actually runs a debugger. Is it possible to bypass this restriction?

I tried to make a fake openocd with a shell script. However, no matter I use wait or sleep, I can not fool VScode.

**Comment by DeqingSun** [comment]
It seems new version of openocd can use dummy.cfg interface and faux.cfg target.

Then debugger can proceed.

**Comment by czgtest** [comment]
@DeqingSun  In other words , do you use the latest openocd to resolve your issue ?

**Comment by DeqingSun** [comment]
Yes, I can use latest openocd to use dummy.cfg interface and faux.cfg target.

VS code will still create a local openocd instance. But I can let debugger attach to another remote openocd.
