### ISSUE TITLE
resolveDebugConfigurationAsync doesn't resolve predefined variables

### ISSUE THREAD

**Issue by DeqingSun** [microsoft/vscode-arduino#627]
I tried to use ${workspaceFolder} to avoid long command. However, the variable was not resolved when "fileExistsSync" is performed.

<img width="787" alt="screen shot 2018-07-28 at 2 44 51 am" src="https://user-images.githubusercontent.com/1385273/43353961-b7eb0070-9210-11e8-85bb-d04fba35828d.png">

I tried to copy "resolveVariables" from https://github.com/Microsoft/vscode-cpptools/blob/master/Extension/src/common.ts

But for some reason, it doesn't resolve ${workspaceFolder} either. Is there a way to resolve it nicely?

**Comment by czgtest** [comment]
the debugServerPath should be like this,  it is your code issue.
![image](https://user-images.githubusercontent.com/35018765/44245573-e8ddf380-a20b-11e8-8f4d-a7be793a03ad.png)
