### ISSUE TITLE
Upload Using Programmer with USBtinyISP without a serial port set.

### ISSUE THREAD

**Issue by Seairth** [microsoft/vscode-arduino#630]
When attempting to program with a USBtinyISP, I am receiving the following error:

`Please specify the upload serial port.`

USBtinyISP does not use a serial port.  In this case, the port should not be checked or passed as a command-line option.

**Comment by feltte** [comment]
I have same problem with release 0.2.24.
Is this issue fixed?

**Comment by CaptainMack** [comment]
No updates for this? I'm having the same problem.

**Comment by tobia** [comment]
So what's the solution?

**Comment by hellyzh** [comment]
Setting an arbitrary serial port allows the sketch to be uploaded without appearing to cause any issue. You can select a serial port and rerun.

**Comment by feltte** [comment]
Why closed?
Some PC have no serial port and USBasp is not recginized as a serial port. I cannot select an arbitrary serial port because there is no serial port.

**Comment by a7hybnj2** [comment]
Agree with @feltte I have 1 serial and its already in use by another utility and when I select it it acts strangely.

**Comment by hellyzh** [comment]
Add a line `"port": "port"` to the config file ./.vscode/arduino.json. Then it will assume you have selected a port named port. To prompt user to select a port, it is because most of cases, it need to choose a serial port to do operation like open serial port or upload code.
