### ISSUE TITLE
Add Serial Plotter

### ISSUE THREAD

**Issue by Ivel97** [Microsoft/vscode-arduino#639]
Would it be possible to implement a version of the Serial Plotter that we have on the Arduino IDE into VS Code?

**Comment by aster94** [comment]
it's already a work in progress #470

**Comment by Ivel97** [comment]
Great, thanks

**Comment by timebis** [comment]
Is it available now ?
Thanks

**Comment by pacaudcorentin** [comment]
You can use this extension, but it seems broken at this moment
https://github.com/nesnes/teleplot-vscode
