### ISSUE TITLE
#include statements inside if blocks marked as necessary dependecies

### ISSUE THREAD

**Issue by 435vic** [microsoft/vscode-arduino#643]
In many libraries, if blocks are used to support older versions of Arduino, like this:
```
#if (ARDUINO >= 100)
 #include "Arduino.h"
#else
 #include "WProgram.h"
#endif
```

If my version of arduino is recent enough, `Arduino.h` will be looked for. Otherwise, It'll be `WProgram.h`.
The issue is, VSCode looks for both, and as WProgram.h was *replaced* with Arduino.h, one of them wil not be found, producing a warning.

Many times, removing the comparison seems to break something, so sometimes I cannot do that.

I would say to just ignore any `include`s inside if blocks, or ignore the ones that don't get run, such as the `#else` (if my arduino is recent)

**Comment by relu91** [comment]
I have the same issue with Encoder.h library.

**Comment by antti202** [comment]
Would be nice to get fixed, still an issue.

**Comment by adiazulay** [comment]
This was a bug with c/c++ extension and should be fixed now. Please reopen this issue if you're still experiencing the problem.
