### ISSUE TITLE
should IntelliSense suggest only built in function?

### ISSUE THREAD

**Issue by aster94** [microsoft/vscode-arduino#645]
hello,

as wikipedia says the aim of intelliSense is to

> reducing the amount of name memorization needed

i think that the intelliSense in vscode should be "focused" on the built-in functions used by the arduino users and not in all the functions which are hidden by the core

example:
![44535657-cc095a80-a6fa-11e8-83ee-55613d761c1d](https://user-images.githubusercontent.com/21184718/44881862-73652f00-acb1-11e8-9e67-615a9734d8f6.png)
i guess that no one ever used that stuff, the common user is interested only in pinMode

![44535744-01ae4380-a6fb-11e8-8099-9ed6193ab58e](https://user-images.githubusercontent.com/21184718/44881873-7829e300-acb1-11e8-8514-fd923c35869e.png)
it doesn't even suggest delay

![44535754-0b37ab80-a6fb-11e8-81b2-8749e0e21939](https://user-images.githubusercontent.com/21184718/44881880-7eb85a80-acb1-11e8-86a0-803d8040410f.png)
same for the serial, where is "begin"?

many and many other examples could be made
the point is that the arduino's user uses arduino not to use the function inside the core but only the built-in which can be found in Arduino.h
https://github.com/arduino/ArduinoCore-avr/blob/master/cores/arduino/Arduino.h

![44535763-0ffc5f80-a6fb-11e8-9995-85d6fff69723](https://user-images.githubusercontent.com/21184718/44881897-824be180-acb1-11e8-90cc-cdbc8f05d363.png)
also the libraries inside the core shouldn't been suggested, the only suggested should be the libraries inside the workspace and the one from the core (https://github.com/arduino/ArduinoCore-avr/tree/master/libraries)

i don't know if this is possible/easy but this would be another great improvements

**Comment by czgtest** [comment]
Thanks a lot for your feedback and suggestion,   it is a good feature request to improve intelliSense.

**Comment by aster94** [comment]
I don't have any knowledge about intellisense but i think this is funny: the perfect behaviour should be this one
![screenshot 2018-10-26 18 44 46](https://user-images.githubusercontent.com/21184718/47580659-bb21d300-d94f-11e8-8f39-22364c974379.png)

but unfortunately using the normal way arduino people code it doesn't show anything
![screenshot 2018-10-26 18 45 36](https://user-images.githubusercontent.com/21184718/47580666-c117b400-d94f-11e8-98a4-486fe5b1f2d1.png)
