### ISSUE TITLE
add "Sketches" folder

### ISSUE THREAD

**Issue by aster94** [Microsoft/vscode-arduino#652]
_I promise that this is my last issue_

in the arduino IDE there is a very useful "Sketches" folder where the users put its project, code snippets, recipes, etc

it can be set from the IDE preferences
![screenshot 2018-09-04 00 17 01](https://user-images.githubusercontent.com/21184718/45002550-226a7900-afd8-11e8-9fd3-ce6f612a381f.png)

and, it could be obtained from the arduino's `preferences.txt` file
excactly from this line: `sketchbook.path=`

**note that this is exaclty the same path of the user's library folder**

I think that adding this Sketches folder at this place in vscode would be very useful for the user who are used to have their sketches easily accesible
![screenshot 2018-09-04 00 08 10](https://user-images.githubusercontent.com/21184718/45002589-a886bf80-afd8-11e8-8766-0485b513354c.png)

**Comment by czgtest** [comment]
@aster94  Thank you a lot for your feedback, it is a nice feature request.

**Comment by aster94** [comment]
solved with #654

**Comment by czgtest** [comment]
This feature is already online on v0.2.23
