### ISSUE TITLE
Cannot click Select Serial Port

### ISSUE THREAD

**Issue by Nickiel12** [Microsoft/vscode-arduino#664]
whenever I click the Select Serial Port button in the bottom right, I get "Extension Host terminated unexpectedly. with two buttons, Open Dev Tools, and Restart Extension Host. This happens every time, and I haven't found anything online

EDIT: I found a workaround, I went to the .vscode > arduino.json and added this code snippet, `"port": "COM5"`. this worked, I know my COM port from the arduino ide.

**Comment by czgtest** [comment]
@Nickiel12  Do you use the latest VSCode ? 
Now I use vscode 1.27.2,  the serial port work well.

please see #590

**Comment by Nickiel12** [comment]
Yes 1.27.2 User Setup. Are you using the system wide? I can't get that to work in a specific scenario, so I use the user setup.

**Comment by czgtest** [comment]
@Nickiel12  Can you have a try on v0.2.25?  we add serial port support for Electron 3.0.

**Comment by Nickiel12** [comment]
the com button works perfectly now, thank you!!

**Comment by davidamayuelas** [comment]
It doesn't work for me. I'm just trying to send to my MXChip IOT Device and when I click on "Select Serial Port" doesn't do nothing
