### ISSUE TITLE
Export NSAT survey response and setup report automation

### ISSUE THREAD

**Issue by chyuanmsft** [Microsoft/vscode-arduino#667]

**Comment by czgtest** [comment]
@chyuanmsft  NSAT survey is on board on v0.2.22,  Can we close this task ?

**Comment by chyuanmsft** [comment]
@czgtest I opened this task for myself to export data and enable report, it's not started yet so please leave it open

**Comment by czgtest** [comment]
@chyuanmsft   any update for it ?  I think you can send NSAT result to team ,  and sync with each other, I close this issue now
