### ISSUE TITLE
Possible to undo forced include path for Arduino.h?

### ISSUE THREAD

**Issue by bretthannigan** [Microsoft/vscode-arduino#669]
Forcing `#include <Arduino.h>` does not allow use of the vscode-arduino extension to do straight AVR programming using the Arduino programmer if any conflicts arise with Arduino.h. Would prefer this removed or made optional in the settings.

**Comment by per1234** [comment]
arduino-builder only adds `#include <Arduino.h.` if the sketch does not already contain an #include directive for that file. So you can block the automatic inclusion of Arduino.h by adding this code to your sketch:
```cpp
#if false
#include <Arduino.h>
#endif
```

Reference: https://github.com/arduino/arduino-builder/commit/9d3dc9e08bdff88d0294f0cbfff704c5aa87d861

**Comment by bretthannigan** [comment]
Thank you, works perfectly.
