### ISSUE TITLE
Debug with J-Link via J-Link GDB Server

### ISSUE THREAD

**Issue by Yoshii1993** [microsoft/vscode-arduino#677]
Hey,
i tried to use the Extension's new Debug capability with my J-Link Debugger on an Adafruit Feather M0.

Cause of the not very clear documentation it took time to figure out, that the extension only accepts OpenOCP as a Debug Server (Which leads to strange Error Messages, if you don't know and write the path to your J-Link GDB Server in the "debugServerPath" field or just leave it blank becaus your server is already started).

After walking through extension's code, i found out that the "\out\src\debug\configurationProvider.js"
checks if there is a path set to openocp.exe. If you leave the field blank, the path is set automatically to openocp, so you can't stop the extension to start it.

This is not so nice if you don't want to use it (maybe because openocp says it's latest tested version with j-link is from 2012...) because openocp's feedback determinates the programm's behaviour.

So what i did to solve it:
i commented out the content of the functions "resolveOpenOcd(config)" and "resolveOpenOcdOptions(config)" in "configurationProvider.js" and made them return true.
This makes the extension thinking that openocd path is set fine and the server arguments are fine too.
This causes that no error feedback from openocd stops the extension debug process and the gdb server is able to connect peacefully (with the right argument of course) to the already startet J-Link Server (not the command line version, caus the GUI starts with pre-settings).

I hope this dirty workaround will help some people which are struggling with the debugging.
And i like to advice, that it would be nice, in future versions, to make the user know, that openocp is used or give him the option to use the gdb server of his debugging device.

Kind Regards
Domenik

**Comment by minkir014** [comment]
Cortex Debug extension does that.
