### ISSUE TITLE
Can't Manage Boards (or do anything infact)

### ISSUE THREAD

**Issue by hossimo** [Microsoft/vscode-arduino#682]
I'm just not sure what I'm doing wrong. I have seen a number of other issues closed because it works on other machines. But I feel like I have read through most of the associated info and I can't see what is not configured correctly.

The issue I am having is if I press `F1` and type `>Arduino: Board Manager` I get a list of boards but of I choose any I get the following in the output console:

> [Starting] Update package index files...
> Loading configuration...
> Initializing packages...
> Preparing boards...
> java.lang.NullPointerException
> 	at processing.app.BaseNoGui.onBoardOrPortChange(BaseNoGui.java:678)
> 	at processing.app.Base.onBoardOrPortChange(Base.java:1313)
> 	at processing.app.Base.<init>(Base.java:276)
> 	at processing.app.Base.main(Base.java:145)
> [Error] Exit with code=255

I have added the additional URL to my Settings as well as other settings (ones with x_ are removed for testing)

```
    "x_arduino.path": "C:/Program Files (x86)/Arduino",
    "x_arduino.commandPath": "run-arduino.bat",
    "x_arduino.logLevel": "info",
    "x_arduino.enableUSBDetection": true,
    "x_arduino.disableTestingOpen": false,
    "x_arduino.skipHeaderProvider": false,
    "arduino.additionalUrls": [
        "http://arduino.esp8266.com/stable/package_esp8266com_index.json"
    ],
    "arduino.defaultBaudRate": 115200,

```

After further testing I have noticed that other things cause the above error like:

- Clicking on Refresh Package Indexes in the Board Manager
- Trying to install any other board

**Comment by czgtest** [comment]
@hossimo ，

1.Remove all configurations except arduino.additionalUrls  in VS Code settings
2.don't use Arduino IDE 1.8.7, rduino IDE 1.8.7 has some breaking changes, it will install board package and library failed, So it is recommended that you install version 1.8.6

then can you have a try?

![image](https://user-images.githubusercontent.com/35018765/47826836-343c8280-ddb5-11e8-9e58-6ac39af2e54c.png)

if the error still repro on , please delete the Arduino15 folder in 
C:\Users\v-czg\AppData\Local\Arduino15

**Comment by hossimo** [comment]
Thanks for the update. I got it working by renaming my Arduino15 folder and rebuilding it with the IDE.

Thanks!
