### ISSUE TITLE
Default C/C++ configuration uses MSVC for IntelliSense rather than GCC

### ISSUE THREAD

**Issue by rhalkyard** [microsoft/vscode-arduino#684]
The project that I am working on brings in the `SPI.h` header that is part of the standard Arduino distribution. This header uses the GCC-specific `__attribute__()` macro in several places, which causes IntelliSense to trip up and report nonsense errors in my project, since MSVC appears not to understand it.

If I modify `c_cpp_properties.json` to use the AVR-GCC compiler provided in the Arduino distribution, using the same command-line options that are used in the compilation process, and set `intelliSenseMode` to `gcc-x64`, I get much more sensible IntelliSense output. Since Arduino projects are always compiled using the Arduino AVR-GCC toolchain, and MSVC chokes on GCC-specific macros in official Arduino headers such as `SPI.h`, shouldn't this be the default value populated in `c_cpp_properties.json` for new projects, rather than MSVC?

The `c_cpp_properties.json` that I am using to make Intellisense work in my project (on a Mega2560 board) is as follows. Note that I have also modified the include paths; I can't remember what the reasoning behind them was, except for that I ran into issues with the default `hardware\arduino\avr\**` and `tools\**` paths at some point, and restricting the include paths to specific directories got things working again.

```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "C:\\Program Files (x86)\\Arduino\\tools\\**",
                "C:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\**",
                "C:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\**",
                "C:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\libraries\\**",
                "C:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\bootloaders\\**",
                "C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr\\avr\\include"
            ],
            "forcedInclude": [
                "C:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino\\Arduino.h"
            ],
            "intelliSenseMode": "gcc-x64",
            "compilerPath": "\"C:/Program Files (x86)/Arduino/hardware/tools/avr/bin/avr-g++.exe\" -Wall -Wextra -c -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR",
            "cStandard": "c11",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
}
```

**Comment by kerrsmith** [comment]
I have now got error highlighting working with my Arduino code, here are the steps I used to get it working:

Create a new project folder
Launch VScode and open this new folder
Use CTRL+Shift+P and choose 'Arduino: Initialize'
Name your .ino file
Choose the relevant board (I choose 'Arduino Nano')

Next open this new .ino file in the official Arduino IDE and go to File -> Preferences
Tick the 'Show verbose output during compilation' and then click OK.
With the .ino file open and the correct board chosen select 'verify', this is the 'tick' icon.
Copy the text from the bottom of the window into a text editor and look for the line that says 'Detecting libraries used...'
Just under this look at the line similar to the following:

`C:\\Users\\YOUR-USER-NAME\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\5.4.0-atmel3.6.1-arduino2/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10808 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR`

Copy the part from `-c` to `-DARDUINO_ARCH_AVR`

Go back to VScode and open 'c_cpp_properties.json' from the .vscode folder

In this default created code modify the 'includePath' so it looks like the block shown below then add the code starting with 'intelliSenseMode:' so it looks similar to that shown below, use the part you just copied above in the 'compilerPath' line (thank you to https://github.com/Microsoft/vscode-arduino/issues/684#issue-377193346 for this whole section of code):

```JSON
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "C:\\Program Files (x86)\\Arduino\\tools\\**",
                "C:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\**",
                "C:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\**",
                "C:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\libraries\\**",
                "C:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\bootloaders\\**",
                "C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr\\avr\\include",
                "C:\\Users\\YOUR-USER-NAME\\Documents\\Arduino\\libraries\\LiquidCrystal"
            ],
            "forcedInclude": [
                "C:\\Users\\YOUR-USER-NAME\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.6.23\\cores\\arduino\\Arduino.h"
            ],
            "intelliSenseMode": "gcc-x64",
            "compilerPath": "\"C:/Program Files (x86)/Arduino/hardware/tools/avr/bin/avr-g++.exe\" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10808 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR",
            "cStandard": "c11",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
}
```

Note: change YOUR-USER-NAME in the lines above to your actual username.

Save the file and wait until the small red icon and three small disks icons disapear from the bottom righthand corner of the window - this allows VScode time to index all the files.

Now you can go back to your .ino file and start coding and the intellisense and error highlighting will now work.

If you have additional libraries just add a link to them in the 'includePath' part in c_cpp_properties.json.
