### ISSUE TITLE
Arduino extension shouldn't rename C++ language to "Arduino"

### ISSUE THREAD

**Issue by ArthurMa1978** [Microsoft/vscode-arduino#686]
It looks like it should be a simple package.json change.  You are renaming the “cpp” language ID:

<img width="833" alt="arduino" src="https://user-images.githubusercontent.com/20514459/47974600-58fe6600-e0e5-11e8-9031-8bbf557baac7.png">

Though honestly, vscode shouldn’t allow extensions to overwrite the builtin language set.

**Comment by czgtest** [comment]
I  will check for it

**Comment by czgtest** [comment]
verify pass on  0.2.23，  so close it
