### ISSUE TITLE
Support input keystrokes in serial monitor

### ISSUE THREAD

**Issue by chyuanmsft** [microsoft/vscode-arduino#700]

**Comment by mathertel** [comment]
There is at least a command "Arduino: Send text to Serial Port" that allows sending some characters.
The only thing that is missing is sending CR or CRLF because enter will send and close the dialog.

**Comment by Sneezry** [comment]
Hi @mathertel , there is an option to set line endings. Please follow these steps to set line ending:

1. **Open serial port monitor** (line ending setting only shows when serial port monitor is open)
2. Click line ending setting in status bar
3. Select line ending

![Snipaste_2019-04-15_10-27-16](https://user-images.githubusercontent.com/1621293/56104178-51cb6600-5f69-11e9-813d-23150dae56f9.png)

**Comment by Aravindray** [comment]
Hi @Sneezry I followed your step but "No line ending" setting is not available in Status bar. So, I can't able to change it. Do you know how to solve it?
![2020-12-31](https://user-images.githubusercontent.com/68138580/103403274-918b1480-4b75-11eb-8c8d-05d7b015a35f.png)

**Comment by adiazulay** [comment]
@Aravindray it looks like your serial port is closed in that screen shot. Is the menu option missing when the serial port open too?

**Comment by vishnumaiea** [comment]
![image](https://user-images.githubusercontent.com/10383395/121816024-e68b9480-cc96-11eb-8677-c1e2d7ce7580.png)

It is in fact missing on my status bar. Serial monitor is open as you can see.
