### ISSUE TITLE
Build errors, related bugs 618,622,683

### ISSUE THREAD

**Issue by ollyru** [Microsoft/vscode-arduino#717]
Hello!

Build errors: I think it's related bugs 618,622,683.

Three times repeat one thing action. Press "F1" -> "Arduino Verify". Getting an error twice. Third time surprise: compiled without errors!

I built a separate project to simulate this error. Use incremental build - it's important. Project and pic's described error attached here:

[Build_erros.txt](https://github.com/Microsoft/vscode-arduino/files/2623890/Build_erros.txt)

![surprise1](https://user-images.githubusercontent.com/45421054/49144866-7d79e680-f30f-11e8-8cbf-7da15a77229f.PNG)

![difffiles](https://user-images.githubusercontent.com/45421054/49144905-95ea0100-f30f-11e8-828a-4f8609c843b0.PNG)

![settings_this_important](https://user-images.githubusercontent.com/45421054/49144921-a00bff80-f30f-11e8-8274-1205fff5c802.PNG)

[Blink_error.zip](https://github.com/Microsoft/vscode-arduino/files/2623901/Blink_error.zip)

**Comment by ollyru** [comment]
In the second picture function prototypes added: why are they not in the first file?

**Comment by ollyru** [comment]
For the same reason, by the way, I think the wrong conclusion is made before compiling that the files have changed and it is necessary to rebuild the entire project ("Build options changed, rebuilding all") if I change just only main (blink.ino) file. Although the other files in fact has not changed. But it's really just a guess.

And yet, I forgot to add: in the standard Arduino 18.8.6 no errors in the Assembly.

[arduino_186.txt](https://github.com/Microsoft/vscode-arduino/files/2624061/arduino_186.txt)

**Comment by czgtest** [comment]
@ollyru   do you use Arduino IDE 1.8.7 and build error?   when use Arduino IDE 1.8.6 , there is no error. 
Arduino IDE 1.8.7 has some breaking changes, it will install board package and library failed, So it is recommended that you install version 1.8.6.

**Comment by ollyru** [comment]
No, i am already use version 1.8.6, only, i readed description for plugin :-) 
May be it depended from my used libraries... 
-- 
Отправлено К-9 Mail для Андроида

29 ноября 2018 г. 5:46:15 GMT+03:00, Chen Zhang <notifications@github.com> пишет:

**Comment by czgtest** [comment]
@ollyru  yes,  if code only support old libraries ,then you install new version libraries , verify and upload will failed,  or if code support new libraries,  then you install old version libraries,  verify will fail too..
now do you resolve this issue ?

**Comment by ollyru** [comment]
Not yet. Manually delete "build" directory before every build.

**Comment by czgtest** [comment]
@ollyru  I open an issue to Arduino IDE,  https://github.com/arduino/Arduino/issues/8271

**Comment by ollyru** [comment]
Great! Thank you very much!!! It works (without nested build path)!
