### ISSUE TITLE
Wrong arduino.commandPath in Doc for MacOS

### ISSUE THREAD

**Issue by MarNwk** [Microsoft/vscode-arduino#720]
OS: MacOs High Sierra
Arduino Version: 1.8.7
Doc: https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-arduino#overview

I installed Visual Code and followed the instructions in the Documentation and used `Contents/MacOS/run-arduino.sh` as path for `arduino.commandPath`, this doesn't work. 
The correct path is `"arduino.commandPath": "Contents/MacOS/Arduino"`

**Comment by czgtest** [comment]
@MarNwk ， arduino.commandPath is  option settings,  not necessarily setting, if you don't have customer command line to run ,  you can not set it in VS Code settings.

**Comment by MarNwk** [comment]
@czgtest Even if it is optional an optional setting, the value provided for MacOs in the documentation is outdated or wrong.

**Comment by czgtest** [comment]
@MarNwk  thank you for your contribution and feedback,  readme already updated

**Comment by jimmyff** [comment]
The text in the settings UI is still incorrect

**Comment by anarchydude** [comment]
Can also vouch text is still incorrect as of this post.
