### ISSUE TITLE
arduino.commandPath error in Windows causes [Error] Exit with code=UNKNOWN

### ISSUE THREAD

**Issue by jaycontensive** [Microsoft/vscode-arduino#722]
Extension installed with "arduino.commandPath" : "run-arduino.bat". That file didn't exist and creating it didn't help.  Tool-tip flyout for that setting said "run-arduino.bat" is the default setting.

[Error] Exit with code=UNKNOWN

.. github doc said default should be "arduino.commandPath": "arduino_debug.exe" -- fixed my issue.

**Comment by czgtest** [comment]
Arduino.commandPath is option settings, not necessarily setting, if you don't have customer command line to run , you can not set it in VS Code settings.
