### ISSUE TITLE
intellisense for Arduino Tabs

### ISSUE THREAD

**Issue by craiq** [microsoft/vscode-arduino#727]
Hi,

my project is grown quite big and is devided in many tabs. [Youtube Example](https://www.youtube.com/watch?v=dSAb3LZBHp0)

Now my problem is, that intellisense don't recognize the functions or variables from other tabs and mark them as non declared. I searched a while now and couldn't find an option so intellisense get the information from all files.

Can this please be added? Or does anyone know how to set this up?

System:
Win10
Visual Studio Code 1.30.0
Extensions:
Arduino 0.2.24
C/C++ 0.20.1

**Comment by czgtest** [comment]
@craiq ,  you can open your project with vs code and add include path to c_cpp_properties.json

![image](https://user-images.githubusercontent.com/35018765/50439817-63dbb700-092e-11e9-9e6f-0313b5d8aabe.png)

**Comment by craiq** [comment]
Thanks for your reply @czgtest 
just "${workspaceRoot}/**" was missing
the rest already was this way. Still no change.
When I extract parts in another file in the same folder I get undefined errors

**Comment by disconn3ct** [comment]
This is still a problem. Please do not close without resolution.

**Comment by disconn3ct** [comment]
Must be nice in all of those velocity meetings (or scrum retros or whatever) to be able to say that you have no backlog because its all been closed.. that doesn't make it valid though, and *REALLY* doesn't encourage contributions.

**Comment by ryancole38** [comment]
If anyone is still struggling with this, what worked for me was to add a path to an `Arduino.h` file under forcedInclude.

**Comment by Rovexx** [comment]
I still encounter this issue on some of my computers. I tried adding paths to all my arduino stuff. also the path to an 'Arduino.h' file. did not work

**Comment by travipross** [comment]
Thank you @Rovexx, this solved my issue as well.
