### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by horvus** [Microsoft/vscode-arduino#739]
- Issue Type: `Performance`
- Extension Name: `vscode-arduino`
- Extension Version: `0.2.24`
- OS Version: `Linux x64 4.18.0-13-generic`
- VSCode version: `1.30.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/michel_bodje/vsciot-vscode.vscode-arduino-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by czgtest** [comment]
duplicate with #759
