### ISSUE TITLE
Arduino plugin does not associate with .pde extension

### ISSUE THREAD

**Issue by kejxu** [Microsoft/vscode-arduino#752]
ROS is one of the most popular robot framework at this point, and rosserial_arduino is its arduino client support. Most, if not all, of the package's [examples] (https://github.com/ros-drivers/rosserial/tree/melodic-devel/rosserial_arduino/src/ros_lib/examples) use `.pde` extension.

**Comment by ijash** [comment]
yes, i need this too..

**Comment by dooriya** [comment]
.pde sketch file was supported in Arduino IDE prior to the release of version 1.0.
pre 1.0 versions do not support many new libraries due to significant changes to the Arduino core API. So if you're using old .pde sketch, you can rename it to .ino extension.

**Comment by kejxu** [comment]
> if you're using old .pde sketch, you can rename it to .ino extension.

thanks for the explanation! this sounds like the recommended action suggested in [Arduino guide](https://www.arduino.cc/en/Guide/Environment); however, it seems `.ino` and `.pde` are still essentially the same thing.

To clarify the scenario reported, most Arduino examples could be opened and generated from vscode-arduino, like this:
![image](https://user-images.githubusercontent.com/44008378/54708829-73b80100-4b01-11e9-827e-4e51fca86529.png)

the generated example defaults to use the `.pde` extension:
![image](https://user-images.githubusercontent.com/44008378/54708945-bb3e8d00-4b01-11e9-9551-3904780ff4a2.png)

In this case, there would neither be any language support:
![image](https://user-images.githubusercontent.com/44008378/54709020-e6c17780-4b01-11e9-9270-d23f2dbd0bd4.png)

All of these could be fixed by renaming the file's extension to `.ino`; however, in that case the process would not be as stream-lined as it could be. Meantime, this is just one of the cases that is found, there might be dozens more (generated) examples that still use the `.pde` extension (due to lack of maintenance).

Is there a specific reason why `.pde` should not be supported? The extension might change to pop up a message suggesting renaming the extension if the current editor opens a `.pde` file.
