### ISSUE TITLE
Very slow compilation

### ISSUE THREAD

**Issue by faig3105** [microsoft/vscode-arduino#758]
I have seen similar post, it wasn't solved at all and was just closed. OUTPUT FOLDER IS SPECIFIED!!! and still very vey very SLOW compilation!!!! CPU is idle , disk is idle what does it do then?
Please help, or I will have no option except moving to platformIO.

**Comment by Nufflee** [comment]
I'm hitting the same issue.. I'm using the STM32 Cores Board Library and I have the output directory set in arduino.json but compile times are way slower than Arduino IDE. Something has to be done about this.
