### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by gtcdevop** [Microsoft/vscode-arduino#759]
- Issue Type: `Performance`
- Extension Name: `vscode-arduino`
- Extension Version: `0.2.25`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.30.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/usuario/vsciot-vscode.vscode-arduino-unresponsive.cpuprofile.txt` :warning:

[vsciot-vscode.vscode-arduino-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-arduino/files/2793727/vsciot-vscode.vscode-arduino-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by czgtest** [comment]
duplicate with #762
