### ISSUE TITLE
Unnecessary prompt for serial port when uploading with USBasp

### ISSUE THREAD

**Issue by turmoni** [microsoft/vscode-arduino#760]
This is effectively the same issue as #630, but for a different programmer, so I don't want to risk overloading that one.

The [USBasp](https://www.fischl.de/usbasp/) is a simple USB-based programmer for AVRs. avrdude talks directly to the device using libusb rather than going via a serial port. When attempting to upload via Code using this programmer without a serial port set, you are prompted to choose a serial port, and the sketch is not uploaded. Setting an arbitrary serial port allows the sketch to be uploaded without appearing to cause any issue, but it took me a while to figure this out.

I'm running Code 1.30.2 from the Arch Linux repositories, but I assume this is platform independent. I'm using version 0.2.25 of the extension.

**Comment by flyandi** [comment]
This is still happening in 2021.
