### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by dbgjerez** [Microsoft/vscode-arduino#762]
- Issue Type: `Performance`
- Extension Name: `vscode-arduino`
- Extension Version: `0.2.25`
- OS Version: `Linux x64 4.15.0-43-generic`
- VSCode version: `1.30.2`

[vsciot-vscode.vscode-arduino-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-arduino/files/2806776/vsciot-vscode.vscode-arduino-unresponsive.cpuprofile.txt)

**Comment by czgtest** [comment]
duplicate with #755
