### ISSUE TITLE
Filename order cause compilation error

### ISSUE THREAD

**Issue by sudoerChris** [microsoft/vscode-arduino#769]
I use .cpp files to seperate different part of the code, but when I include the cpp file, it will say 
`error: something.cpp: No such file or directory`
turns out it was due to the file name ordering, if the .cpp file is "higher" than the ino file, it will not compile, only when you change the name to make it "lower" than the ino file

reproduction steps:
- open a new folder
- command>arduino: initialize
- create i3.ino
- create i2.cpp
- add  `#include "i2.cpp"` in i3.ino
- compile -> shows `error: i2.cpp: No such file or directory`
- now rename i2.cpp to i4.cpp and change the #include
- compile -> success

**Comment by czgtest** [comment]
@sudoerChris   do you try to use Arduino IDE to repro this issue ?  I think it is an issue of Arduino  IDE.
