### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by anhtuank7c** [Microsoft/vscode-arduino#775]
- Issue Type: `Performance`
- Extension Name: `vscode-arduino`
- Extension Version: `0.2.25`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/anhtuank7c/vsciot-vscode.vscode-arduino-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by czgtest** [comment]
duplicate with #783
