### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by kino002** [Microsoft/vscode-arduino#780]
- Issue Type: `Performance`
- Extension Name: `vscode-arduino`
- Extension Version: `0.2.25`
- OS Version: `Linux x64 4.15.0-45-generic`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/takayuki/vsciot-vscode.vscode-arduino-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by czgtest** [comment]
duplicate with #778
