### ISSUE TITLE
Output Panel stops auto-scroll

### ISSUE THREAD

**Issue by Drayak335** [Microsoft/vscode-arduino#784]
The Output Panel suddenly stops auto-scrolling for "verify" or "upload", I need to manually scroll.  I don't know how to replicate it, but I have experienced several times. 

The only way I have found so far to make it auto-scroll again is to completely close the application and launch again.

**Comment by dilin-MS** [comment]
Hi @Drayak335 , can you please provide a snapshot so we can better the situation you met? Many thanks!

**Comment by Drayak335** [comment]
@dilin-MS  by snapshot, do you mean a screenshot? If not how do I get the snapshot?

Below a screenshot, if you can see in the right corner, when I hit verify I see the message "[Starting] Verfy sketch..."  and then it starts throwing all the messages, but the window doesnt auto-scroll, I need to  manually scroll to read the messages.

![image](https://user-images.githubusercontent.com/12659538/54148735-be02f900-4402-11e9-8052-892b83517188.png)

**Comment by Sneezry** [comment]
Hi @Drayak335 , click the small lock, and you will get auto scoll back.

![Snipaste_2019-03-11_23-21-28](https://user-images.githubusercontent.com/1621293/54178922-82911a80-4454-11e9-9114-bfde59b7857e.png)

**Comment by Drayak335** [comment]
> Hi @Drayak335 , click the small lock, and you will get auto scoll back.
> 
> ![Snipaste_2019-03-11_23-21-28](https://user-images.githubusercontent.com/1621293/54178922-82911a80-4454-11e9-9114-bfde59b7857e.png)

**Comment by Drayak335** [comment]
> Hi @Drayak335 , click the small lock, and you will get auto scoll back.
> 
> ![Snipaste_2019-03-11_23-21-28](https://user-images.githubusercontent.com/1621293/54178922-82911a80-4454-11e9-9114-bfde59b7857e.png)

Is there any keyboard shortcut to toggle this? I am trying to understand how it may have changed.

**Comment by Sneezry** [comment]
I don't know the keyboard shortcut for the lock, and I cannot find it in shortcut settings either. So I think the anwser is no.

**Comment by Drayak335** [comment]
Just as a follow up, I noticed that at some point something changes the state of this setting. I have not been able to figure out what is triggering the change?

**Comment by cocohub** [comment]
I have the same issue. Even though I click the lock icon, it stops auto scrolling. Any tips?
