### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by matthewburton71** [microsoft/vscode-arduino#785]
- Issue Type: `Performance`
- Extension Name: `vscode-arduino`
- Extension Version: `0.2.25`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.32.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/matthew/vsciot-vscode.vscode-arduino-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by dilin-MS** [comment]
Hi @matthewburton71 , do you mean you encountered high cpu load due to vscode-arduino? Can you provide more description concerning your situation?

**Comment by zunhu** [comment]
issue fixed, please install latest vscode\ arduino-extension\ arduino and try again.
