### ISSUE TITLE
Open/close Serial Monitor through exposed API 

### ISSUE THREAD

**Issue by sebrk** [microsoft/vscode-arduino#790]
I use MAKE with my setup. Everything works great except I have to manually close the Serial Monitor if it happens to be open when uploading new binary to the board. I would love to be able to close the Serial connection automatically as part of my build setup thus eliminating the issue. I very often try to upload forgetting about the already open Serial connection which makes the process stall.

I should say that I'm using the Android compatible board Teensy with [Teensyduino](https://www.pjrc.com/teensy/teensyduino.html) and [VisualTeensy](https://github.com/luni64/VisualTeensy)

**Comment by ArthurMa1978** [comment]
Arduino Extension already support close serial port when building / uploading.
VS Code doesn't support export internal runtime, so if you want to customize the build / upload process, like using MAKE, please manually close the serial port.

Please let us know if you have further asks.
