### ISSUE TITLE
Arduino Board Manage, exit with code 255

### ISSUE THREAD

**Issue by nehaunilever** [microsoft/vscode-arduino#800]
Hi All,

I am new to programming and am trying to install az3166 board. As soon as I open Arduino board manager , I see output screen exit with code 255.
Below is the error in the logs. 
C:\Users\Admin\AppData\Local\Arduino15\package_index.json.tmp: The process cannot access the file because it is being used by another process.

I am trying to navigate to the path mentioned and I cannot find theAppData folder in this location in my C drive.

Can you please help me understand where is this Location picked up from? Also no idea where this package is installed in my pc, how to check this?

**Comment by cosminpolifronie** [comment]
I have the same issue on Arch Linux. I have the following error:

> [Starting] Update package index files...
> Picked up JAVA_TOOL_OPTIONS: 
> Loading configuration...
> Initializing packages...
> Preparing boards...
> java.lang.NullPointerException
> 	at processing.app.BaseNoGui.onBoardOrPortChange(BaseNoGui.java:679)
> 	at processing.app.Base.onBoardOrPortChange(Base.java:1317)
> 	at processing.app.Base.<init>(Base.java:284)
> 	at processing.app.Base.main(Base.java:151)
> [Error] Exit with code=255
> 
> [Starting] Update library index files...
> Picked up JAVA_TOOL_OPTIONS: 
> Loading configuration...
> Initializing packages...
> Preparing boards...
> java.lang.NullPointerException
> 	at processing.app.BaseNoGui.onBoardOrPortChange(BaseNoGui.java:679)
> 	at processing.app.Base.onBoardOrPortChange(Base.java:1317)
> 	at processing.app.Base.<init>(Base.java:284)
> 	at processing.app.Base.main(Base.java:151)
> [Error] Exit with code=255

**Comment by dooriya** [comment]
Please refer to the installation section in https://microsoft.github.io/azure-iot-developer-kit/docs/faq/

**Comment by bularond** [comment]
I installed arduino-1.8.6 and it start working

**Comment by Wulfheart** [comment]
> 
> 
> Please refer to the installation section in https://microsoft.github.io/azure-iot-developer-kit/docs/faq/

I'm unsure how this is related to the issue. I'm getting the same error.
