### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by larryyyyy** [Microsoft/vscode-arduino#801]
- Issue Type: `Performance`
- Extension Name: `vscode-arduino`
- Extension Version: `0.2.25`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/lawrenceho/vsciot-vscode.vscode-arduino-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by lirenhe** [comment]
Duplicate of #785
