### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by medianetix** [Microsoft/vscode-arduino#809]
- Issue Type: `Performance`
- Extension Name: `vscode-arduino`
- Extension Version: `0.2.25`
- OS Version: `Linux x64 4.15.0-48-generic`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/hthurat/vsciot-vscode.vscode-arduino-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by czgtest** [comment]
duplicate with #785
