### ISSUE TITLE
Arduino ide not found in mac 

### ISSUE THREAD

**Issue by shadababe04** [microsoft/vscode-arduino#825]
i install the arduino ide already but still got error of 
cannot found Arduino IDE.but i check Arduino is installed in Applications founder and working very fine

**Comment by shadababe04** [comment]
Cannot find Arduino IDE. Please specify the "arduino.path" in the User Settings. Requires a restart after change.

**Comment by ArthurMa1978** [comment]
yes, it's specified in https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-arduino-iot-devkit-az3166-get-started#prepare-the-development-environment
