### ISSUE TITLE
intelliSenseEngine doesn't work as default

### ISSUE THREAD

**Issue by IQ-raf** [microsoft/vscode-arduino#831]
having `  "C_Cpp.intelliSenseEngine": "Tag Parser"` makes the C/C+ extension not work properly. For example, I can write a line without a semicolon at the end and it won't throw me an error until I compile. and another example is the autocomplete from a class will also list me every single method from every file included instead of just the ones from this class.

Unfortunately, I need  ` "C_Cpp.intelliSenseEngine": "Tag Parser"` so that vsc doesn't throw an error for every file I include (and Arduino methods such as `Serial`).

It would be great if this extension worked with   "C_Cpp.intelliSenseEngine": ` set to `"default'`

**Comment by adiazulay** [comment]
Tracking this with #438
