### ISSUE TITLE
Output window showing garbled character

### ISSUE THREAD

**Issue by Move2win** [microsoft/vscode-arduino#837]
**Output window showing garbled character after clicked "Arduino: Verify"**

System: Windows8.1 64-bits
System Language and Region: Chinese(Simplified Chinese, People Republic of China)
VS Code & Extensions: latest version
VS Code Language: Chinese(Simplified) using Language Pack for Visual Studio Code

**OUTPUT WINDOW INCLUDE**

[Starting] Verify sketch - Lesson1.Lighting_LED.ino
[Warning] Output path is not specified. Unable to reuse previously compiled files. Verify could be slow. See README.
姝ｅ湪鍔犺浇閰嶇疆...
姝ｅ湪鍒濆鍖栧寘...
姝ｅ湪鍑嗗寮€鍙戞澘...
姝ｅ湪楠岃瘉...
椤圭洰浣跨敤浜� 736 瀛楄妭锛屽崰鐢ㄤ簡 (2%) 绋嬪簭瀛樺偍绌洪棿銆傛渶澶т负 32256 瀛楄妭銆�
鍏ㄥ眬鍙橀噺浣跨敤浜�9瀛楄妭锛�(0%)鐨勫姩鎬佸唴瀛橈紝浣欑暀2039瀛楄妭灞€閮ㄥ彉閲忋€傛渶澶т负2048瀛楄妭銆�
[Done] Finished verify sketch - Lesson1.Lighting_LED.ino

![屏幕截图(573)](https://user-images.githubusercontent.com/45490638/59960637-bc66c800-94fd-11e9-9226-e226781d7a3a.png)

**Comment by tkhub** [comment]
The problem is not fixed yet.
But,  we can fix it by comment out.
The comment out line is bellow. This counter-measure is well known in Japan.
![image](https://user-images.githubusercontent.com/24850071/98254389-92f9ef80-1fbf-11eb-9c93-0ee862f64517.png)
