### ISSUE TITLE
Triage #694

### ISSUE THREAD

**Issue by disconn3ct** [microsoft/vscode-arduino#841]
Slackbot: 

> Please feel free to open a new issue if you would like further discussion. Thank you for your contributions.

Any discussion at all on #694 would be great.

**Comment by robotdad** [comment]
Linked issue closed as stale, generally I don't think we should have issues to look at issues. The linked issue should be reactivated if it needs to be looked at.

**Comment by disconn3ct** [comment]
Which is true? The bot says open a new ticket.

**Comment by robotdad** [comment]
Ah, sorry for the confusion. I didn't review the posts from the bot. I reactivated #694 for when we do a pass over IntelliSense issues.

**Comment by disconn3ct** [comment]
Appreciate it! Will that keep it from going stale again?
