### ISSUE TITLE
Can't verify or compile ESP8266 libs

### ISSUE THREAD

**Issue by Nathan-ma** [microsoft/vscode-arduino#843]
Hello, it seems vscode extension for arduino cannot find basic Libraries like ESP8266WiFi.h

The same code compiles just fine on Arduino IDE, but it cannot even verify properly on vscode.

![image](https://user-images.githubusercontent.com/11060905/60539047-31968200-9ce2-11e9-9194-d8d1e3c44c2a.png)
I already included the path for my other libraries.

The problem seems to be with the command `#include ''`, this commands tells the compiler to search for files on the directory of the .ino file, thing is, the libs on esp8266 included that way are inside the src folder on the directory of the lib.

Here a few pictures to explain it better:
![image](https://user-images.githubusercontent.com/11060905/60539214-876b2a00-9ce2-11e9-97e2-1d1a7c99e451.png)

Vscode error, not been able to find the BearSSLHealpers.cpp inside the Webserver lib.

![image](https://user-images.githubusercontent.com/11060905/60539289-ac5f9d00-9ce2-11e9-9837-5aaf9f8aeb6d.png)
Arduino IDE can find it no problem... path is correct also.

and finally

![image](https://user-images.githubusercontent.com/11060905/60539325-c8fbd500-9ce2-11e9-862e-0566a9139d59.png)

so, the .h is inside src on the libs folder. arduino understands it just fine, but vscode try to look for the .h on the rootpath and returns me FILE NO FOUND.

How can I fix this?

**Comment by Nathan-ma** [comment]
@pmckinney1971 has fixed this with :
```
"includePath": [
                "C:\\Users\\Leonie\\Documents\\Arduino\\hardware\\esp8266com\\esp8266\\libraries\\ESP8266WiFi\\src",
                "C:\\Users\\Leonie\\AppData\\Local\\Arduino15\\packages\\esp8266\\tools\\**",
                "C:\\Users\\Leonie\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\2.5.0\\**",
                "C:\\Users\\Leonie\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\2.5.0\\libraries\\**",
                "C:\\Users\\Leonie\\AppData\\Local\\Arduino15\\**",
                "C:\\Users\\Leonie\\Documents\\Arduino\\hardware\\esp8266com\\esp8266\\**",
                "C:\\Users\\Leonie\\Documents\\Arduino\\libraries\\**",
                "${workspaceFolder}/**"
```
as its includePath, to directly include all the files inse the WiFi/src lib...

**Comment by ArthurMa1978** [comment]
thanks @Nathan-ma and @pmckinney1971
