### ISSUE TITLE
Can't select COM port

### ISSUE THREAD

**Issue by curdeveryday** [microsoft/vscode-arduino#846]
Since update to vscode v1.36.0, I can't select COM port.
![image](https://user-images.githubusercontent.com/39357306/60643317-3afc2780-9e65-11e9-8e2f-adc41177d800.png)

**Comment by curdeveryday** [comment]
I have rebuilt the module and move it in the extension folder. It works.

**Comment by ArthurMa1978** [comment]
Dup with #851

**Comment by ArthurMa1978** [comment]
Fixed since v0.2.27, thanks @curdeveryday
