### ISSUE TITLE
Update extension for June 2019 Vscode

### ISSUE THREAD

**Issue by aboulfad** [microsoft/vscode-arduino#848]
Arduino extension serial connection is broken with 2019 Update of Vscode, see details in issue #774 . Solution is in comment https://github.com/microsoft/vscode/issues/76538#issuecomment-508385062
Please update arduino extension to reflect new node version.

**Comment by ArthurMa1978** [comment]
We are working on the fix will release new version soon.

**Comment by ArthurMa1978** [comment]
Dup with https://github.com/microsoft/vscode-arduino/issues/851

**Comment by ArthurMa1978** [comment]
Fixed since v0.2.27, thanks @aboulfad
