### ISSUE TITLE
Need VSCode commands to get sketchbook and package paths

### ISSUE THREAD

**Issue by bfxdev** [microsoft/vscode-arduino#849]
If you look at the [tutorial I wrote for VSCode with Arduino/Gamebuino](https://github.com/bfxdev/Arduino/blob/master/VSCode/README.md), you will see my proposal for a c_cpp_settings.json file that is supposed to be compatible with all flavors of Arduino IDE, on Linux, Windows and macOS.

You can notice that it is always the same board-specific block, adapted to the different paths of the "Sketchbook" and "packages" folder (using environment variables).
I normally include this kind of file in the GIT repository of a sketch such that anybody can clone it and work with VSCode directly.

I would love to simplify it by directly referencing the paths as determined by the arduino extension. Any [automatic insertion of paths by the extension](https://github.com/microsoft/vscode-arduino/issues/438) could as well benefit from this  feature. Adding automatically-adapted paths with these new commands would better support collaboration.

A possible implementation should take the form of [VSCode commands](https://code.visualstudio.com/docs/editor/variables-reference#_command-variables) that returns the [package and sketchbook paths as determined internally](https://github.com/microsoft/vscode-arduino/blob/master/src/arduino/arduinoSettings.ts).

Comments welcome!

**Comment by adiazulay** [comment]
IntelliSense auto-generation has been added in v0.4.0. If you're having any problems with IntelliSense please open a new issue.
