### ISSUE TITLE
Unable to start serial monitor

### ISSUE THREAD

**Issue by szormok** [microsoft/vscode-arduino#851]
The serial monitor worked fine but couple of days ago something happened because If I try to open the following error appears:
"Failed to open serial port COM6 due to error: + TypeError: Cannot read property 'close' of null"
Similar as in issue #596.
Also I am not able to change the serial port because the dialog not opens.
I have the latest 1.36.0 and 0.2.26 version.
By the way the uploading works! So the port is alive.
And also in the Arduino IDE everything is fine.

**Comment by MichaelPfezer** [comment]
Same issue here

**Comment by CodeNameHawk** [comment]
Same issue here

**Comment by rido-min** [comment]
I also see this issue

**Comment by rafalp9728** [comment]
Also have this issue. It started after update to VS Code 1.36.0.
I see it's been reported already in issue #848.

**Comment by Cube-Line** [comment]
+1  like:   ----->>>>     Failed to open serial port COM3 due to error: + TypeError: Cannot read property 'close' of null

**Comment by ArthurMa1978** [comment]
We are working on the fix will release new version soon.

**Comment by ArthurMa1978** [comment]
Fixed since v0.2.27, thanks @szormok @rido-min @MichaelPfezer @CodeNameHawk @Cube-Line @rafalp9728 .

**Comment by DanwithArduino** [comment]
trying to change the serial port "crashes the extension host".

**Comment by CodeNameHawk** [comment]
@ArthurMa1978 
now work Select Serial Port, and Open Serial Monitor,
but I use an USB-COM adapter FTDI FT232RL with control DTR and RTS, to automatic programming ESP8266
Unfortunately, the plugin incorrectly sets the levels to DTR and RTS, which does not allow to use normally Serial Monitor

**Comment by ArthurMa1978** [comment]
@CodeNameHawk thanks for report this, can you help to file a new issue to us?

**Comment by CodeNameHawk** [comment]
@ArthurMa1978 Ok.

**Comment by dzuda11** [comment]
> We are working on the fix will release new version soon.

Hey!! We have the same issues again with VS Code v1.40.1. can you fix it again or show how can it be fixed? Than you!

**Comment by xinyiz1226** [comment]
Duplicate with #918 , we are working on the fix and will let you know when it is ready.

**Comment by fmlin429** [comment]
Have the problem resolved? looks like I have the same issue.

**Comment by dzuda11** [comment]
> Have the problem resolved? looks like I have the same issue.

Did you update VS Code and extension?
If you are up-to-date then we have the same problem again....

**Comment by cooperbaker** [comment]
Same problem here :(

**Comment by dzuda11** [comment]
> Same problem here :(

Duplicated with #980 
Downgrade VS code to 1.42 and wait for Arduino extension update....

**Comment by wouterds** [comment]
> Downgrade VS code to 1.42 and wait for Arduino extension update....

Can confirm that downgrading to [January 2020 release](https://code.visualstudio.com/updates/v1_42) works ❤️!

**Comment by DeadpoolKerns** [comment]
I am having the same issue and would love to downgrade but it appears that the January version is only offering a Win64 release. I downloaded the file VSCodeUserSetup-x64-1.42.1.exe.  Although the download link has a reference of https://update.code.visualstudio.com/1.42.1/win32-x64-user/stable ,which might infer an offer for 32 or 64 bit installations, the download was a Win64 release.

Where can I download the 1.42.1 Win32 release?

**Comment by 333fps** [comment]
https://az764295.vo.msecnd.net/stable/c47d83b293181d9be64f27ff093689e8e7aed054/VSCodeUserSetup-ia32-1.42.1.exe

**Comment by DeadpoolKerns** [comment]
Thank you very much 333fps. I installed 1.42.1 and the serial monitor is functioning as expected again. You've made my day. Now on to getting used to Vscode :+1:  after using arduino UI  :(  for so long

**Comment by GregTerrell** [comment]
> I am having the same issue and would love to downgrade but it appears that the January version is only offering a Win64 release. I downloaded the file VSCodeUserSetup-x64-1.42.1.exe. Although the download link has a reference of https://update.code.visualstudio.com/1.42.1/win32-x64-user/stable ,which might infer an offer for 32 or 64 bit installations, the download was a Win64 release.
> 
> Where can I download the 1.42.1 Win32 release?

https://code.visualstudio.com site, then click Updates. This is a history of monthly releases. The link below is the redirect as of today. Left navigation to January 2020 is 1.42.1. Confirmed that rolling back to 1.42.1 fixes the serial monitor fails to open for my Windows10 install.

https://code.visualstudio.com/updates/v1_43

**Comment by DeadpoolKerns** [comment]
Thanks Greg but the file I referenced in my comment came from that site. The only January version available for download is the win64 version. This will not install on my Windows 7 32 bit OS

**Comment by Awbmilne** [comment]
@fmlin429 @dzuda11 @cooperbaker @wouterds @DeadpoolKerns 

I created issue #1002 for this problem resurfacing, please post a comment there aswell. Thanks!!
