### ISSUE TITLE
Disconnecting Arduino (CH340) while Serial is connected, crashes Extension Host

### ISSUE THREAD

**Issue by iqapps** [microsoft/vscode-arduino#857]
While developing code for Arduino's you often need to disconnect Arduino to test some special functions.

If you disconnect the Arduino while the Serial Monitor has the Serial Port opened, the Visual Studio Code Extension Host crashes and shows the "Restart Extension Host" button.

Could we please have it so that the Serial Monitor just closes the serial port silently when the Arduino is disconnected.

**Comment by ameer1234567890** [comment]
happens for me too

**Comment by gcampbell-msft** [comment]
@iqapps We have recently updated the Arduino extension to depend on a new standalone Serial Monitor extension, please upgrade your arduino extension and try out this new feature! 

Let us know if it solves your issue!
