### ISSUE TITLE
Serial monitor not working on ESP32

### ISSUE THREAD

**Issue by WilliamAtek** [microsoft/vscode-arduino#865]
With the esp32 and ftdi. The problem is caused by the DTR line pulled LOW keeping the esp32 in reset state. You have to let the dtr going back HIGH so that the esp32 can reboot.

If not the serial won't work.

**Comment by ArthurMa1978** [comment]
This is a problem from esp32 sdk, please open issue in https://github.com/espressif/arduino-esp32
