### ISSUE TITLE
Status bar always active

### ISSUE THREAD

**Issue by jscheel** [microsoft/vscode-arduino#877]
Not sure if something has changed on my end, but my status bar always shows all of the arduino actions now, even in projects/files that have nothing to do with arduino.

**Comment by zunhu** [comment]
@jscheel what's your OS, Arduino, Arduino extension version?

and can you please paste screenshot for it?

**Comment by zunhu** [comment]
not sure if it is temporary issue, since long time no active, issue closed, please assign another issue if still happen.

**Comment by jscheel** [comment]
MacOS 10.12.5

Name: Arduino
Id: vsciot-vscode.vscode-arduino
Description: Arduino for Visual Studio Code
Version: 0.2.27
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-arduino

Interestingly, it only seems to appear in some windows. Here it is in a completely unrelated project on a .jsx (react) file.

![Screen Shot 2019-08-20 at 10 58 01 AM](https://user-images.githubusercontent.com/211478/63363546-6ebdde80-c339-11e9-9686-b1a24192b88f.png)

**Comment by jscheel** [comment]
@zunhu sorry for the delay, been in a hole ^^
