### ISSUE TITLE
Weird arduino serial output

### ISSUE THREAD

**Issue by realivanjx** [microsoft/vscode-arduino#879]
When i compile any code that uses `Serial.print` it prints very weird message:

![image](https://user-images.githubusercontent.com/12814796/62632870-676ffb80-b95d-11e9-88e6-3b7545bb3f37.png)

![image](https://user-images.githubusercontent.com/12814796/62632909-7a82cb80-b95d-11e9-9b90-83490641be67.png)

But when i copied all my code to the original arduino ide and upload it from there, it works just fine:

![image](https://user-images.githubusercontent.com/12814796/62633035-b3bb3b80-b95d-11e9-917f-5e7e190c135a.png)

![image](https://user-images.githubusercontent.com/12814796/62632998-a1d99880-b95d-11e9-98c5-9b0eb06ef4f8.png)

Why this happens?

**Comment by zunhu** [comment]
@realivanjx what's your OS? 
looks similar with https://forum.arduino.cc/index.php?topic=76658.0

**Comment by realivanjx** [comment]
Windows 10 latest

**Comment by zunhu** [comment]
same issue with #875 , mark as bug.

**Comment by zunhu** [comment]
1, try to find file C:\Users\username\.vscode\extensions\vsciot-vscode.vscode-arduino-0.2.27\out\src\common\util.js
2. commented out line:215.
3. restart vscode.
