### ISSUE TITLE
Cannot set output folder using Environment Variable

### ISSUE THREAD

**Issue by dasfdlinux** [microsoft/vscode-arduino#880]
When attempting to set an Output folder in Windows using an environment variable, it is getting treated as a relative path. Am I using the environment variables incorrectly? I referenced [https://code.visualstudio.com/docs/editor/variables-reference#_environment-variables](https://code.visualstudio.com/docs/editor/variables-reference#_environment-variables) and #450 

arduino.json
`{
    "port": "COM5",
    "board": "arduino:avr:pro",
    "sketch": "wireless_temperature.ino",
    "programmer": "AVRISP mkII",
    "configuration": "cpu=8MHzatmega328",
    "output": "${env:TEMP}/arduinoBuild"
}`

Error:
> Please check the "output" in the sketch Settings.Cannot find the output path:c:\Users\dshaffer\Documents\Misc Code\wireless_temperature\${env:TEMP}\arduinoBuild

VS Code 1.36.1
Arduino 0.2.27
Windows 10

**Comment by dilin-MS** [comment]
Hi, the `${variableName}` syntax is supported in VS Code's built-in `launch.json` and `tasks.json` files( as the [link](https://code.visualstudio.com/docs/editor/variables-reference#_environment-variables) suggests). Currently arduino extension's configuration file `arduino.json` does not support the environment variable.

**Comment by dasfdlinux** [comment]
Thanks, I see that now. I clearly skimmed over the first paragraph on that page. This would be a great enhancement.

**Comment by BeautifulNow97** [comment]
Cannot find the sketch file.
编译出现

**Comment by tsbertalan** [comment]
Bumping this -- I want to be able to have one `arduino.json` file that both Windows and Linux machines use for compilations (or even Windows machines with different usernames), and have my output dir in like `~/tmp/arduino_output/`.
