### ISSUE TITLE
Snippets doesn't work

### ISSUE THREAD

**Issue by swortain** [microsoft/vscode-arduino#883]
I set "arduino path" and "command path" and open folder in vscode. But there is no snippets in .ino files.... Is there something wrong?
![image](https://user-images.githubusercontent.com/6780386/63754408-64768400-c8e7-11e9-9b9b-783be4da81ca.png)

**Comment by zunhu** [comment]
since you created new project, it is empty as design.

**Comment by swortain** [comment]
emmm....Sorry,I don't get the point.....what shall I do to enable the snippets...

**Comment by swortain** [comment]
And thanks for the reply!

**Comment by swortain** [comment]
got it...arduino board should be set at first...
