### ISSUE TITLE
Integrated functions undefined - bug

### ISSUE THREAD

**Issue by DoganM95** [microsoft/vscode-arduino#886]
### Sample of what i am trying to test on my ESP32:

![image](https://user-images.githubusercontent.com/38842553/63955825-a3dad700-ca85-11e9-92ec-027becac6a3a.png)
---
![image](https://user-images.githubusercontent.com/38842553/63956818-7c850980-ca87-11e9-8399-1e2a6cde8d44.png)

### The integrated functions of arduino ide are not working, e.g. `Serial`, but as soon as i include any library from Library Manager (even the ones which have noting to do with Serial), the internal functions get recognized.

![image](https://user-images.githubusercontent.com/38842553/63956090-1a77d480-ca86-11e9-9f15-946e36382cc7.png)

### Result:
![image](https://user-images.githubusercontent.com/38842553/63956183-3ed3b100-ca86-11e9-82ea-5ef5f8f842fc.png)
---
![image](https://user-images.githubusercontent.com/38842553/63957002-e00f3700-ca87-11e9-83de-5dd135fa53a0.png)

**Comment by zunhu** [comment]
Hi, may I know how can repro this issue? is uninstall all library?

![63955825-a3dad700-ca85-11e9-92ec-027becac6a3a](https://user-images.githubusercontent.com/40815873/63990704-9bcb7780-cb17-11e9-8124-5a0fe4ccdf24.png)

**Comment by beeb** [comment]
Can confirm this also happens on my end.

**Comment by adiazulay** [comment]
IntelliSense auto-generation has been added in v0.4.0. If you're having any problems with IntelliSense please open a new issue.
