### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by hamzbond** [microsoft/vscode-arduino#888]
- Issue Type: `Bug`
- Extension Name: `vscode-arduino`
- Extension Version: `0.2.27`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.38.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 20348,
		"activateCallTime": 2109,
		"activateResolvedTime": 0,
		"activationEvent": "*"
	},
	"runtimeErrors": []
}
```

**Comment by zunhu** [comment]
hi, can you please provide more details then I will try to repro on my side.
