### ISSUE TITLE
Missing Commands

### ISSUE THREAD

**Issue by mnebesny** [microsoft/vscode-arduino#894]
When I try to install, not all of the commands are there. It is notably missing Arduino: Initialize and a few others. How do I fix this?

![Screenshot from 2019-09-19 16-40-05](https://user-images.githubusercontent.com/46246628/65279433-30643c80-dafc-11e9-96eb-d88e06ae3a8d.png)

**Comment by zunhu** [comment]
hi, looks your screenshot is for settings, for commands you can try to "command palette" (ctrl+shift+P) to open command window. it will list all commands of Arduino.
![image](https://user-images.githubusercontent.com/40815873/65298909-dae16b80-db9f-11e9-92d5-be1a0b38d84c.png)

**Comment by mnebesny** [comment]
Thanks for the help, but the same commands are still missing. When I try to manually enter commands like Arduino: Initialize or Arduino: Examples it just opens the settings.

![Screenshot from 2019-09-20 22-06-25](https://user-images.githubusercontent.com/46246628/65366516-f9248700-dbf2-11e9-8832-7b45d245d83e.png)

**Comment by zunhu** [comment]
hi, can you please type "Arduino" in command box then it will be filter all commands of Arduino.

Otherwise, I can't repro this issue on my side, maybe you can try to uninstall\ install Arduino Extension and Arduino IDE and try again.
