### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by nikschwe** [microsoft/vscode-arduino#896]
- Issue Type: `Performance`
- Extension Name: `vscode-arduino`
- Extension Version: `0.2.27`
- OS Version: `Darwin x64 18.7.0`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/nikschwe/vsciot-vscode.vscode-arduino-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by emitchel** [comment]
correct url https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load
