### ISSUE TITLE
Is ip port supported for yun?

### ISSUE THREAD

**Issue by ssduracell** [microsoft/vscode-arduino#901]
i can only select serial ports is there a way i can connect with an ip? 
needed for dragino etc.

thanks!

**Comment by zunhu** [comment]
hi, select serial port is to connect with boards. 
May I know more details of your problem?

**Comment by ssduracell** [comment]
i want to connect to my dragino (arduino yun + arduino uno) gateway over my network but my arduino ide doesnt find lg01

**Comment by skoky** [comment]
I wish to connect to YUN with IP console as well

**Comment by robotdad** [comment]
I realize serial isn't the right label here but it seems worth considering within context of discussions there.

**Comment by gcampbell-msft** [comment]
@skoky @ssduracell We have recently updated the Arduino extension to depend on a new standalone Serial Monitor extension, please upgrade your arduino extension and try out this new feature! The new Serial Monitor extension supports a TCP mode, maybe this would fit your needs?

Let us know if it solves your issue or if the issue still persists!
