### ISSUE TITLE
.github/workflows/main.yml

### ISSUE THREAD

**Issue by Jonirutclub** [microsoft/vscode-arduino#904]
.github/workflows/main.yml #903 @Atalanttore 
![2019-08-22](https://user-ima[Jonirutclub.github](.github/workflows/main.yml) `ges.githubusercontent.com/55123685/65766379-01317900-e155-11e9-824f-8b42b92b3ba5.jpg)`

> ### 

- _**

1. 

- [ ] 

**_

**Comment by zunhu** [comment]
#903 dev is working on that.
