### ISSUE TITLE
Error trying to program ATtiny85 with VSCode

### ISSUE THREAD

**Issue by arvobowen** [microsoft/vscode-arduino#908]
I'm trying my best to use VSCode to replace some of my IDEs but having some issues when using it for Arduino programming.

I have my project/sketch (*.ino) that I have verified and uploaded to my **ATtiny85** chip via the Arduino Uno board I have. So I know the way I have everything hooked up and how I'm trying to do it (board config, programmer, etc) works fine.

However, when I try to use VSCode I just get `[Error] Exit with code=1` returned when I try to upload my sketch to the chip. I can't find anywhere else to see any more debug information. I currently have the Arduino, C/C++, Notepad++ keymap extensions installed for VSCode.

My settings (settings.json) for the Arduino extension are...
```
{
    "workbench.startupEditor": "newUntitledFile",
    "explorer.confirmDelete": false,
    "C_Cpp.updateChannel": "Insiders",
    "explorer.confirmDragAndDrop": false,
    "arduino.additionalUrls": "https://raw.githubusercontent.com/damellis/attiny/ide-1.6.x-boards-manager/package_damellis_attiny_index.json"
}
```

My settings (arduino.json) for my Arduino project are...
```
{
    "sketch": "powersupply.ino",
    "board": "attiny:avr:ATtinyX5",
    "port": "COM3",
    "programmer": "Arduino as ISP",
    "output": "../builds/PowerSupply",
    "configuration": "cpu=attiny85,clock=internal8"
}
```

Has anyone tried to use VSCode to program their ATtiny85 before and ran into this issue?

**Comment by arvobowen** [comment]
Version: 1.39.0 (user setup)
Commit: 9df03c6d6ce97c6645c5846f6dfa2a6a7d276515
Date: 2019-10-09T06:58:04.439Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

Name: Arduino
Id: vsciot-vscode.vscode-arduino
Description: Arduino for Visual Studio Code
Version: 0.2.27
Publisher: Microsoft

**Comment by mMerlin** [comment]
I do not use ATtiny85.  However, since you have "output": "../builds/PowerSupply" configured, what gets created in that folder?  Is there a log there that says what was happening just before the upload error?  From current information, I assume the compile worked fine.

**Comment by arvobowen** [comment]
As a matter of fact, it is working now.  Absolutely NOTHING was changed.  I just closed the IDE, restarted my machine (for other reasons) and when I went back to it trying to get it to work...  It just did!

Not sure what I did to resolve the issue but I can now flash the ATtiny with no issues at all.
