### ISSUE TITLE
Travis Node.js: 11 job failing

### ISSUE THREAD

**Issue by jayvdb** [microsoft/vscode-arduino#911]
On https://github.com/microsoft/vscode-arduino/pull/910 I see failures on the Node 11 job only, that look unrelated to the PR changes.

https://travis-ci.org/microsoft/vscode-arduino/jobs/597960540

**Comment by hellyzh** [comment]
The Travis CI build passed now.

**Comment by jayvdb** [comment]
Awesome thanks.  Should I rebase my PR, or will it be reviewed as-is?

**Comment by hellyzh** [comment]
No need, we will review.
