### ISSUE TITLE
arduino 1.8.10 中文乱码

### ISSUE THREAD

**Issue by VirensCn** [microsoft/vscode-arduino#912]
配合arduino 1.8.10 时，输出控制台中文乱码
![O3CJS`(61 @KK{HI4K}3}WC](https://user-images.githubusercontent.com/9736815/67019090-b3de7100-f12e-11e9-864d-888e680a48e5.png)

**Comment by zunhu** [comment]
can you please try : https://github.com/microsoft/vscode-arduino/issues/875
