### ISSUE TITLE
Can't install libraries from Vscode for ESP8266

### ISSUE THREAD

**Issue by gtleon** [microsoft/vscode-arduino#930]
Hello!

Please tell me I would like to create a portable version of the plugin for Arduino for vscode.

In the Arduino app, I changed the location of the Arduino system folders.

In the plugin for VSCode, I changed the folder location to the ones I needed.

Basic standard sketches are verified.

1) Can't install libraries from Vscode for ESP8266 (via Arduino distribution installed).

2) After installing libraries for ESP8266 through Arduino IDE, can't verify sketch.

Thanks in advance!

**Comment by hellyzh** [comment]
Support custom libraries with portable version of Arduino #946

**Comment by DrXoo** [comment]
> Support custom libraries with portable version of Arduino #946

If this is already solved then the Issue can be closed?
