### ISSUE TITLE
VS Code November update broke the extension

### ISSUE THREAD

**Issue by iMina** [microsoft/vscode-arduino#932]
The extension was working fine until VS Code updated this month. Now, the COM port selection and the Serial monitor are not working at all.
When I try to open the serial monitor, the extension gives this error : 

> Failed to open serial port COM30 due to error: + TypeError: Cannot read property 'close' of null.

I can manually change the COM port in arduino.json file, but the serial monitor cannot be opened, and switching to the serial monitor from the output window opens it, but connecting to the port does not work at all and displays this line along with the previous error :
> [Starting] Opening the serial port - COM30

**Comment by xinyiz1226** [comment]
Duplicate with #918
