### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by luxmorpheux** [microsoft/vscode-arduino#939]
- Issue Type: `Performance`
- Extension Name: `vscode-arduino`
- Extension Version: `0.2.28`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Button\vsciot-vscode.vscode-arduino-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by hellyzh** [comment]
correct url: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by hellyzh** [comment]
Close the issue because it doesn't have recent activity. Please feel free to open a new issue if you would like further discussion. Thank you for your contributions.
