### ISSUE TITLE
Save the last used end of line

### ISSUE THREAD

**Issue by MagTun** [microsoft/vscode-arduino#952]
Please add a way to save the last used end of line so we don't have to select it again each time. One way of doing could be via settings.json

Thanks!

**Comment by hellyzh** [comment]
Thank you for your advice. Do you have more details?

**Comment by MagTun** [comment]
No, I don't know how to implement this, I just know many extensions use the settings.json to store such users preferences.

**Comment by hellyzh** [comment]
What do you mean the last use end of line? is it the selection after click `Arduino: Open Serial Monitor` like "No line ending", "Newline" ...

**Comment by MagTun** [comment]
Yes this is what I mean:  when I want to send text to my connected device, I always have to make sure the end of line is the right one because each time I restart vscode the line ending is set back "No line ending" and not the one I usually use (ex: Newline). If my choice was saved in settings.json, then each time vscode would restart, it will automatically set the end of line to the one I want (ex: Newline and not "No line ending")

I also have to make sure the end of line is the right after I have to "restart extension host" because I unplugged a device connected to serial monitor without closing the serial monitor first (by the way. that would be great if there was a way to prevent the crashing of "extension host" in this case but this is another issue).

**Comment by Xepol** [comment]
I issued a pull request (baud_fix) that covers this.  Also you to set this before opening the serial monitor.  Hope they accept it in to the main branch soon.

**Comment by hellyzh** [comment]
Arduino extension 0.3.0 has been released. It removed the selection of ending line and use new line with `/r/n` as default.

**Comment by MarcoRBosco** [comment]
How do we change now the ending line? If  for example we need no line ending instead of `/r/n`. Thank you!

**Comment by roninbar** [comment]
I don't understand how to select a line ending other than `/r/n`. Why is there an option in the status bar to change the baud rate but no option to change the line ending? (v0.4.3)
