### ISSUE TITLE
Update / Install Package Error 255

### ISSUE THREAD

**Issue by ttins** [microsoft/vscode-arduino#961]
If following this tutorial "https://docs.microsoft.com/en-us/samples/azure-samples/mxchip-iot-devkit-get-started/sample/" make sure to install Arduino IDE 1.8.6.

**Comment by hellyzh** [comment]
I can reproduce the issue on Arduino IDE 1.8.11 but not on 1.8.6. Please try to add Environment Variable **PATH** to include path `C:\Program Files (x86)\Arduino`.

**Comment by hellyzh** [comment]
The tutorial should work without changing environment variable using Arduino IDE 1.8.12 which is just released.
