### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Maaruuuuuul** [microsoft/vscode-arduino#971]
- Issue Type: `Performance`
- Extension Name: `vscode-arduino`
- Extension Version: `0.2.29`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.42.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\adrie\vsciot-vscode.vscode-arduino-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by elektronikworkshop** [comment]
The CPU-profile file is missing:
> :warning: Make sure to **attach** this file from your *home*-directory:
> :warning: `C:\Users\adrie\vsciot-vscode.vscode-arduino-unresponsive.cpuprofile.txt`
