### ISSUE TITLE
Extension don't see standard arduino boards.

### ISSUE THREAD

**Issue by OlegKuch** [microsoft/vscode-arduino#973]
There is digispark, esp, stm boards in list of boards, but there are not standard arduino boards.

**Comment by hellyzh** [comment]
You can save URL of boards you need to `arduino.additionalUrls` according to [guide](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-arduino) to get the specified boards.

**Comment by hellyzh** [comment]
Close the issue because it doesn't have recent activity. Please feel free to open a new issue if you would like further discussion. Thank you for your contributions.
