### ISSUE TITLE
Cannot find Arduino IDE. 

### ISSUE THREAD

**Issue by Ilie24118** [microsoft/vscode-arduino#979]
![Screenshot-20200305140739-1920x1080](https://user-images.githubusercontent.com/43288147/75980347-f55b9700-5eea-11ea-89dc-28b7c8213aba.png)

**Comment by DrXoo** [comment]
Please execute the command Arduino: Initialize to create the arduino.json file. Inside you can specify the path

**Comment by dilin-MS** [comment]
Hi @Ilie24118 , is the issue resolved for you?

**Comment by Ilie24118** [comment]
no

**Comment by hellyzh** [comment]
Arduino extension v0.3.0 is released to fix serial port issue which requires vscode 1.43, please try to open an arduino example using the extension.

**Comment by El-Programador4** [comment]
I have the same problem as the author, and I don't know how to solve it!

**Comment by hellyzh** [comment]
@El-Programador4, have you installed [Arduino IDE](https://www.arduino.cc/en/Main/Software) ?

**Comment by Ilie24118** [comment]
Yes

**Comment by hellyzh** [comment]
@Ilie24118 , Please try to set `arduino.path` to `C:\\Program Files (x86)\\Arduino` (the path of your Arduino IDE) and `arduino.commandPath` to `arduino_debug.exe` and restart your vscode.
