### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by MyFutureIsAMess** [microsoft/vscode-arduino#987]
- Issue Type: `Performance`
- Extension Name: `vscode-arduino`
- Extension Version: `0.2.29`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.43.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Y50c\vsciot-vscode.vscode-arduino-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by hellyzh** [comment]
Arduino extension v0.3.0 is released to fix serial port issue which requires vscode 1.43.
