### ISSUE TITLE
Similar to issue #927 - no serial port choice for VS Code

### ISSUE THREAD

**Issue by micahalan** [microsoft/vscode-arduino#989]
I am currently having this same issue as issue #927  with version 1.43.0

The serial port "link" does nothing when I click on it, or try and reach that functionality through other menus.

**Comment by rneurink** [comment]
Same issue here. I can select boards but the serial port selection trough the status bar or through the command does not work a.t.m.

**Comment by Jojojdotpng** [comment]
You can try downgrading VSCode to version [v1.42](https://code.visualstudio.com/updates/v1_42). it  worked fine on my machine

**Comment by micahalan** [comment]
Thanks @Jojojdotpng !! Good idea and it seems to have worked.

**Comment by BinaryHole** [comment]
I am having the same issue.
VSCode - 1.43.1
Electron - 7.1.11

**Comment by rockboynton** [comment]
Same issue 1.43.1

**Comment by dilin-MS** [comment]
Dulpicate with #980
