### ISSUE TITLE
cannot select port & cannot open port

### ISSUE THREAD

**Issue by VulcanLIU** [microsoft/vscode-arduino#991]
Issue Type: <b>Bug</b>

when I click "<Select serial port>",My Visual code doesn't  popup the list of COM as before.I type "port": "COM3" in arduino.json by hand and try to open port.My Visual code told me ”Failed to open serial port com3 due to error: + TypeError: Cannot read property 'close' of null”. My arudino IDE version is 1.8.9.

Extension version: 0.2.29
VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.51GB free)|
|Process Argv|C:\Users\Vulca\Desktop\1\1|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by dilin-MS** [comment]
Hi, can you take a look and see if the issue you met is the same as #980 ? Thanks!
