### ISSUE TITLE
COM port selection stop working after vscode v1.43 update

### ISSUE THREAD

**Issue by flautines** [microsoft/vscode-arduino#997]
Issue Type: <b>Bug</b>

After upgrading Visual Studio Code to v1.43, COM selection is not working anymore.

Steps to reproduce the isse:
At the Arduino extension bottom bar click on the "Select Serial Port" button.

expected result:
A list of available ports should open in a listbox in the Editor window.

actual result:
Nothing happens

Extension version: 0.2.29
VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (11.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by dilin-MS** [comment]
Duplicate with #980
