### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by JENkt4k** [microsoft/vscode-arduino#999]
- Issue Type: `Bug`
- Extension Name: `vscode-arduino`
- Extension Version: `0.2.29`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.43.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 802,
		"activateCallTime": 392,
		"activateResolvedTime": 0,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "vsciot-vscode.vscode-arduino",
				"_lower": "vsciot-vscode.vscode-arduino"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [
		{
			"name": "TypeError",
			"message": "Cannot read property 'close' of null"
		}
	]
}
```

**Comment by hellyzh** [comment]
Arduino extension v0.3.0 is released to fix serial port issue which requires vscode 1.43.
